### ISSUE TITLE
Crash loop upgrading from 1.53.x to 1.54+

### ISSUE THREAD

**Issue by vmstan** [n8n-io/n8n#10420]
### Bug Description

I'm currently running n8n in a Kubernetes environment, with a dedicated external Postgres 16 database. I have been running 1.53.x attempting to move to 1.54.x or 1.55.x fails with a container crash loop with the following error:

```
2024-08-14 18:02:36.025Z,n8n-0,n8n,"User settings loaded from: /home/node/.n8n/config"
2024-08-14 18:02:39.589Z,n8n-0,n8n,"Last session crashed"
2024-08-14 18:02:49.598Z,n8n-0,n8n,"Initializing n8n process"
2024-08-14 18:02:50.925Z,n8n-0,n8n,"Error: There was an error initializing DB"
2024-08-14 18:02:50.925Z,n8n-0,n8n,"DatabaseError: no pg_hba.conf entry for host "10.118.0.7", user "n8n", database "n8n", no encryption"
```

Reverting the manifest back to 1.53.2 allows the pod to start. I reviewed the release notes for all versions between them, and didn't see anything about changes to Postgres configuration. I had a similar issue in #7413 that was resolved with SQL configuration options but not sure what to adjust this time.

Here is a redacted copy of the deployment manifest:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n
spec:
  selector:
    matchLabels:
      app: n8n
  serviceName: "n8n-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: n8n
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: c-4
      containers:
        - name: n8n
          image: ghcr.io/n8n-io/n8n:1.53.2
          resources:
            requests:
              memory: "512Mi"
              cpu: "125m"
            limits:
              cpu: "500m"
              memory: "2G"
          ports:
            - containerPort: 5678
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: data
            - mountPath: /root/do-certificate.crt
              subPath: do-certificate.crt
              name: do-certificate
              readOnly: true
          env:
            - name: GENERIC_TIMEZONE
              value: America/Chicago
            - name: TZ
              value: America/Chicago
            - name: N8N_ENCRYPTION_KEY
              value: xxxx
            - name: WEBHOOK_URL
              value: https://n8n.vmst.io/
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: http
            - name: N8N_EMAIL_MODE
              value: smtp
            - name: N8N_SMTP_HOST
              value: xxxx
            - name: N8N_SMTP_SSL
              value: "true"
            - name: N8N_SMTP_PORT
              value: "465"
            - name: N8N_SMTP_USER
              value: xxxx
            - name: N8N_SMTP_PASS
              value: xxxx
            - name: N8N_SMTP_SENDER
              value: n8n@ses.vmst.io
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_HOST
              value: xxxx
            - name: DB_POSTGRESDB_PORT
              value: "25060"
            - name: DB_POSTGRESDB_USER
              value: n8n
            - name: DB_POSTGRESDB_PASSWORD
              value: xxxx
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
              value: "false"
            # - name: DB_POSTGRESDB_SSL_CA
            #   value: /root/do-certificate.crt
            # - name: DB_POSTGRESDB_SSL_ENABLED
            #   value: "true"
          livenessProbe:
            tcpSocket:
              port: 5678
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5678
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 5678
            failureThreshold: 30
            periodSeconds: 5
            initialDelaySeconds: 30
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: do-certificate
          configMap:
            name: do-certificate
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
```

The commented out SSL settings were tried and resulted in different errors about a self-signed certificate being in the chain. No other database server configurations have been changed between the upgrade and downgrade attempts aside from the n8n version.

### To Reproduce

Attempt to upgrade from 1.53.x to 1.54.

### Expected behavior

n8n connects to the database

### Operating System

OS Containerized

### n8n Version

1.53 -> 1.54+

### Node.js Version

Node.js Version Containerized

### Database

PostgreSQL

### Execution mode

main (default)
