### ISSUE TITLE
Problems with Telegram Trigger module

### ISSUE THREAD

**Issue by Smacktur** [n8n-io/n8n#10485]
### Bug Description

Hi everyone! For some reason the Telegram Trigger module is not working. Everyone is writing about it. We can't find a solution to this problem.

When using the Telegram Trigger module, I get the error `Telegram Trigger: Bad Request: bad webhook: Failed to resolve host: Name or service not known`. I have never had any problems with webhooks. The host is open to the Internet.

1. I already gave a detailed answer here: https://community.n8n.io/t/telegram-triggers-dont-work/50872/9?u=smacktur.
2. The answer why `start --tunnel` did not work for me: https://community.n8n.io/t/telegram-triggers-dont-work/50872/10?u=smacktur.
3. I tried the recommendation with `NODEJS_PREFER_IPV4=true` from this thread: https://github.com/n8n-io/n8n/issues/9824#issuecomment-2195038460. Didn't help.

My config is `docker-compose`:
```yaml
version: '3'

Services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    expose:
      - “5678”
    labels:
      traefik.enable: “true”.
      traefik.http.routers.n8n-container.tls: “true”
      traefik.http.routers.n8n-container.tls.options: “no-strict-sni@file”
      traefik.http.routers.n8n-container.rule: “Host(`n8n.ХХХХ.tech`)”
      traefik.http.routers.n8n-container.entrypoints: “https”
      traefik.http.routers.n8n-container-http.rule: “Host(`n8n.ХХХХ.tech`)”
      traefik.http.routers.n8n-container-http.entrypoints: “http”.
      traefik.http.routers.n8n-container-http.middlewares: “default-https-redirect@file”.
      traefik.http.services.n8n-container.loadbalancer.server.port: “5678”
      traefik.http.services.n8n-container.loadbalancer.server.scheme: “http”
    environment:
      N8N_BASIC_AUTH_ACTIVE: “true”
      N8N_BASIC_AUTH_USER: “ХХХХ”.
      N8N_BASIC_AUTH_PASSWORD: “ХХХХ”
      N8N_HOST: “n8n.ХХХХ.tech”
      N8N_PORT: “5678”
      N8N_PROTOCOL: “https”
      NODEJS_PREFER_IPV4: true
      NODE_ENV: “production”
      WEBHOOK_URL: “https://n8n.ХХХХ.tech/”
      GENERIC_TIMEZONE: “ХХХХ”
      export N8N_LOG_LEVEL: “debug”
      export N8N_LOG_OUTPUT: “file”
      export N8N_LOG_FILE_LOCATION: “./n8n/logs/n8n.log”
      export N8N_LOG_FILE_MAXSIZE: “50”
      export N8N_LOG_FILE_MAXCOUNT: “60”
    volumes:
      - /opt/docker-n8n/n8n:/home/node/.n8n
      - /n8n-local-files:/files
```

I'm out of ideas((( Please help. Really need this function.

### To Reproduce

1. Adding **Telegram Trigger** module
2. Copy webhook (**Production URL**)
3. Enter the URL of my webhook here (to register it for Telegram):
`https://api.telegram.org/ЬотХХХХ/setWebhook?url=https://n8n.ХХХХ.tech/webhook/2e641c8b-bbe4-4781-bfc8-dfe6368e63a3/webhook`

This is what I get in response:
```json
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: bad webhook: Failed to resolve host: Name or service not known"
}
```
4. Result of `getWebhookInfo`: `https://api.telegram.org/ЬотХХХХ/getWebhookInfo`
```json
{
  "ok": true,
  "result": {
    "url": "",
    "has_custom_certificate": false,
    "pending_update_count": 2,
    "allowed_updates": [
      "message"
    ]
  }
}
```

PS: Of course I created and connected a Telegram Bot to the n8n.

### Expected behavior

I expect this module to work correctly and accept events from Telegram

### Operating System

Debian 6.1.90-1

### n8n Version

1.54.3

### Node.js Version

v20.15.0

### Database

SQLite (default)

### Execution mode

main (default)
