### ISSUE TITLE
Schedule node is not triggering workflows on set intervals. 

### ISSUE THREAD

**Issue by onlypfachi** [n8n-io/n8n#10653]
### Bug Description

I have just updated to version (initially)1.56.2 from 1.55.3, and now on version 1.57.0 but the issue is persistent. when trying to use the schedule node, at first you struggle to save the workflow it keeps giving the error `Workflow could not be activated: There was a problem activating the workflow: “ERROR: You specified an invalid ``date.”` but after some retries, it may save and you expect it to run on scheduled times but I got 2 executions before it completely stopped triggering and nothing. I has been like that now crippling our workflows.  

### To Reproduce

```
version: "3"
services:
  pgsql:
    image: "postgis/postgis:15-3.3-alpine"
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_PASSWORD=<redacted>
    expose:
      - 5432
    networks:
      - proxy
    volumes:
      - /mnt/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U postgres -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    container_name: "n8n"
    restart: always
    image: n8nio/n8n:1.56.2
    environment:
      - WEBHOOK_URL=<redacted>
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=pgsql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=<redacted>
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
      - NODE_OPTIONS=--max_old_space_size=8000
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - N8N_LOG_LEVEL=verbose
      - GENERIC_TIMEZONE="Africa/Johannesburg"
    expose:
      - 5678
    volumes:
      - /mnt/n8n:/home/node/.n8n
    networks:
      - proxy
      - services
    depends_on:
      - pgsql
      - redis

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
  services:
    external: true
````

### Expected behavior

The schedule node is supposed to run on set intervals. But it is not doing that anymore. This means that now we have to trigger workflows manually and it defeats the purpose and a lot of work.

### Operating System

Linux Ubuntu

### n8n Version

1.57.0

### Node.js Version

<20

### Database

PostgreSQL

### Execution mode

main (default)
