### ISSUE TITLE
Cannot start docker container with image later than v1.59.0

### ISSUE THREAD

**Issue by mintyfrankie** [n8n-io/n8n#11002]
### Bug Description

When start a n8n container with docker image later than v1.59.0, an error message is displayed:

```bash
Error response from daemon: unable to find user node: no matching entries in passwd file
```

### To Reproduce

With a minimum docker compose file

```yaml
services:
  n8n:
    image: n8nio/n8n:1.59.0
    # image: n8nio/n8n:1.55.3
    container_name: n8n
    restart: unless-stopped
    expose:
      - 5678
```

Error message is displayed when doing `docker compose up -d --build`

### Expected behavior

Docker container should be up correctly.

### Operating System

Debian 12

### n8n Version

1.60.0

### Node.js Version

N/A

### Database

PostgreSQL

### Execution mode

main (default)
