### ISSUE TITLE
Queue mode is broken since version 1.60.0

### ISSUE THREAD

**Issue by fruworg** [n8n-io/n8n#11247]
### Bug Description

Since version 1.60.0 (tested also on 1.62.5) we get an error on the worker when using the queue mod.

```
n8n-worker | Error: Worker exiting due to an error.
n8n-worker | TypeError: Cannot read properties of undefined (reading 'subscribe')
n8n-worker | User settings loaded from: /root/.n8n/config
n8n-worker | Last session crashed
```

### To Reproduce

`master.yaml`
```
services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      --requirepass <REDACTED-PWD>
      --bind 0.0.0.0
    ports:
      - 0.0.0.0:6379:6379
  postgres:
    container_name: n8n-psql
    hostname: n8n-psql
    image: postgres:16
    user: "0:0"
    ports:
      - '5432:5432'
    restart: always
    command:
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/var/lib/postgresql/psql.pem"
      - "-c"
      - "ssl_key_file=/var/lib/postgresql/psql.key"
    environment:
      - POSTGRES_USER=_it_n8n
      - POSTGRES_PASSWORD=<REDACTED-PSQL-PWD>
      - POSTGRES_DB=_it_n8n_db
      - POSTGRES_NON_ROOT_USER=_it_n8n
      - POSTGRES_NON_ROOT_PASSWORD=<REDACTED-PSQL-PWD>
    volumes:
      - /mnt/BLOCK-STORAGE/n8n/psql:/var/lib/postgresql/data
      - ./ssl/<REDACTED-MASTER-FQDN>.crt:/var/lib/postgresql/psql.pem
      - ./ssl/<REDACTED-MASTER-FQDN>.key:/var/lib/postgresql/psql.key
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U _it_n8n -d _it_n8n_db']
      interval: 5s
      timeout: 5s
      retries: 10
  n8n-master:
    container_name: n8n-master
    image: n8nio/n8n
    user: "0:0"
    volumes:
      - /opt/n8n:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Europe/Moscow
      - WEBHOOK_URL=https://<REDACTED-MASTER-FQDN>
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=_it_n8n_db
      - DB_POSTGRESDB_HOST=n8n-psql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=_it_n8n
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_PASSWORD=<REDACTED-PSQL-PWD>
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PASSWORD=<REDACTED-PWD>
      - N8N_ENCRYPTION_KEY=<REDACTED-KEY>
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=1000000
      - NODE_FUNCTION_ALLOW_EXTERNAL=jsonwebtoken
    ports:
      - '127.0.0.1:5678:5678'
    restart: always
    depends_on:
      redis:
        condition: service_healthy

```

`worker.yaml`
```
services:
  n8n-worker:
    container_name: n8n-worker
    image: n8nio/n8n:1.62.5
    user: "0:0"
    volumes:
      - /mnt/BLOCK-STORAGE/n8n:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Europe/Moscow
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=_it_n8n_db
      - DB_POSTGRESDB_HOST=<REDACTED-MASTER-FQDN>
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=_it_n8n
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_PASSWORD=<REDACTED-PSQL-PWD>
      - DB_POSTGRESDB_SSL_ENABLED=true
      - QUEUE_BULL_REDIS_HOST=<REDACTED-MASTER-FQDN>
      - QUEUE_BULL_REDIS_PASSWORD=<REDACTED-PWD>
      - N8N_ENCRYPTION_KEY=<REDACTED-KEY>
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=1000000
      - NODE_FUNCTION_ALLOW_EXTERNAL=jsonwebtoken
    command: worker --concurrency=100
    restart: always
```

`docker compose up -d`
`docker compose logs`

### Expected behavior

Something like this:

```
n8n-worker  | n8n worker is now ready
n8n-worker  |  * Version: 1.62.5
n8n-worker  |  * Concurrency: 100
```

### Operating System

Ubuntu 24.04.1 LTS

### n8n Version

1.62.5

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @fruworg,

We have created an internal ticket to look into this which we will be tracking as "GHC-314"

**Comment by netroy** [comment]
> /root/

unrelated to this particular issue, but we highly recommend not running n8n as the root user, or using `/root/.n8n` as the n8n storage folder. Not only is this a security issue, we also don't test this configuration, and cannot guarantee that n8n will continue to work as expected as root. 🙏🏽

**Comment by Joffcom** [comment]
@fruworg I am currently running queue mode on 1.63.2 without any issues, Can you try updating and seeing if you have the same issue.

**Comment by netroy** [comment]
This is most likely coming from [this line](https://github.com/n8n-io/n8n/blob/master/packages/cli/src/scaling/pubsub/subscriber.service.ts#L61). This doesn't seem to be breaking for any of our instances, or in any of our tests.

I'm guessing there is something in how n8n is setup in your case, that's causing this.
Would it be possible for you to try to reproduce this on a setup without `user: "0:0"` for both n8n containers 🙏🏽

**Comment by netroy** [comment]
Also, can you please try adding service dependencies on redis and postgres to both n8n containers? 

```yaml
depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
```
