### ISSUE TITLE
Wrong start / end time for recurring calendar events from different timezone after daylight savings change

### ISSUE THREAD

**Issue by gabrielwhite** [n8n-io/n8n#11264]
### Bug Description

I have a recurring meeting that is based on CET/Ceuta that started in July 2024. I live in America/Santiago. 

When we changed to daylight savings time here in Chile (a month ago), the event kept being read as being at the old time (i.e. the event was at 9AM America/Santiago before the daylight savings change, and should be at 10AM America/Santiago after the change, but it still shows as 9AM in n8n). 

I don't see this problem in any of my calendar apps.

```
name: n8n
services:
    n8n:
        container_name: n8n
        ports:
            - 5678:5678
        volumes:
            - ./data:/home/node/.n8n
        environment:
            - N8N_EDITOR_BASE_URL=https://n8n
            - GENERIC_TIMEZONE=America/Santiago
            - TZ=America/Santiago
        image: docker.n8n.io/n8nio/n8n
        restart: unless-stopped
```

Please let me know if I can provide any more debug info.

### To Reproduce

1. Create event with participants in different timezones in north and southern hemisphere / locations that do not share same daylight savings schedule or direction
2. Wait for daylight savings time to change
3. See event is showing wrong time in recipients timezone

### Expected behavior

Event time should reflect updated local time.

### Operating System

Debian Bookworm

### n8n Version

1.62.5

### Node.js Version

Whatever ships with the docker image

### Database

SQLite (default)

### Execution mode

main (default)
