### ISSUE TITLE
Nextcloud Integration Pulling HTML instead of files through WebDAV

### ISSUE THREAD

**Issue by pypeaday** [n8n-io/n8n#11391]
### Bug Description

I have n8n setup fresh with docker compose, I self-host nextcloud at https://mydomain.nextcloud.com. I started playing with n8n to just download a file from nextcloud but when I test the node the file it pulls isn't my target file, it's like it curled down the html

Here's the docker compose file for reproducing

```yaml
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
```

### To Reproduce

1. use docker compose to spin up n8n fresh
2. add nextcloud credentials for a user on your instance (I'm happy to collaborate on my instance)
3. add nextcloud node to download a file
4. successfully test the node but the downloaded file is the html of a webpage, not the target file

### Expected behavior

I would expect that if I wanted to download a `Readme.md` file at the root of my users folder that I would be able to open the downloaded file in a text editor and see the markdown content

### Operating System

Fedora 40

### n8n Version

1.64.2

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)
