### ISSUE TITLE
getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by JustinGuese** [n8n-io/n8n#11479]
### Bug Description

I know you already told other people with that problem that it is their fault, but it actually is a n8n problem... I am trying to run the app in a Kubernetes cluster, all other apps can resolve, and `cat /etc/resolv.conf` shows nameserver 1.1.1.1

The app logs suggest it can not resolve to your telemetry server, and to nothing at all...

### To Reproduce

1. Start n8n as docker container, or in kubernetes
2. every request shows getaddrinfo ENOTFOUND

### Expected behavior

Adresses can be resolved

### Operating System

Ubuntu 22.10

### n8n Version

1.64.3

### Node.js Version

v20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @JustinGuese,

We have created an internal ticket to look into this which we will be tracking as "GHC-367"

**Comment by Joffcom** [comment]
Hey @JustinGuese 

This error suggests an issue with DNS which our application does not control which is why we often tell users that this is not an issue with n8n itself.

Have you checked that the container has been configured to use the correct network and dns server?

**Comment by Vinaum8** [comment]
+1

**Comment by Vinaum8** [comment]
I use IPv6 with EKS, if you need more tests I can help.
I use Bitnami's Redis Helm Chart in other applications and they are working correctly.

**Comment by Joffcom** [comment]
We are moving this to closed as there doesn't appear to be any extra context and `ENOTFOUND` is known to not be an n8n application error.

If anyone has detailed steps on how to reproduce this in a way that is the fault of the application and not an environment issue let me know.

**Comment by JustinGuese** [comment]
indeed the busy box container seems to have a problem to resolve dns entries. 
it seems to only use the first name server entry in /etc/resolv.conf, which is the coredns of k3s in my case.

I could solve the issue with setting an explicit name server in the deployment.yaml (kubernetes)

other pods work, so I guess its a busy box issue?

```
      dnsPolicy: None # ignores coredns
      dnsConfig:
        nameservers:
          - 1.1.1.1 # sets cloud flare dns
```

**Comment by Joffcom** [comment]
There does appear to be a few cases online where users have found the same issue with busybox going back to 2020.

**Comment by vrzlev** [comment]
BusyBox networking may be broken when using a single IP address family.

* https://bugs.busybox.net/show_bug.cgi?id=5042
* https://bugs.busybox.net/show_bug.cgi?id=10611

**Comment by vrzlev** [comment]
Managed to restore connectivity by forcing the pod's DNS policy to Default. 

I'm using Flux's HelmRelease, so in my case it is:

```yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: add
                path: /spec/template/spec/dnsPolicy
                value: Default
```

This makes the pod inherit the host's DNS settings, so it can no longer resolve in-cluster addresses, but I'm okay with that.

**Comment by neoromantique** [comment]
HI! I've had same issue with k3s now, and since my database is within the cluster I couldn't change dnsPolicy to Default, as that'd break the app.


I have side-stepped it with a hacky solution:
```yaml
kubectl create configmap -n n8n-server custom-resolv --from-literal=resolv.conf="
nameserver 10.43.0.10 # cluster DNS
nameserver 8.8.8.8 # Google DNS as fallback
search n8n-server.svc.cluster.local svc.cluster.local cluster.local
options ndots:5 timeout:2 attempts:3
```

```yaml
  template:
    spec:
      volumes:
<...>
        - name: custom-resolv
          configMap:
            name: custom-resolv
      containers:
        - name: n8n
          volumeMounts:
<...>
            - name: custom-resolv
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
```
