### ISSUE TITLE
Setting DATA_FOLDER does not work as expected

### ISSUE THREAD

**Issue by haf** [n8n-io/n8n#1168]
**Describe the bug**
When changing DATA_FOLDER, data is not saved in that folder.

**To Reproduce**
1. set it
2. save a workflow
3. restart the stateful set / otherwise the process
4. try to load the previous workflow

**Expected behavior**
For DATA_FOLDER to have an effect: https://community.n8n.io/t/what-be-a-good-deployment-story/3004/4?u=haf

**Environment (please complete the following information):**
 - OS: host is macOS but using the official docker container
 - n8n: latest docker container
 - Node.js Version [e.g. 10.16.0]: see above

**Additional context**

Removing DATA_FOLDER and mouting `/root/.n8n` to a persistent volume claim works.

---

Appendix A: statefulset.yaml:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
---
# Docs: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n

  annotations:
    sidecar.jaegertracing.io/inject: jaeger

spec:
  serviceName: n8n

  replicas: 1

  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
        prometheus.io/port: "9114"

    spec:
      terminationGracePeriodSeconds: 10

      serviceAccountName: n8n

      containers:
      - name: n8n
        image: n8nio/n8n

        env:
        # TODO: n8n/config -> /etc/n8n/config
        # TODO: n8n/database.sqlite -> /etc/n8n/database.sqlite
        # Right now they are both in this folder:

        - name: DATA_FOLDER
          value: /var/lib/n8n
        - name: GENERIC_TIMEZONE
          value: Europe/Berlin
        - name: N8N_PORT
          value: "5678"

        ports:
        - name: http
          containerPort: 5678

        # The kubelet uses readiness probes to know when a container is ready to start accepting traffic.
        readinessProbe:
          httpGet:
            path: /healthz
            port: http

        # Many applications running for long periods of time eventually transition to broken states, and cannot recover except by being restarted. Kubernetes provides liveness probes to detect and remedy such situations.
        livenessProbe:
          httpGet:
            path: /healthz
            port: http

        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 20Mi

        volumeMounts:
        # DATA_FOLDER does not seem to work
        # Goes ONLY by user; here 'root'
        - name: n8n-state
          mountPath: /var/lib/n8n

  volumeClaimTemplates:
  - metadata:
      name: n8n-state
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 10Gi

```
