### ISSUE TITLE
When installing the update it is reporting this error regarding my community nodes.

### ISSUE THREAD

**Issue by wilsonfe** [n8n-io/n8n#12071]
### Bug Description

ERROR

nodes package n8n-nodes-browserless is already loaded.

 Please delete this second copy at path /home/node/.n8n/nodes/node_modules/n8n-nodes-browserless

Error: nodes package n8n-nodes-browserless is already loaded.

 Please delete this second copy at path /home/node/.n8n/nodes/node_modules/n8n-nodes-browserless

    at LoadNodesAndCredentials.runDirectoryLoader (/usr/local/lib/node_modules/n8n/dist/load-nodes-and-credentials.js:204:19)

    at LoadNodesAndCredentials.loadPackage (/usr/local/lib/node_modules/n8n/dist/load-nodes-and-credentials.js:159:27)

    at CommunityPackagesService.installOrUpdateNpmPackage (/usr/local/lib/node_modules/n8n/dist/services/community-packages.service.js:309:44)

    at processTicksAndRejections (node:internal/process/task_queues:95:5)

    at community-package-install (/usr/local/lib/node_modules/n8n/dist/scaling/pubsub/pubsub-handler.js:46:85)

    at EventService.<anonymous> (/usr/local/lib/node_modules/n8n/dist/scaling/pubsub/pubsub-handler.js:135:17)

nodes package @splainez/n8n-nodes-phonenumber-parser is already loaded.

 Please delete this second copy at path /home/node/.n8n/nodes/node_modules/@splainez/n8n-nodes-phonenumber-parser

Error: nodes package @splainez/n8n-nodes-phonenumber-parser is already loaded.

 Please delete this second copy at path /home/node/.n8n/nodes/node_modules/@splainez/n8n-nodes-phonenumber-parser

    at LoadNodesAndCredentials.runDirectoryLoader (/usr/local/lib/node_modules/n8n/dist/load-nodes-and-credentials.js:204:19)

    at LoadNodesAndCredentials.loadPackage (/usr/local/lib/node_modules/n8n/dist/load-nodes-and-credentials.js:159:27)

    at CommunityPackagesService.installOrUpdateNpmPackage (/usr/local/lib/node_modules/n8n/dist/services/community-packages.service.js:309:44)

    at processTicksAndRejections (node:internal/process/task_queues:95:5)

    at community-package-install (/usr/local/lib/node_modules/n8n/dist/scaling/pubsub/pubsub-handler.js:46:85)

    at EventService.<anonymous> (/usr/local/lib/node_modules/n8n/dist/scaling/pubsub/pubsub-handler.js:135:17)

nodes package n8n-nodes-chatwoot is already loaded.

 Please delete this second copy at path /home/node/.n8n/nodes/node_modules/n8n-nodes-chatwoot

Error: nodes package n8n-nodes-chatwoot is already loaded.

 Please delete this second copy at path /home/node/.n8n/nodes/node_modules/n8n-nodes-chatwoot

    at LoadNodesAndCredentials.runDirectoryLoader (/usr/local/lib/node_modules/n8n/dist/load-nodes-and-credentials.js:204:19)

    at LoadNodesAndCredentials.loadPackage (/usr/local/lib/node_modules/n8n/dist/load-nodes-and-credentials.js:159:27)

    at CommunityPackagesService.installOrUpdateNpmPackage (/usr/local/lib/node_modules/n8n/dist/services/community-packages.service.js:309:44)

    at processTicksAndRejections (node:internal/process/task_queues:95:5)

    at community-package-install (/usr/local/lib/node_modules/n8n/dist/scaling/pubsub/pubsub-handler.js:46:85)

    at EventService.<anonymous> (/usr/local/lib/node_modules/n8n/dist/scaling/pubsub/pubsub-handler.js:135:17)

nodes package n8n-nodes-data-validation is already loaded.

 Please delete this second copy at path /home/node/.n8n/nodes/node_modules/n8n-nodes-data-validation

Error: nodes package n8n-nodes-data-validation is already loaded.

 Please delete this second copy at path /home/node/.n8n/nodes/node_modules/n8n-nodes-data-validation

    at LoadNodesAndCredentials.runDirectoryLoader (/usr/local/lib/node_modules/n8n/dist/load-nodes-and-credentials.js:204:19)

    at LoadNodesAndCredentials.loadPackage (/usr/local/lib/node_modules/n8n/dist/load-nodes-and-credentials.js:159:27)

    at CommunityPackagesService.installOrUpdateNpmPackage (/usr/local/lib/node_modules/n8n/dist/services/community-packages.service.js:309:44)

    at processTicksAndRejections (node:internal/process/task_queues:95:5)

    at community-package-install (/usr/local/lib/node_modules/n8n/dist/scaling/pubsub/pubsub-handler.js:46:85)

    at EventService.<anonymous> (/usr/local/lib/node_modules/n8n/dist/scaling/pubsub/pubsub-handler.js:135:17)

nodes package n8n-nodes-document-generator is already loaded.

 Please delete this second copy at path /home/node/.n8n/nodes/node_modules/n8n-nodes-document-generator

Error: nodes package n8n-nodes-document-generator is already loaded.

 Please delete this second copy at path /home/node/.n8n/nodes/node_modules/n8n-nodes-document-generator

    at LoadNodesAndCredentials.runDirectoryLoader (/usr/local/lib/node_modules/n8n/dist/load-nodes-and-credentials.js:204:19)

    at LoadNodesAndCredentials.loadPackage (/usr/local/lib/node_modules/n8n/dist/load-nodes-and-credentials.js:159:27)

    at CommunityPackagesService.installOrUpdateNpmPackage (/usr/local/lib/node_modules/n8n/dist/services/community-packages.service.js:309:44)

    at processTicksAndRejections (node:internal/process/task_queues:95:5)

    at community-package-install (/usr/local/lib/node_modules/n8n/dist/scaling/pubsub/pubsub-handler.js:46:85)

    at EventService.<anonymous> (/usr/local/lib/node_modules/n8n/dist/scaling/pubsub/pubsub-handler.js:135:17)

nodes package n8n-nodes-edit-image-plus is already loaded.

 Please delete this second copy at path /home/node/.n8n/nodes/node_modules/n8n-nodes-edit-image-plus

Error: nodes package n8n-nodes-edit-image-plus is already loaded.

### To Reproduce

I just updated my stack via portainer.

### Expected behavior

Use existing community nodes

### Operating System

Debian 12

### n8n Version

1.70.1 (Self Hosted)

### Node.js Version

1.2 (Latest version: 1.3)

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @wilsonfe,

We have created an internal ticket to look into this which we will be tracking as "GHC-569"

**Comment by alarm109** [comment]
I also encounter this error with my custom node. When I check `/mnt/mydisk/n8nData/.n8n/.n8n/nodes/node_modules` folder, the specified package does not exist, so I can't delete it.

```
2024-12-10T11:30:27.594Z | error | Error loading package "n8n-nodes-firebase-admin-auth-get-uid-from-email" :The specified package could not be loaded
Cause: nodes package n8n-nodes-firebase-admin-auth-get-uid-from-email is already loaded.
 Please delete this second copy at path /mnt/mydisk/n8nData/.n8n/.n8n/nodes/node_modules/n8n-nodes-firebase-admin-auth-get-uid-from-email
ResponseError: Error loading package "n8n-nodes-firebase-admin-auth-get-uid-from-email" :The specified package could not be loaded
Cause: nodes package n8n-nodes-firebase-admin-auth-get-uid-from-email is already loaded.
 Please delete this second copy at path /mnt/mydisk/n8nData/.n8n/.n8n/nodes/node_modules/n8n-nodes-firebase-admin-auth-get-uid-from-email
    at CommunityPackagesController.installPackage (/opt/render/project/src/packages/cli/src/controllers/community-packages.controller.ts:111:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handler (/opt/render/project/src/packages/cli/src/decorators/controller.registry.ts:105:12)
    at /opt/render/project/src/packages/cli/src/response-helper.ts:154:17
 {"file":"LoggerProxy.js","function":"exports.error"}
```

**Comment by ivov** [comment]
Have either of you followed the instruction in the error message?

**Comment by balmacefa** [comment]
I have a similar issue, after install update and uninstall a custom module.

![image](https://github.com/user-attachments/assets/575a5186-77e8-4da2-806f-f6a8664c21f2)

I remove the packages.json and stuffs on the folder ~/.n8n/nodes

but for some reason this is still calling my custom node, after removing from UI and manually.

**Comment by simonefrancia** [comment]
Any update on this? 
I have a similar error

**Comment by kitobelix** [comment]
I'm having a similar error, cannot upgrade, install or remove any community nodes, but they do upgrade or remove if I use CLI or CLI node to do so.

My version: 1.80.3 (Docker, latest)
Tried setting up as user "node" (uid 1000) and "root" (UID 0) but no success.
Used Env 
UI shows: (redacted the node name)
```
Problem updating package
Error removing package "n8n-nodes-{node-name}":Failed to save installed package
```

Logs: (redacted the node name)
```
25/2/2025 15:30:35Error removing package "n8n-nodes-{node-name}":Failed to save installed package
25/2/2025 15:30:35ResponseError: Error removing package "n8n-nodes-{node-name}":Failed to save installed package
25/2/2025 15:30:35    at CommunityPackagesController.updatePackage (/usr/local/lib/node_modules/n8n/dist/controllers/community-packages.controller.js:227:19)
25/2/2025 15:30:35    at processTicksAndRejections (node:internal/process/task_queues:95:5)
25/2/2025 15:30:35    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
25/2/2025 15:30:35    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26
25/2/2025 15:30:35
25/2/2025 15:30:35Failed to save installed package
25/2/2025 15:30:35Error: Failed to save installed package
25/2/2025 15:30:35    at CommunityPackagesService.installOrUpdatePackage (/usr/local/lib/node_modules/n8n/dist/services/community-packages.service.js:292:23)
25/2/2025 15:30:35    at processTicksAndRejections (node:internal/process/task_queues:95:5)
25/2/2025 15:30:35    at CommunityPackagesService.updatePackage (/usr/local/lib/node_modules/n8n/dist/services/community-packages.service.js:235:16)
25/2/2025 15:30:35    at CommunityPackagesController.updatePackage (/usr/local/lib/node_modules/n8n/dist/controllers/community-packages.controller.js:183:41)
25/2/2025 15:30:35    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
25/2/2025 15:30:35    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26
25/2/2025 15:30:35
25/2/2025 15:30:35async function setType(requestOptions) {
25/2/2025 15:30:35    const operation = this.getNodeParameter('operation');
25/2/2025 15:30:35    const me...<omitted>...
25/2/2025 15:30:35} could not be cloned.
```

Docker compose equivalent: (redacted for privacy)
```
  n8n-main-service:
    image: docker.n8n.io/n8nio/n8n:latest
    environment:
      NODE_ENV: production
      GENERIC_TIMEZONE: (redacted for privacy)
      DB_POSTGRESDB_HOST: postgres-db
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_PORT: '5432'
      DB_POSTGRESDB_USER: (redacted for privacy)
      DB_POSTGRESDB_PASSWORD: (redacted for privacy)
      DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: 'true'
      WEBHOOK_URL: https://(redacted for privacy)
      N8N_HOST: n8n.(redacted for privacy)
      N8N_PORT: '5678'
      N8N_PROTOCOL: http
      N8N_EMAIL_MODE: smtp
      N8N_SMTP_HOST: mail.(redacted for privacy)
      N8N_SMTP_PORT: '465'
      N8N_SMTP_USER: n8n@(redacted for privacy)
      N8N_SMTP_PASS: (redacted for privacy)
      N8N_SMTP_SENDER: N8N (redacted for privacy) <n8n@(redacted for privacy)>
      N8N_METRICS: 'true'
      EXECUTIONS_MODE: regular
      EXECUTIONS_DATA_PRUNE: 'true'
      EXECUTIONS_DATA_MAX_AGE: '160'
      EXECUTIONS_DATA_PRUNE_MAX_COUNT: '200'
      EXECUTIONS_DATA_SAVE_ON_ERROR: all
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: all
      EXECUTIONS_DATA_SAVE_ON_PROGRESS: 'true'
      EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: 'true'
      N8N_ENCRYPTION_KEY: (redacted for privacy)
      QUEUE_BULL_REDIS_HOST: n8n-redis-(redacted for privacy)
      QUEUE_BULL_REDIS_PORT: '6379'
      QUEUE_HEALTH_CHECK_ACTIVE: 'true'
      N8N_DEFAULT_BINARY_DATA_MODE: filesystem
      DB_TYPE: postgresdb
      NODE_FUNCTION_ALLOW_BUILTIN: '*'
      EXECUTIONS_TIMEOUT: '1800'
      N8N_COMMUNITY_PACKAGES_ENABLED: 'true'
      NODE_FUNCTION_ALLOW_EXTERNAL: '*'
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      N8N_REINSTALL_MISSING_PACKAGES: 'true'
      N8N_RUNNERS_ENABLED: 'true'
```

I'm not sure when it started to happen. I've been using n8n from version 1.5 aprox.

What i've tried so far:
- Deleting docker image, volumes, mounts.
- Rolling back a few versions.
- Switching from user "node" to "root".

Workaround:
- Using npm cli to manage community nodes. So far so good but, you know, it might not be optimal.

Thanks a lot for all the effort!
