### ISSUE TITLE
JWT auth not working

### ISSUE THREAD

**Issue by Vad1mo** [n8n-io/n8n#1211]
I am trying to use [pomerium](https://pomerium.io) with c8n according to the documentation of c8n it should work. 

Pomerium does the validation and attaches the header with jwt token `X-Pomerium-Jwt-Assertion` 

```yaml
security:
  jwtAuth:
    active: true                # If JWT auth should be activated for editor and REST-API - default: false
    jwtHeader: 'X-Pomerium-Jwt-Assertion'  # The request header containing a signed JWT - default: ''
    jwksUri: 'https://authenticate.app.8gears.com/.well-known/pomerium/jwks.json'   # The URI to fetch JWK Set for JWT authentication - default: ''
```

However, I get the error message:

```json
{
"code": 403,
"message": "The JWKS endpoint did not contain any signing keys"
}
```

https://authenticate.app.8gears.com/.well-known/pomerium/jwks.json
```json
{
"keys": [
{
"use": "sig",
"kty": "EC",
"kid": "7a1239efdb8ea0117b49a94bd8e1fee6918bbf82abe1362ab562afc5dea0fe7b",
"crv": "P-256",
"alg": "ES256",
"x": "DvJoz97mxby9hBL-K4jIPYqbCic7aWE9mxc9LtiPg_s",
"y": "WMPCS3olLJ8T3v0ZqzyywD03HCfLksetTebxrX2O4LQ"
}
]
}
```

Maybe @tovbinm has an idea, as he did the initial PR on that!
