### ISSUE TITLE
Deprecated config default values in helmchart

### ISSUE THREAD

**Issue by ftqualifio** [n8n-io/n8n#12205]
### Bug Description

The following default in the helm chart prevents n8n from starting as it is not in the schema anymore.  The config shouldn't have any default value and be optional.

```
config:
  executions:
    # prune executions by default
    pruneData: "true"
    # Per default, we store 1 year of history
    pruneDataMaxAge: 3760
```

### To Reproduce

Deploy the helm chart

### Expected behavior

Being able to deploy without the default config.

### Operating System

Debian 12

### n8n Version

1.67.1

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

main (default)
