### ISSUE TITLE
Node Parameter Changes Not Persisting in Workflow Editor

### ISSUE THREAD

**Issue by sylvesterdas** [n8n-io/n8n#12253]
## Description
When attempting to edit node parameters in the workflow editor, changes are not persisting. The parameters reset to their original values either:
- Immediately after saving (Ctrl+S)
- When moving focus to another field within the same node
This makes it impossible to modify any node parameters, effectively preventing workflow editing.

## Environment
- n8n Version: 1.71.3
- Deployment: Docker (self-hosted)
- Node.js Version: 20.18.0
- Database: SQLite
- Browser: Chrome 131.0.0.0
- OS: Linux x86_64
- License: Enterprise (Production)

## Actual Behavior
- Parameter changes immediately revert to their original values
- Unable to modify any node parameters
- Changes do not persist even after attempting to save

## Additional Context
- Issue persists after container restart
- Problem has been occurring for several days
- All other n8n functionality appears to work normally
- System storage has available space
- Using memory mode for binary data storage
- Pruning is enabled with standard settings

## Debug Information
```yaml
Core:
- executionMode: regular
- concurrency: -1
- consumerId: 3b2adc1a-a7dc-4a6d-9952-358548215b59

Storage:
- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

Pruning:
- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

Security:
- secureCookie: false
```

## Logs
No specific error messages observed in logs (System intentionally configured not to log)

### To Reproduce

1. Open any workflow in the n8n editor
2. Select any node to edit
3. Attempt to modify a parameter field
4. Either:
   - Press Ctrl+S to save, or
   - Click another field within the same node
5. Observe that the modified parameter reverts to its original value

### Expected behavior

- Parameter changes should persist when saving
- Changes should remain when moving between fields within the node
- Modified values should be saved successfully to the workflow

### Operating System

Linux x86_64

### n8n Version

1.71.3

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)
