### ISSUE TITLE
Queued processes regardless of n8n instance configuration

### ISSUE THREAD

**Issue by brunolnetto** [n8n-io/n8n#12519]
### Bug Description

Hi there,

I self-hosted an n8n instance with Traefik reverse proxing it. However, I am not able to run scheduled workflows, they keep stuck on "Queued" status. Do you have some advices to give me about this?

### To Reproduce

I did not add workers neither additional webhooks. The production workflows keeps on status `Queued` indefinitely. 

```
services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      ## Database configuration
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres

      # Authentication for the editor UI
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=username
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_PROTOCOL=https
      - N8N_PORT=5679
      - WEBHOOK_URL=https://n8n.example.com

      # Execution settings
      - EXECUTIONS_MODE=queue

        ## Redis settings
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336

      ## Community Nodes
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes

      ## Timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

      labels:
        - "traefik.enable=true"
        - "traefik.http.services.n8n_ivplast.loadbalancer.server.port=5679"
        - "traefik.http.routers.n8n_ivplast.rule=Host(`n8n.example.com`)"
        - "traefik.http.routers.n8n_ivplast.entrypoints=websecure"

    networks:
      - "traefik_network"
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  n8n-data:

networks:
  traefik_network:
    external: true
    name: "traefik_network"
```

### Expected behavior

I expected to run the workflows sucessfully.

### Operating System

Ubuntu Linux 22.04

### n8n Version

1.72.1

### Node.js Version

18.16.0

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @brunolnetto,

We have created an internal ticket to look into this which we will be tracking as "N8N-8066"

**Comment by netroy** [comment]
I think the issue is that you have `EXECUTIONS_MODE=queue` set, but there is no redis or n8n-workers in your compose stack. Production executions need workers to actually execute.

You need to either add those extra containers, or you should remove the `EXECUTIONS_MODE` env variable.

**Comment by brunolnetto** [comment]
Ok, great! Thanks for answering so fast. I do have a redis instance sharing the same network as n8n instance. However, as you noticed, I do not have workers.  I added below new work service and added environment variable `- N8N_ENCRYPTION_KEY=MRy6z5Z6kc8RS3egRwrfzCVlU` to editor service. I removed the stack and redeployed. However, it outputs following error still. I am crying. T-T

```
User settings loaded from: /home/node/.n8n/config
(node:7) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (audit)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
message: Mismatching encryption keys. The encryption key in the settings file /home/node/.n8n/config does not match the N8N_ENCRYPTION_KEY env var. Please make sure both keys match. More information: https://docs.n8n.io/hosting/environment-variables/configuration-methods/#encryption-key
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7) Warning: Error
module: @oclif/core@4.0.7
task: findCommand (base-command)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
```

```
...
  n8n_dekcomercial_worker:
    image: n8nio/n8n:latest ## Versão do N8N
    command: worker --concurrency=10

    networks:
      - traefik_network ## Nome da rede interna

    environment:
      ## Dados do postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=moscanobanco

      ## Url do N8N
      - WEBHOOK_URL=https://n8n.example.com
      - N8N_PROTOCOL=https

      - N8N_ENCRYPTION_KEY=MRy6z5Z6kc8RS3egRwrfzCVlU
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

      ## Modo do Node
      - NODE_ENV=production

      ## Modo de execução (deletar caso deseje em modo regular)
      - EXECUTIONS_MODE=queue

      ## Community Nodes
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes

      ## Dados do Redis
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336

      ## Timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
```
