### ISSUE TITLE
Worker failed to find data for execution

### ISSUE THREAD

**Issue by brunolnetto** [n8n-io/n8n#12535]
### Bug Description

Production workflows execution with a worker started outputing the error below. Although I have tried to check for Redis and postgres connection based on correct credentials,  the instance still complains. 

```
Problem with execution 116: Worker failed to find data for execution 116 (job 147). Aborting.
Worker failed to find data for execution 116 (job 147) (execution 116)
Error: Worker failed to find data for execution 116 (job 147)
    at Queue.onFailed (/usr/local/lib/node_modules/n8n/node_modules/bull/lib/job.js:516:18)
    at Queue.emit (node:events:519:28)
    at Object.module.exports.emitSafe (/usr/local/lib/node_modules/n8n/node_modules/bull/lib/utils.js:50:20)
    at EventEmitter.messageHandler (/usr/local/lib/node_modules/n8n/node_modules/bull/lib/queue.js:476:15)
    at EventEmitter.emit (node:events:519:28)
    at DataHandler.handleSubscriberReply (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/DataHandler.js:80:32)
    at DataHandler.returnReply (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/DataHandler.js:47:18)
    at JavascriptRedisParser.returnReply (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/DataHandler.js:21:22)
    at JavascriptRedisParser.execute (/usr/local/lib/node_modules/n8n/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/DataHandler.js:25:20)
```

### To Reproduce

```
services:
  n8n_editor:
    image: n8nio/n8n:latest
    environment:
      ## Database configuration
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres

      # Authentication for the editor UI
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=n8n_username
      - N8N_BASIC_AUTH_PASSWORD=n8n_password
      - N8N_PROTOCOL=https
      - N8N_PORT=5679
      - WEBHOOK_URL=https://n8n.example.com


      ## Dados do Redis
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336

      ## Modo do Node
      - NODE_ENV=production

      # Execution settings
      - EXECUTIONS_MODE=queue
      #- N8N_CONCURRENCY_PRODUCTION_LIMIT=20

      ## Community Nodes
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes

      ## Timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

      labels:
        - "traefik.enable=true"
        - "traefik.http.services.n8n_dekcomercial.loadbalancer.server.port=5679"
        - "traefik.http.routers.n8n_dekcomercial.rule=Host(`n8n.example.com`)"
        - "traefik.http.routers.n8n_dekcomercial.entrypoints=websecure"

    networks:
      - "traefik_network"
    volumes:
      - n8n-data:/home/node/.n8n

  n8n_worker:
    image: n8nio/n8n:latest ## Versão do N8N
    command: worker --concurrency=10

    networks:
      - traefik_network ## Nome da rede interna

    environment:
      ## Dados do postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_queue
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres

      ## Url do N8N
      - WEBHOOK_URL=https://n8n.example.com
      - N8N_PROTOCOL=https

      - N8N_ENCRYPTION_KEY=fcrHIa/MRy6z5Z6kc8RS3egRwrfzCVlU
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

      ## Modo do Node
      - NODE_ENV=production

      ## Modo de execução (deletar caso deseje em modo regular)
      - EXECUTIONS_MODE=queue

      ## Community Nodes
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes

      ## Dados do Redis
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336

      ## Timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  n8n-data:

networks:
  traefik_network:
    external: true
    name: "traefik_network"
```

### Expected behavior

I expected to run without this error.

### Operating System

Ubuntu 22.04

### n8n Version

1.74.0

### Node.js Version

18.16.0

### Database

PostgreSQL

### Execution mode

queue

**Comment by brunolnetto** [comment]
In which table can I find the execution queue events? The credentials are correct. I have no control over deletion as well. This leaves me without options to investigate.

**Comment by ivov** [comment]
Executions are in `execution_entity` and `execution_data`. As a user you can e.g. delete executions via the UI and API, and regularly delete them via pruning settings. Queue mode keys are all under the `bull` prefix in Redis, but based on your error Redis is working correctly.

If you boot up only a main without no workers and start a production execution, does the enqueued production execution show up in `execution_entity`. An enqueued execution will have status as `new`, no started at timestamp, finished as `false`, etc. If you later start a worker, does the worker fail to find that execution?

**Comment by brunolnetto** [comment]
I ran without the worker, and commented environment variable `- EXECUTIONS_MODE=queue`. It runs correctly now. I feel sad for not being able to use the queue.

**Comment by ivov** [comment]
Can you please try what I suggest above? Keep queue mode enabled - the purpose of not starting the worker at first is to give you an opportunity to check the database to see if the execution has been enqueued.

> If you boot up only a main without no workers and start a production execution, does the enqueued production execution show up in execution_entity? An enqueued execution will have status as new, no started at timestamp, finished as false, etc. If you later start a worker, does the worker fail to find that execution?

**Comment by brunolnetto** [comment]
Ok! 

Query `select * from execution_entity order by 1 desc limit 1;`:

```
 id  | finished |  mode   | retryOf | retrySuccessId | startedAt |         stoppedAt         | waitTill | status |    workflowId    | deletedAt |         createdAt
-----+----------+---------+---------+----------------+-----------+---------------------------+----------+--------+------------------+-----------+----------------------------
 123 | f        | webhook |         |                |           | 2025-01-09 14:15:21.82+00 |          | error  | YGiiBCeZysJAWY2M |           | 2025-01-09 14:15:21.741+00
```

Query `select "executionId", "data" from execution_data order by 1 desc limit 1;`:

```
executionId |                                                                                                                                                                                                                                                                                           data
-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
         123 | [{"resultData":"1"},{"error":"2","runData":"3"},{"message":"4","stack":"5"},{},"Worker failed to find data for execution 123 (job 153)","Error: Worker failed to find data for execution 123 (job 153)\n    at Queue.onFailed (/usr/local/lib/node_modules/n8n/node_modules/bull/lib/job.js:516:18)\n    at Queue.emit (node:events:519:28)\n    at Object.module.exports.emitSafe (/usr/local/lib/node_modules/n8n/node_modules/bull/lib/utils.js:50:20)\n    at EventEmitter.messageHandler (/usr/local/lib/node_modules/n8n/node_modules/bull/lib/queue.js:476:15)\n    at EventEmitter.emit (node:events:519:28)\n    at DataHandler.handleSubscriberReply (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/DataHandler.js:80:32)\n    at DataHandler.returnReply (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/DataHandler.js:47:18)\n    at JavascriptRedisParser.returnReply (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/DataHandler.js:21:22)\n    at JavascriptRedisParser.execute (/usr/local/lib/node_modules/n8n/node_modules/redis-parser/lib/parser.js:544:14)\n    at Socket.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/DataHandler.js:25:20)"]
````

**Comment by ivov** [comment]
To be clear, execution 123 is the result of following the steps I suggested? Or is it what led you to open the issue in the first place? Looks like the latter.

My suggestion above is to debug this step by step:

1. Start a main in queue mode and `N8N_LOG_LEVEL=debug`. Do not start a worker.
2. Create a workflow with a webhook, activate the workflow, call the webhook. Main's logs should show `Enqueued execution 456 (job 789)` with no surrounding errors
3. Still without starting a worker, inspect the execution in Postgres: `SELECT "status", "startedAt", "stoppedAt" FROM "execution_entity" WHERE "id" = '456';`. This execution should have status `new` and have `startedAt` and `stoppedAt` as `null`
4. If step 3 checks out, then start a worker with `N8N_LOG_LEVEL=debug` and observe its logs. Does the worker fail to find the execution now? If so, does the execution still exist in the DB?

**Comment by brunolnetto** [comment]
For some unknown reason, the test instance started succeeding. This makes me think, the other instances are corrupted in some other way. I have no idea how to turn them into new without transfering the original data to a brand new instance.

**Comment by brunolnetto** [comment]
I will do this rn. I hope, this does not overwhelm your day. I am not much versed into all docker features. Therefore, I wonder if it is possible to directly plug to image "ghcr.io/n8n-io/n8n:1.74.1-debug-empty-node-execution-stack" instead of requiring Dockerfile context to pre-build a custom-image.

Side note: I saw @netroy approving the PR, he helped me on another deployment issue as well.

**Comment by ivov** [comment]
For both main and worker, you should be able to replace like this:

```diff
- image: n8nio/n8n:latest
+ image: ghcr.io/n8n-io/n8n:1.74.1-debug-empty-node-execution-stack
```

**Comment by brunolnetto** [comment]
I was unable to use the image as you provided, the stack deployment on my docker swarm did not automatically created the containers. However, I was able to reproduce the intermitent workflow with variable `N8N_SENTRY_DSN` as you provided with error whose message is `Cannot read properties of undefined (reading 'node')`, please check sentry logs with source IP `147.79.82.36`. 

```
 status  |         startedAt          |         stoppedAt
---------+----------------------------+----------------------------
 success | 2025-01-10 12:05:50.98+00  | 2025-01-10 12:05:51.04+00
 success | 2025-01-10 12:07:38.892+00 | 2025-01-10 12:07:38.904+00
 error   |                            | 2025-01-10 12:07:40.89+00
 success | 2025-01-10 12:07:45.464+00 | 2025-01-10 12:07:45.473+00
 error   |                            | 2025-01-10 12:07:47.381+00
 success | 2025-01-10 12:07:48.622+00 | 2025-01-10 12:07:48.631+00
 error   |                            | 2025-01-10 12:07:50.292+00
 success | 2025-01-10 12:07:52.563+00 | 2025-01-10 12:07:52.58+00
 error   |                            | 2025-01-10 12:07:54.205+00
```

**Comment by ivov** [comment]
Thank you for this, so the jobs are being dequeued correctly. As you're now on the debug image with Sentry enabled, let's wait to see what shows up on our end. I'll post back once we have something.

**Comment by brunolnetto** [comment]
If there is anything else I can do to help, feel free to promptly say! THANKS! 🥳

**Comment by brunolnetto** [comment]
I added the logs to other stacks and redeployed. There may be several fresh logs available.

**Comment by ivov** [comment]
Tested today by creating a docker compose based on your provided settings (and filling in the missing Postgres and Redis images) and then calling a production webhook multiple times, and all the executions are running successfully.

Are there any relevant differences between your settings and ours? Does this docker compose work on your end? 

<details>
  <summary>Settings</summary>

`docker-compose.yml`

```yml
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_storage:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n_editor:
    ports:
      - 5678:5678
    image: n8nio/n8n:1.71.2
    links:
      - postgres
      - redis
    environment:
      ## Database configuration
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}

      # Authentication for the editor UI
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=n8n_username
      - N8N_BASIC_AUTH_PASSWORD=n8n_password
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n.example.com

      ## Dados do Redis
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336

      ## Modo do Node
      - NODE_ENV=production

      # Execution settings
      - EXECUTIONS_MODE=queue
      #- N8N_CONCURRENCY_PRODUCTION_LIMIT=20

      ## Community Nodes
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes

      ## Timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    volumes:
      - n8n-data:/home/node/.n8n

  n8n_worker:
    links:
      - postgres
      - redis
    image: n8nio/n8n:1.71.2 ## Versão do N8N
    command: worker --concurrency=10

    environment:
      ## Dados do postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}

      ## Url do N8N
      - WEBHOOK_URL=https://n8n.example.com
      - N8N_PROTOCOL=https

      - N8N_ENCRYPTION_KEY=fcrHIa/MRy6z5Z6kc8RS3egRwrfzCVlU
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

      ## Modo do Node
      - NODE_ENV=production

      ## Modo de execução (deletar caso deseje em modo regular)
      - EXECUTIONS_MODE=queue

      ## Community Nodes
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_NODE_PATH=/home/node/.n8n/nodes

      ## Dados do Redis
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=2
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336

      ## Timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  n8n-data:
  db_storage:
  redis_storage:
```

`init-data.sh`

```sh
#!/bin/bash
set -e;


if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
		GRANT CREATE ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi
```

`.env`

```env
POSTGRES_USER=changeUser
POSTGRES_PASSWORD=changePassword
POSTGRES_DB=n8n

POSTGRES_NON_ROOT_USER=changeUser
POSTGRES_NON_ROOT_PASSWORD=changePassword
```
<details>

**Comment by brunolnetto** [comment]
I performed following steps to reproduce the provided assets:

1. Created a new folder with command `mkdir n8n-test && cd n8n-test`;
2. Touched and copied content to 3 files `docker-compose.yaml`, `init-data.sh` and `.env`;
3. Activated environment variable with command run `source .env`;
4. Ran commands `docker-compose up -d`;

I was able to reproduce the (de-)queue locally. Remotely, I had to adapt to integrate to swarm. I guess, there is some confusion performed by traefik based on environment variable `WEBHOOK_URL=https://n8n.example.com:5680` . To allow using a single DNS, here `n8n.example.com`, I create multiple port entrypoints on my traefik compose. The complete traefik compose is below. 

<details>
<summary>
docker-compose.yml
</summary>

```
services:
  traefik:
    image: traefik:v3.2.3
    hostname: '{{.Node.Hostname}}'
    command:
      - "--api.dashboard=true"
      - "--certificatesresolvers.letsencryptresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/etc/traefik/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencryptresolver.acme.email=example@mail.com"
      - "--providers.swarm.exposedByDefault=false"
      - "--providers.swarm.network=traefik_network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.asDefault=true"
      - "--entrypoints.n8n_teste.http.tls.certresolver=letsencryptresolver"
      - "--entrypoints.n8n_dekcomercial.address=:5680"
       - "--log.level=DEBUG"
      - "--log.format=common"
      - "--log.filePath=/var/log/traefik/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access-log"

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.example.com`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"
        - "traefik.http.routers.dashboard.middlewares=myauth"
        - "traefik.http.middlewares.myauth.basicauth.users=test:$$apr1$$LAdrB6op$$.gz/GEIrpRzHSlrWbmjnB/"
 
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 5680
        published: 5680
        mode: host

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "vol_certificates:/etc/traefik/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  vol_certificates:
    external: true
    name: volume_certificates

networks:
  traefik_network:
    attachable: true
    name: traefik_network
```
</details>

On main service, I perform following modifications for variable `WEBHOOK_URL` and add labels on property `deploy`.

<details>
<summary>
Compose diff for docker swarm deployment
</summary>

``` 
    ...
    environment:
      - N8N_LOG_LEVEL=debug
      - N8N_SENTRY_DSN=https://a1a1abc6b8b44ec94289a2785e82af02@o1420875.ingest.us.sentry.io/4504016528408576

      - WEBHOOK_URL="https://n8n.example.com:5680"
    ...
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.n8n_teste.loadbalancer.server.port=5680"
        - "traefik.http.routers.n8n_teste.rule=Host(`n8n.example.com`)"
        - "traefik.http.routers.n8n_teste.entrypoints=websecure,n8n_teste"
``` 
</details>

The reproduction steps I performed are 

1. Create network with command run `docker network create --driver overlay "traefik_network" --`;
2. Hire a Linux VPS;
3. Bind Traefik domain `traefik.example.com` on your favourite DNS provider to a VPS (If you want to use dashboard. Provided `username:password` above are `test:test`);
4. Copy-paste content from `traefik` on file `traefik.yml`;
5. Deploy traefik with command run `docker stack deploy -c traefik.yml traefik`;
6. Create N8N domain `n8n.example.com` on your favourite DNS provider;
7. Create file `n8n.yml` with the credentials you provide and perform the modifications for variable `WEBHOOK_URL` as well as labels on property `deploy`;8. Deploy using command run `docker stack delpoy -c n8n.yml`
9. (Try to) access urls `https://traefik.example.com` and `https://n8n.example.com` remotely.
