### ISSUE TITLE
Paypal trigger node is not being triggered

### ISSUE THREAD

**Issue by Quack6765** [n8n-io/n8n#12561]
### Bug Description

When using the Paypal trigger node with any event type, it will never trigger.

Using the webhook tester from Paypal, I can see from my reverse proxy logs that the query is indeed sent to N8N but yet the node never triggers:

Caddy log that shows the query being accepted and forwarded to my n8n instance:
```
{"level":"info","ts":1736539170.5965438,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"REDACTED","remote_port":"49632","client_ip":"REDACTED","proto":"HTTP/1.1","method":"POST","host":"n8n.example.com","uri":"/webhook-test/b3c3d317-REDACTED/webhook","headers":{"Paypal-Auth-Algo":["SHA256withRSA"],"X-B3-Spanid":["REDACTED"],"Paypal-Transmission-Id":["REDACTED"],"Paypal-Auth-Version":["v2"],"Cal_poolstack":["REDACTED"],"Paypal-Transmission-Time":["2025-01-10T19:59:13Z"],"User-Agent":["PayPal/AUHD-214.0-58711782"],"Correlation-Id":["REDACTED"],"Paypal-Transmission-Sig":["REDACTED"],"Client_pid":["REDACTED"],"Content-Length":["1263"],"Accept":["*/*"],"Paypal-Cert-Url":["REDACTED"],"Content-Type":["application/json"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"http/1.1","server_name":"n8n.example.com"}},"bytes_read":1263,"user_id":"","duration":0.369580354,"size":35,"status":200,"resp_headers":{"Server":["Caddy"],"Alt-Svc":["h3=\":443\"; ma=2592000"],"Content-Length":["35"],"Etag":["W/\"23-NtpDzMsUcnBm9d5fplxPmZoZiD4\""],"Vary":["Accept-Encoding"],"Date":["Fri, 10 Jan 2025 19:59:30 GMT"],"Content-Type":["application/json; charset=utf-8"]}}
```

### To Reproduce

1. Create a new workflow
2. Select the Paypal trigger node with valid credentials and select `*` as the event type
3. Set the trigger node in test mode.
4. Go to the [Paypal Dev webhook simulator](https://developer.paypal.com/dashboard/webhooksSimulator)
5. Paste your webhook URL and select any event type.
6. Watch the node never being triggered

Can also reproduce by enabling the workflow and using the production webhook URL. Once an event is fired from Paypal webhook simulator, you'll can check the workflow executions to confirm that it's not being triggered.

### Expected behavior

Trigger the node

### Operating System

Docker

### n8n Version

1.73.1

### Node.js Version

Default with docker image

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Quack6765,

We have created an internal ticket to look into this which we will be tracking as "N8N-8083"

**Comment by tomi** [comment]
Hi @Quack6765 . I just tested and was able to receive an event using the PayPal Trigger node. Since you are using a reverse proxy, have you configured the required [environment variables](https://docs.n8n.io/hosting/configuration/configuration-examples/webhook-url/)?

**Comment by Quack6765** [comment]
Hey @tomi,

That's weird. Yes the `WEBHOOK_URL` var env is set and all other webhooks trigger works fine except for Paypal.Here are some more info and logs maybe that could help:

N8N logs shows the POST being received from paypal: 
`2025-01-13T15:34:30.334Z | debug | Received webhook "POST" for path "3f5b1ac4-8ebb-4722-bb74-30f2a4255e0b/webhook" {"file":"live-webhooks.js","function":"executeWebhook"}`

Screenshot showing the webhook URL in question:
![CleanShot 2025-01-13 at 10 36 15](https://github.com/user-attachments/assets/d93df63f-0463-4987-9274-975bb42e7d48)

Screenshot showing the latest execution (empty) of the workflow:
![CleanShot 2025-01-13 at 10 35 20](https://github.com/user-attachments/assets/655b8b99-dbb8-414a-aeea-2de5b52d1b8e)

My reverse proxy is Caddyv2 with the following Caddyfile:
```
https://n8n.example.com {
        reverse_proxy http://192.168.2.253:5678
}
```

My docker-compose settings:
```
  n8n:
    container_name: n8n
    network_mode: bridge
    environment:
      - TZ=America/New_York
      - HOST_OS=Unraid
      - HOST_HOSTNAME=Example
      - HOST_CONTAINERNAME=n8n
      - GENERIC_TIMEZONE=America/Toronto
      - 'WEBHOOK_URL=https://n8n.example.com/'
      - N8N_LOG_LEVEL=debug
    ports:
      - '5678:5678/tcp'
    volumes:
      - '/mnt/user/appdata/n8n:/home/node/.n8n:rw'
    restart: unless-stopped
    image: n8nio/n8n
```
