### ISSUE TITLE
Setting UID and GID does not work

### ISSUE THREAD

**Issue by Bluestart83** [n8n-io/n8n#12582]
### Bug Description

If user have to run docker image, and UID is not 1000  (is default in docker NODE IMAGE you rely on), it does not work.

I have to build a custom IMAGE of n8n with this inside:

the build file n8n_build.docker:
```
FROM n8nio/n8n:latest

# Switch to root to install dependencies
USER root

# Custom UID GID
# Override the default UID/GID with your custom values
ARG USER_UID=1000
ARG USER_GID=1000

# Re-create the node group and user with custom UID/GID
RUN deluser node || true && \
    delgroup node || true && \
    addgroup -g $USER_GID node && \
    adduser -u $USER_UID -G node -s /bin/sh -D node && \
    chown -R node:node /home/node /usr/local/lib/node_modules .n8n

# Switch back to non-root user
ENV SHELL /bin/sh
USER node
ENTRYPOINT ["tini", "--", "/docker-entrypoint.sh"]
```

and this in the docker-compose.yaml file:
```yml
services:
  n8n:
    #image: n8nio/n8n:latest
    build:
        context: .
        dockerfile: n8n_build.docker # This is your custom Dockerfile
        args:
          USER_UID: 1002  # Replace with the desired UID
          USER_GID: 1002  # Replace with the desired GID 
    user: "1002:1002"  # UID:GID of the n8n_user different than 1000
```

### To Reproduce

Use different user than 1000 id and try to use docker image.
Any n8n version.

### Expected behavior

N8N should work with different user than the default one 1000.

### Operating System

Debian 12 (bookworm)

### n8n Version

*

### Node.js Version

*

### Database

PostgreSQL

### Execution mode

main (default)
