### ISSUE TITLE
WebUI cannot load: crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by WangEdward** [n8n-io/n8n#12624]
### Bug Description

Similar issue to #12051

Error message `Uncaught TypeError: crypto.randomUUID is not a function at index-D0W-rAl_.js:292077:27`

Corresponding source code:

https://github.com/n8n-io/n8n/blob/da8aafc0e3a1b5d862f0723d0d53d2c38bcaebc3/packages/editor-ui/src/components/CodeNodeEditor/CodeNodeEditor.vue#L40

Issue in 1.74, no error when reverted to 1.73.0.

### n8n Version

1.74.1

### Environment
MacOS, chrome, HTTP, `N8N_SECURE_COOKIE=false`

**Comment by Joffcom** [comment]
Hey @WangEdward,

We have created an internal ticket to look into this which we will be tracking as "N8N-8117"

**Comment by netroy** [comment]
what browser are you using ?

**Comment by WangEdward** [comment]
> what browser are you using ?

I tried with Chrome and Safari, both have this error.

**Comment by netroy** [comment]
and, do you have `N8N_SECURE_COOKIE` set to `false`?

**Comment by xoniq** [comment]
> and, do you have `N8N_SECURE_COOKIE` set to `false`?

I have the same issue as OP, changed the env variable as described by you but doesnt make a difference.
This is what I use in my `docker-compose.yml`:

```yaml
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - TZ=Europe/Amsterdam
      - N8N_SECURE_COOKIE=false
    restart: unless-stopped

volumes:
  n8n_data:
```
