### ISSUE TITLE
NODES_INCLUDE not working!

### ISSUE THREAD

**Issue by zakariamehbi** [n8n-io/n8n#12713]
### Bug Description

Hello, I have a problem with NODES_INCLUDE not working, every time I set my list and start my docker container, I get an error when trying to create a trigger.

```
Error cannot read properties of undefined (reading 'match')
```

```
- NODES_INCLUDE=["n8n-nodes-base.gmailTrigger","n8n-nodes-base.gmail","n8n-nodes-base.googleSheets","n8n-nodes-base.httpRequest","n8n-nodes-base.if","n8n-nodes-base.code","n8n-nodes-base.set","n8n-nodes-base.merge","n8n-nodes-base.emailSend","n8n-nodes-base.dateTime","n8n-nodes-base.webhook","n8n-nodes-base.manualTrigger","n8n-nodes-base.scheduleTrigger"]
```

### To Reproduce

1. Create a docker-compose.yml
2. Add this config: 
```
version: '3.1'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - NODES_INCLUDE=["n8n-nodes-base.gmailTrigger","n8n-nodes-base.gmail","n8n-nodes-base.googleSheets","n8n-nodes-base.httpRequest","n8n-nodes-base.if","n8n-nodes-base.code","n8n-nodes-base.set","n8n-nodes-base.merge","n8n-nodes-base.emailSend","n8n-nodes-base.dateTime","n8n-nodes-base.webhook","n8n-nodes-base.manualTrigger","n8n-nodes-base.scheduleTrigger"]
    volumes:
      - ~/.n8n:/home/node/.n8n
```
3. start the container
4. try creating a workflow, any trigger will output an error

### Expected behavior

- The list of items included in NODES_INCLUDE shows up, and all the rest disappear.
- Clicking a trigger doesn't show an error

### Operating System

Mac OS

### n8n Version

1.74.3

### Node.js Version

23.6.0

### Database

SQLite (default)

### Execution mode

main (default)
