### ISSUE TITLE
n8n Security is not working in RHEL 7

### ISSUE THREAD

**Issue by plrdeops** [n8n-io/n8n#128]
export N8N_BASIC_AUTH_ACTIVE=true
export N8N_BASIC_AUTH_USER=<USER>
export N8N_BASIC_AUTH_PASSWORD=<PASSWORD>

The above mentioned n8n security is not working. Please let me know if any other solution

**Comment by janober** [comment]
hm, can currently not think of any reason why it should not work in RHEL.

Do the environment variables all have values defined and that for sure in the environment n8n gets started in? Then it should work. The code which uses them is very simple and should be independent of the operating system as it gets the values via `process.env` which should work everywhere

Anyway, the other alternative would be to simply start n8n with docker or set up a reverse proxy with Nginx yourself.

**Comment by janober** [comment]
Did you find the problem?

**Comment by PLR143** [comment]
No Dude.... Please help me

**Comment by ky0shiro** [comment]
Hello, I'm facing similar issue.
I'm deploying n8n on kubernetes, with env variables:
```
          env:
            - name: N8N_PORT
              value: "5678"
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-auth
                  key: username
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-auth
                  key: password
```
These variables are correctly set up in n8n container:
```
kubectl -n default exec -it n8n-5cfc769d6b-z8jjs /bin/sh         
/data # echo $N8N_BASIC_AUTH_USER
user
/data # echo $N8N_BASIC_AUTH_PASSWORD
password
```
When I'm trying to access webui login window pops up, but it rejects my credentials.
