### ISSUE TITLE
SMTP TLS not working

### ISSUE THREAD

**Issue by rimvydascivilis** [n8n-io/n8n#12809]
### Bug Description

Docker logs
```
Failed to send email
Please contact your administrator: 38C29C78037F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

ResponseError: Please contact your administrator: 38C29C78037F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

    at PasswordResetController.forgotPassword (/usr/local/lib/node_modules/n8n/dist/controllers/password-reset.controller.js:89:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26

38C29C78037F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
```

### To Reproduce

```yml
services:
  n8n:
    image: ghcr.io/n8n-io/n8n:1.76.1
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost/
      - N8N_SMTP_HOST=smtp-relay.gmail.com
      - N8N_SMTP_PORT=587
      - N8N_SMTP_SENDER=n8n@example.com
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
```

Create account
Reset password (http://localhost/forgot-password)

### Expected behavior

Sends emails without errors

### Operating System

Rocky linux 9

### n8n Version

ghcr.io/n8n-io/n8n:1.76.1

### Node.js Version

20

### Database

SQLite (default)

### Execution mode

main (default)
