### ISSUE TITLE
Version 1.76.1 AI Agent Issues

### ISSUE THREAD

**Issue by xhzkp** [n8n-io/n8n#12961]
### Bug Description

I performed a fresh installation of the latest version of n8n (v1.76.1) on a Windows 10 operating system. I created a new workflow, but the execution process is extremely slow, and there are no indicators showing the execution of OpenAI. The following video demonstrates this issue.
(I installed an older version of n8n on another Windows 10 computer, executed the same workflow, and the execution speed was very fast. Additionally, the OpenAI model execution indicators were displayed.)

Executing a simple OpenAI conversation now takes over 10 seconds, which is ten times slower than before. Additionally, most of the old workflows I imported no longer work properly. It's really frustrating.

https://github.com/user-attachments/assets/2fb0a417-e1f3-4d80-87e6-8353f6f39f97

code:
```
{
  "nodes": [
    {
      "parameters": {
        "options": {}
      },
      "type": "@n8n/n8n-nodes-langchain.chatTrigger",
      "typeVersion": 1.1,
      "position": [
        -180,
        -120
      ],
      "id": "e2a7f4af-7f3f-43f2-b0e9-df620dbead0e",
      "name": "When chat message received",
      "webhookId": "43c980cd-5c31-4288-91c7-23c537387b2f"
    },
    {
      "parameters": {
        "options": {}
      },
      "type": "@n8n/n8n-nodes-langchain.agent",
      "typeVersion": 1.7,
      "position": [
        160,
        -140
      ],
      "id": "26a7f0e5-384a-417d-b28a-96b8dedae96b",
      "name": "AI Agent"
    },
    {
      "parameters": {
        "model": {
          "__rl": true,
          "mode": "list",
          "value": "gpt-4o-mini"
        },
        "options": {}
      },
      "type": "@n8n/n8n-nodes-langchain.lmChatOpenAi",
      "typeVersion": 1.2,
      "position": [
        80,
        40
      ],
      "id": "039acf30-88ce-4a5e-8142-990174fac50a",
      "name": "OpenAI Chat Model",
      "credentials": {
        "openAiApi": {
          "id": "TyEokTl05Lo4KMtT",
          "name": "OpenAi account"
        }
      }
    },
    {
      "parameters": {},
      "type": "@n8n/n8n-nodes-langchain.memoryBufferWindow",
      "typeVersion": 1.3,
      "position": [
        260,
        80
      ],
      "id": "3684aa69-0d02-4ac2-a8fb-70be02befafa",
      "name": "Window Buffer Memory"
    }
  ],
  "connections": {
    "When chat message received": {
      "main": [
        [
          {
            "node": "AI Agent",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "OpenAI Chat Model": {
      "ai_languageModel": [
        [
          {
            "node": "AI Agent",
            "type": "ai_languageModel",
            "index": 0
          }
        ]
      ]
    },
    "Window Buffer Memory": {
      "ai_memory": [
        [
          {
            "node": "AI Agent",
            "type": "ai_memory",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {},
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "39a8e5ec27a409e407646288ee0cfe2b90961dcade892b2e4e9bf07933f589ce"
  }
}
```

### To Reproduce

1.copy code
2. run

### Expected behavior

Normal execution speed

### Operating System

windows 10

### n8n Version

1.76.1

### Node.js Version

18.16.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @xhzkp,

We have created an internal ticket to look into this which we will be tracking as "GHC-681"

**Comment by Joffcom** [comment]
Hey @xhzkp 

I have not seen any other reports of this so I suspect it could be environmental.

On the second machine you put the older version on what happens if you try the newest version on that?

**Comment by xhzkp** [comment]
> Hey [@xhzkp](https://github.com/xhzkp)
> 
> I have not seen any other reports of this so I suspect it could be environmental.
> 
> On the second machine you put the older version on what happens if you try the newest version on that?

@Joffcom 
I don't dare to try again. My previous experience tells me that the chances of encountering issues are too high. The issues mentioned above occurred after a fresh installation of n8n, which is a bit hard to understand.

**Comment by xhzkp** [comment]
@Joffcom 
Before the AI agent responds slowly, the following error message appears in the console window:

```
Error in handler N8nLlmTracing, handleLLMStart: TypeError: fetch failed
2025-01-31T03:56:40.216Z [Rudder] error: Response error code: ETIMEDOUT
Error in handler N8nLlmTracing, handleLLMEnd: TypeError: fetch failed
2025-01-31T03:57:01.464Z [Rudder] error: Response error code: ETIMEDOUT
2025-01-31T03:57:22.994Z [Rudder] error: Response error code: ETIMEDOUT
Error in handler N8nLlmTracing, handleLLMStart: TypeError: fetch failed
2025-01-31T03:57:44.808Z [Rudder] error: Error: ETIMEDOUT
connect ETIMEDOUT 2606:4700:20::681a:cbb:443
connect ETIMEDOUT 2606:4700:20::681a:cbb:443
connect ETIMEDOUT 2606:4700:20::681a:cbb:443
connect ETIMEDOUT 2606:4700:20::681a:cbb:443
connect ETIMEDOUT 2606:4700:20::681a:cbb:443
connect ETIMEDOUT 2606:4700:20::681a:cbb:443
Error in handler N8nLlmTracing, handleLLMEnd: TypeError: fetch failed
```

**Comment by xhzkp** [comment]
@Joffcom 

I tried upgrading to the latest preview version 1.77.0, but the issue still persists. Below is the upgrade log.
```
C:\Users\Administrator>npm install -g n8n@next
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated lodash.get@4.4.2: This package is deprecated. Use the optional chaining (?.) operator instead.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @aws-sdk/protocol-http@3.374.0: This package has moved to @smithy/protocol-http
npm warn deprecated @aws-sdk/signature-v4@3.374.0: This package has moved to @smithy/signature-v4
npm warn deprecated @aws-sdk/node-http-handler@3.374.0: This package has moved to @smithy/node-http-handler
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated google-p12-pem@4.0.1: Package is no longer maintained
npm warn deprecated dommatrix@1.0.3: dommatrix is no longer maintained. Please use @thednp/dommatrix.
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated infisical-node@1.3.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated @azure/core-http@3.0.5: This package is no longer supported. Please refer to https://github.com/Azure/azure-sdk-for-js/blob/490ce4dfc5b98ba290dee3b33a6d0876c5f138e2/sdk/core/README.md

changed 2162 packages in 10m

198 packages are looking for funding
  run `npm fund` for details

C:\Users\Administrator>n8n
User settings loaded from: C:\Users\Administrator\.n8n\config
(node:4652) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Initializing n8n process
n8n ready on 0.0.0.0, port 5678
Version: 1.77.0

Editor is now accessible via:
http://localhost:5678/

Press "o" to open in Browser.
2025-01-31T04:53:30.423Z [Rudder] error: Response error code: ETIMEDOUT
2025-01-31T04:53:51.802Z [Rudder] error: Response error code: ETIMEDOUT
2025-01-31T04:54:13.276Z [Rudder] error: Response error code: ETIMEDOUT
Error in handler N8nLlmTracing, handleLLMStart: TypeError: fetch failed
Error in handler N8nLlmTracing, handleLLMEnd: TypeError: fetch failed
Error fetching feature flags Error [PostHogFetchNetworkError]: Network error while fetching PostHog
    at new PostHogFetchNetworkError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\n8n\node_modules\posthog-core\src\index.ts:41:5)
    at PostHog.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\n8n\node_modules\posthog-core\src\index.ts:546:17)
    at step (C:\Users\Administrator\AppData\Roaming\npm\node_modules\n8n\node_modules\node_modules\tslib\tslib.es6.js:102:23)
    at Object.throw (C:\Users\Administrator\AppData\Roaming\npm\node_modules\n8n\node_modules\node_modules\tslib\tslib.es6.js:83:53)
    at rejected (C:\Users\Administrator\AppData\Roaming\npm\node_modules\n8n\node_modules\node_modules\tslib\tslib.es6.js:74:65) {
  error: DOMException [TimeoutError]: The operation was aborted due to timeout
      at node:internal/deps/undici/undici:13502:13,
  [cause]: DOMException [TimeoutError]: The operation was aborted due to timeout
      at node:internal/deps/undici/undici:13502:13
}

```

**Comment by xhzkp** [comment]
@Joffcom 
To verify the issue, I performed a fresh installation of Windows 10 LTSC 2021, then installed Node.js v22.13.1, followed by n8n v1.76.1. Unfortunately, the issue mentioned earlier still persists. 

On my other computer, which was upgraded from an earlier version of n8n to the new version, the issue does not occur.

How can this issue be resolved?

**Comment by xhzkp** [comment]
@Joffcom 
I have four computers running Windows 10, all of which have n8n installed via npm. After upgrading to version 1.76.1, all workflows have completely broken, and I am unable to restore them to a working state.  
I need help and would appreciate any suggestions or assistance in advance.

**Comment by Rar9** [comment]
same issue with Ubuntu 24.04 lts with Docker 1.76.1 Chat breaks

**Comment by xhzkp** [comment]
@Joffcom 

> With the workflows that are not working what is happening with them?
The situation is the same as before. Whenever the AI agent is used, the chat replies become extremely slow, with a delay of several seconds before receiving a response. However, there is no issue with version 1.66 of n8n. 

I request the developers to install n8n via npm on a Windows system and review this issue, as Windows is the true productivity system.

**Comment by xhzkp** [comment]
@Joffcom 
I downgraded the version to 1.66.0 using the command `npm install -g n8n@1.66.0`, and the AI agent response speed became very fast, returning to normal. Below is the video demonstration. 

https://github.com/user-attachments/assets/f986386d-4006-4452-9d9f-49b529eb1a05

I forgot to mention one point: I modified the base URL of the OpenAI model, as shown in the image below. In versions after 1.66, the base URL parameter is included in the credentials, and I believe this might be the cause of the issue.

![Image](https://github.com/user-attachments/assets/06d10a2e-2a5f-401a-b7e8-4d84adfa0e02)

**Comment by xhzkp** [comment]
@Joffcom 

The issue I encountered is the same as the one in the link below. It occurred after upgrading the version and has the same error message.

```
Error in handler N8nLlmTracing, handleLLMStart: TypeError: fetch failed
Error in handler N8nLlmTracing, handleLLMEnd: TypeError: fetch failed
```
https://github.com/n8n-io/n8n/issues/12670

**Comment by tarkh** [comment]
Same story here. Installed via Docker, AI Agent spinning red arrows for 20-23 seconds, then I receive answer from OpenRouter. After this only AI Agent block marked green, while OpenRouter bubble still dark grey (and there was no spinning red arrows at all).

![Image](https://github.com/user-attachments/assets/94247a46-fb11-4d70-adc9-7c9e4126f342)

Machine is on Rocky Linux 9.5 (5.14.0-503.19.1.el9_5.x86_64)
Docker version 28.0.0, build f9ced58
n8n Version 1.80.3

From CLI I do also see this lines while running docker and starting chat prompt for AI Agent:
```
n8n         | Error in handler N8nLlmTracing, handleLLMStart: TypeError: fetch failed
n8n         | Error in handler N8nLlmTracing, handleLLMEnd: TypeError: fetch failed
```
Full log from CLI:
```
[www@Main-Server n8n-kit]$ docker compose --profile cpu up
[+] Running 5/5
 ✔ Network n8n-kit_demo          Created                                                                                                                                                                                                0.2s 
 ✔ Container n8n-kit-postgres-1  Created                                                                                                                                                                                                0.0s 
 ✔ Container qdrant              Created                                                                                                                                                                                                0.0s 
 ✔ Container n8n-import          Created                                                                                                                                                                                                0.0s 
 ✔ Container n8n                 Created                                                                                                                                                                                                0.0s 
Attaching to n8n, n8n-import, postgres-1, qdrant
postgres-1  | 
postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-1  | 
postgres-1  | 2025-02-27 06:21:58.672 UTC [1] LOG:  starting PostgreSQL 16.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
postgres-1  | 2025-02-27 06:21:58.673 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres-1  | 2025-02-27 06:21:58.673 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres-1  | 2025-02-27 06:21:58.676 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres-1  | 2025-02-27 06:21:58.680 UTC [29] LOG:  database system was shut down at 2025-02-27 06:21:06 UTC
postgres-1  | 2025-02-27 06:21:58.685 UTC [1] LOG:  database system is ready to accept connections
qdrant      |            _                 _    
qdrant      |   __ _  __| |_ __ __ _ _ __ | |_  
qdrant      |  / _` |/ _` | '__/ _` | '_ \| __| 
qdrant      | | (_| | (_| | | | (_| | | | | |_  
qdrant      |  \__, |\__,_|_|  \__,_|_| |_|\__| 
qdrant      |     |_|                           
qdrant      | 
qdrant      | Version: 1.13.4, build: 7abc6843
qdrant      | Access web UI at http://localhost:6333/dashboard
qdrant      | 
qdrant      | 2025-02-27T06:21:58.698233Z  WARN qdrant: Bootstrap URI is the same as this peer URI. Consider this peer as a first in a new deployment.    
qdrant      | 2025-02-27T06:21:58.698444Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json    
qdrant      | 2025-02-27T06:21:58.712160Z  INFO storage::content_manager::toc: Loading collection: documents    
qdrant      | 2025-02-27T06:21:58.811428Z  INFO collection::shards::local_shard: Recovering collection documents: 0/1 (0%)    
qdrant      | 2025-02-27T06:21:58.829088Z  INFO collection::shards::local_shard: Recovered collection documents: 1/1 (100%)    
qdrant      | 2025-02-27T06:21:58.830812Z  INFO qdrant: Distributed mode disabled    
qdrant      | 2025-02-27T06:21:58.831232Z  INFO qdrant: Telemetry reporting enabled, id: 9b6a36fb-a7a8-4b33-ab74-909699d57ed6    
qdrant      | 2025-02-27T06:21:58.831654Z  INFO qdrant: Inference service is not configured.    
qdrant      | 2025-02-27T06:21:58.833501Z  INFO qdrant::actix: TLS disabled for REST API    
qdrant      | 2025-02-27T06:21:58.833764Z  INFO qdrant::actix: Qdrant HTTP listening on 6333    
qdrant      | 2025-02-27T06:21:58.833843Z  INFO actix_server::builder: Starting 7 workers
qdrant      | 2025-02-27T06:21:58.834033Z  INFO actix_server::server: Actix runtime found; starting in Actix runtime
qdrant      | 2025-02-27T06:21:58.837556Z  INFO qdrant::tonic: Qdrant gRPC listening on 6334    
qdrant      | 2025-02-27T06:21:58.837569Z  INFO qdrant::tonic: TLS disabled for gRPC API    
n8n-import  | Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
n8n-import  | n8n-import  | There is a deprecation related to your environment variables. Please take the recommended actions to update your configuration:
n8n-import  |  - N8N_RUNNERS_ENABLED -> Running n8n without task runners is deprecated. Task runners will be turned on by default in a future version. Please set `N8N_RUNNERS_ENABLED=true` to enable task runners now and avoid potential issues in the future. Learn more: https://docs.n8n.io/hosting/configuration/task-runners/
n8n-import  | 
n8n-import  | Successfully imported 2 credentials.
n8n-import  | Permissions 0644 for n8n settings file /home/node/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
n8n-import  | User settings loaded from: /home/node/.n8n/config
n8n-import  | 
n8n-import  | There is a deprecation related to your environment variables. Please take the recommended actions to update your configuration:
n8n-import  |  - N8N_RUNNERS_ENABLED -> Running n8n without task runners is deprecated. Task runners will be turned on by default in a future version. Please set `N8N_RUNNERS_ENABLED=true` to enable task runners now and avoid potential issues in the future. Learn more: https://docs.n8n.io/hosting/configuration/task-runners/
n8n-import  | 
n8n-import  | Importing 1 workflows...
n8n-import  | Successfully imported 1 workflow.
n8n-import exited with code 0
n8n         | User settings loaded from: /home/node/.n8n/config
n8n         | Initializing n8n process
n8n         | n8n ready on 0.0.0.0, port 5678
n8n         | 
n8n         | There is a deprecation related to your environment variables. Please take the recommended actions to update your configuration:
n8n         |  - N8N_RUNNERS_ENABLED -> Running n8n without task runners is deprecated. Task runners will be turned on by default in a future version. Please set `N8N_RUNNERS_ENABLED=true` to enable task runners now and avoid potential issues in the future. Learn more: https://docs.n8n.io/hosting/configuration/task-runners/
n8n         | 
n8n         | Version: 1.80.3
n8n         | 
n8n         | Editor is now accessible via:
n8n         | https://n8n.tarkh.com
n8n         | Error in handler N8nLlmTracing, handleLLMStart: TypeError: fetch failed
n8n         | Error in handler N8nLlmTracing, handleLLMEnd: TypeError: fetch failed
```

docker-compose.yml
```
[www@Main-Server n8n-kit]$ cat docker-compose.yml 
volumes:
  n8n_storage:
  postgres_storage:
  #ollama_storage:
  qdrant_storage:

networks:
  demo:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['demo']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    #- OLLAMA_HOST=ollama:11434

#x-ollama: &service-ollama
#  image: ollama/ollama:latest
#  container_name: ollama
#  networks: ['demo']
#  restart: unless-stopped
#  ports:
#    - 11434:11434
#  volumes:
#    - ollama_storage:/root/.ollama
#
#x-init-ollama: &init-ollama
#  image: ollama/ollama:latest
#  networks: ['demo']
#  container_name: ollama-pull-llama
#  volumes:
#    - ollama_storage:/root/.ollama
#  entrypoint: /bin/sh
#  environment:
#    - OLLAMA_HOST=ollama:11434
#  command:
#    - "-c"
#    - "sleep 3; ollama pull llama3.2"

services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    networks: ['demo']
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-import:
    <<: *service-n8n
    hostname: n8n-import
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/backup/credentials && n8n import:workflow --separate --input=/backup/workflows"
    volumes:
      - ./n8n/backup:/backup
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    ports:
       - 192.168.30.106:3051:5678
       #- 5678:5678
    dns:
       - 1.1.1.1
    environment:
       #- N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
       - N8N_PROTOCOL=https
       - N8N_SSL_CERT=/ssl/n8n.crt
       - N8N_SSL_KEY=/ssl/n8n.key
       - N8N_HOST=0.0.0.0  # Ensure n8n listens on all interfaces
       - WEBHOOK_URL=https://n8n.***********.com
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./shared:/data/shared
      - /etc/ssl/n8n:/ssl
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 192.168.30.106:3052:6333
    volumes:
      - qdrant_storage:/qdrant/storage

  #ollama-cpu:
  #  profiles: ["cpu"]
  #  <<: *service-ollama

  #ollama-gpu:
  #  profiles: ["gpu-nvidia"]
  #  <<: *service-ollama
  #  deploy:
  #    resources:
  #      reservations:
  #        devices:
  #          - driver: nvidia
  #            count: 1
  #            capabilities: [gpu]

  #ollama-gpu-amd:
  #  profiles: ["gpu-amd"]
  #  <<: *service-ollama
  #  image: ollama/ollama:rocm
  #  devices:
  #    - "/dev/kfd"
  #    - "/dev/dri"

  #ollama-pull-llama-cpu:
  #  profiles: ["cpu"]
  #  <<: *init-ollama
  #  depends_on:
  #    - ollama-cpu

  #ollama-pull-llama-gpu:
  #  profiles: ["gpu-nvidia"]
  #  <<: *init-ollama
  #  depends_on:
  #    - ollama-gpu

  #ollama-pull-llama-gpu-amd:
  #  profiles: [gpu-amd]
  #  <<: *init-ollama
  #  image: ollama/ollama:rocm
  #  depends_on:
  #   - ollama-gpu-amd
```
