### ISSUE TITLE
cant stop the workflow test

### ISSUE THREAD

**Issue by ClaudioAldazosa** [n8n-io/n8n#13058]
If I have a second tab on localhost, in the second tab I can't stop the workflowtest

![Image](https://github.com/user-attachments/assets/98982ed5-8bf5-41dc-b537-e07b449ef8cb)

```
(Select the nodes on your canvas and use the keyboard shortcuts CMD+C/CTRL+C and CMD+V/CTRL+V to copy and paste the workflow.)
⚠️ WARNING ⚠️ If you have sensitive data in your workflow (like API keys), please remove it before sharing.
```

### core

- n8nVersion: 1.76.3
- platform: docker (self-hosted)
- nodeJsVersion: 20.18.2
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: community

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

### pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

### client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/131.0.0.0 safari/537.36 opr/116.0.0.0
- isTouchDevice: false

Generated at: 2025-02-04T23:55:22.269Z}

**Comment by Joffcom** [comment]
Hey @ClaudioAldazosa,

We have created an internal ticket to look into this which we will be tracking as "GHC-733"

**Comment by Joffcom** [comment]
Hey @ClaudioAldazosa 

What happens when you try? I take it the second tab is also where you are starting the workflow from.

**Comment by ClaudioAldazosa** [comment]
Yes, in both tabs the workflow starts, both have a webhook, in the first tab I can stop it with the button, in the second the button does not work, I must refresh the page for the test to stop

**Comment by LiuYuWei** [comment]
I also meet the problem.

<img width="938" alt="Image" src="https://github.com/user-attachments/assets/a3808517-0268-49bd-8249-a0fa8a47bd1d" />

When I click the "test workflow" button. I can get the result message in telegram, but I cannot click the stop the trigger event

<img width="1469" alt="Image" src="https://github.com/user-attachments/assets/0314a969-889a-4698-88f8-d2e357e2666a" />

What should I do to fix this problem? Thanks for help!

**Comment by Joffcom** [comment]
@LiuYuWei your issue is likely to be a configuration issue, Can you post on the forum and include the details on how you are running n8n and what reverse proxy you are using? My initial thought is you are using nginx or apache but have not enabled websockets.

@ClaudioAldazosa I can't reproduce this, Are you running the same workflow twice or 2 different ones?

**Comment by ClaudioAldazosa** [comment]
@Joffcom  There are 2 different workflows but both with a webhook to retell AI, the first is to check availability in Google Calendar, and the second is to schedule an appointment in Google Calendar

**Comment by Joffcom** [comment]
@ClaudioAldazosa any chance you could record a video of your screen showing the issue in action?

**Comment by LiuYuWei** [comment]
Hi @Joffcom 

Thanks for your response. 

This is part of my docker-compose.yml and nginx default.conf. Please check the information. If the information is not enough for verify, please let me know. Thanks!

```
x-n8n: &service-n8n
  image: n8nio/n8n:1.76.2
  networks: ['demo']
  environment:
    - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=...
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - N8N_SECURE_COOKIE=false
    - WEBHOOK_URL=...
  links:
    - postgres

services:
  n8n:
    <<: *service-n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./shared:/data/shared
      - ./custom:/home/node/.n8n/custom
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx
    networks: ['demo']
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - /etc/letsencrypt/live/.../fullchain.pem:/etc/ssl/certs/certificate.pem
      - /etc/letsencrypt/live/.../privkey.pem:/etc/ssl/certs/privatekey.pem
    depends_on:
      - n8n
      - flowise
      - open-webui
```

default.conf:
```
# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name ...;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ...;

    # N8N 服務的 SSL 配置
    ssl_certificate /etc/ssl/certs/certificate.pem;
    ssl_certificate_key /etc/ssl/certs/privatekey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # N8N 服務
    location / {
        proxy_pass http://n8n:5678;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

...
```
