### ISSUE TITLE
Last n8n update broke the service

### ISSUE THREAD

**Issue by ohmyboroda** [n8n-io/n8n#13512]
### Bug Description

The last update broke the service. Rollback version does not help, before that everything worked stably.
The database works without any problems.
![Image](https://github.com/user-attachments/assets/933a7738-ee2f-45fa-a2df-3246335ea522)

### To Reproduce

Upgrade from 1.79.4 -> 1.81.0

### Expected behavior

Successful service load after restarting the docker container.

### Operating System

Ubuntu Linux 22.04

### n8n Version

1.79.4

### Node.js Version

idk

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @ohmyboroda,

We have created an internal ticket to look into this which we will be tracking as "GHC-962"

**Comment by netroy** [comment]
According to the error in the screenshot, the credentials for the postgres connection are incorrect.
Can you check again if the credentials are valid via another postgres client?

**Comment by ohmyboroda** [comment]
> According to the error in the screenshot, the credentials for the postgres connection are incorrect. Can you check again if the credentials are valid via another postgres client?

Yes, connects successfully through another client. I checked all the credentials.
Everything worked without problems before the update, after restarting the container with the update it stopped working.

**Comment by netroy** [comment]
Just tried this compose file:

```yaml
volumes:
  n8n-data:
  postgresql-data:

services:
  n8n:
    image: n8nio/n8n:1.81.0
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - TZ=Europe/Berlin
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgresql
      - DB_POSTGRESDB_DATABASE=$POSTGRES_DB
      - DB_POSTGRESDB_USER=$SERVICE_USER_POSTGRES
      - DB_POSTGRESDB_PASSWORD=$SERVICE_PASSWORD_POSTGRES
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10

  postgresql:
    image: postgres:16-alpine
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
```

with `.env`
```
POSTGRES_DB=n8n
SERVICE_USER_POSTGRES=n8n
SERVICE_PASSWORD_POSTGRES=password
```

and had no issues.

Maybe `SERVICE_PASSWORD_POSTGRES` or `SERVICE_USER_POSTGRES` has changed in your env, and since postgres only provisions the user/DB once, the credentials probably don't match anymore.
