### ISSUE TITLE
Self-hosted N8N on Coolify in a Hetzner VPS can't connect to Google services

### ISSUE THREAD

**Issue by lamurian** [n8n-io/n8n#13619]
## Describe the problem/error/question

I have a problem when authorizing access to BigQuery and Google Gemini nodes in my workflow. I use **the same workflow** in the cloud version, and **everything works well**. However, when I tried the exact same workflow in a self-hosted N8N instance within Coolify, it refuses to authorize my access. Google BigQuery node was authenticated using OAuth2, as suggested by the documentation. Google Gemini node was authenticated using API Key from Google AI Studio, also as suggested by the documentation.

## What is the error message (if any)?

This is the associated error logs obtained from N8N canvas for BigQuery node:

```
Issues:

    There was a problem loading the parameter options from server: "403 - "\n\n \n \n Error 403 (Forbidden)!!1\n \n \n

    403. That’s an error.\n

    Your client does not have permission to get URL /bigquery/v2/projects/tonal-run-451811-t9/datasets/news_aggregator/tables/curated_news from this server. That’s all we know.\n""
```

So, I use the Coolify instance to access the N8N container terminal with:

```
docker exec -it $n8n_container sh
```

Then, I tried to manually send an HTTP request to Gemini API:

```
export GEMINI_API="my_gemini_api"
wget --header="Content-Type: application/json" \
     --post-data='{
       "contents": [{
         "parts":[{"text": "Write a story about a magic backpack."}]
       }]
     }' \
     "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}" \
     -O -
```

Which gives me the following error:

```
Connecting to generativelanguage.googleapis.com (216.58.210.170:443)
wget: server returned error: HTTP/1.1 403 Forbidden
```

I also tried to use the IPv6 address:

```
wget --header="Content-Type: application/json" \
     --post-data='{
       "contents": [{
         "parts":[{"text": "Write a story about a magic backpack."}]
       }]
     }' \
     "https://2a00:1450:4026:802::200a/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}" \
     -O -
```

Which gives me the following error:

```
Connecting to 2a00:1450:4026:802::200a ([2a00:1450:4026:802::200a]:443)
wget: can't connect to remote host: Network unreachable
```

On a side note, N8N can access other instances. I tried with DeepSeek and Groq credentials, and there's no issue. Google services are the only ones refused to work.

## Share the output returned by the last node

Only an error because I can't use the Google BigQuery and Google Gemini nodes.

![Image](https://github.com/user-attachments/assets/cd641c04-d13f-4ebb-bdb0-dd2174a03d01)

![Image](https://github.com/user-attachments/assets/483b6056-d55a-4cff-9676-dca9979dfabd)

## Deployment config

This is the Docker compose file deployed in Coolify:

```
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - SERVICE_FQDN_N8N_5678
      - 'N8N_EDITOR_BASE_URL=${SERVICE_FQDN_N8N}'
      - 'WEBHOOK_URL=${SERVICE_FQDN_N8N}'
      - 'N8N_HOST=${SERVICE_URL_N8N}'
      - 'GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Berlin}'
      - 'TZ=${TZ:-Europe/Berlin}'
    volumes:
      - 'n8n-data:/home/node/.n8n'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10
```

And this is the .env:

```
GENERIC_TIMEZONE=Asia/Jakarta
NODE_ENV=production
SERVICE_FQDN_N8N=https://flow.konsulin.care
SERVICE_URL_N8N=flow.konsulin.care
NODE_VERSION=22.12.0
DOMAIN_NAME=konsulin.care
N8N_HOST=flow.konsulin.care
N8N_PORT=5678
N8N_PROTOCOL=https
N8N_RUNNERS_ENABLED=true
SUBDOMAIN=flow
TZ=Asia/Jakarta
WEBHOOK_URL=https://flow.konsulin.care/
```

## Related issues

This problem seems related to @AFirouzi [report](https://github.com/n8n-io/n8n/issues/12871), but I haven't been able to solve the underlying issue.

### core

- n8nVersion: 1.80.5
- platform: docker (self-hosted)
- nodeJsVersion: 20.18.3
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

### pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

### client

- userAgent: mozilla/5.0 (x11; linux x86_64; rv:135.0) gecko/20100101 firefox/135.0
- isTouchDevice: false

Generated at: 2025-03-02T04:06:55.307Z}
