### ISSUE TITLE
Binary response is missing when execution logging is disabled

### ISSUE THREAD

**Issue by centigrade-kdk** [n8n-io/n8n#14101]
### Bug Description

When a workflow with a Webhook Trigger responds with the last node being an HTTP Request that fetches an image via a GET request, the image is not displayed in the production response if execution saving is disabled.

<img width="71" alt="Image" src="https://github.com/user-attachments/assets/447b82a4-9c78-467e-bf04-8b8aa4355527" />

**Note**:
This behavior occurs after switching the binary data mode to `N8N_DEFAULT_BINARY_DATA_MODE=filesystem`. With the `default` (in-memory) mode, the same setup works without any issues.

### To Reproduce

1. Deploy a Docker container with `N8N_DEFAULT_BINARY_DATA_MODE=filesystem`.
2. Create a workflow with a Webhook GET trigger that response with the last node.
3. Add an HTTP Request node that requests an image (in our case, from another workflow that responds with a binary image).
4. Disable all execution saving options (Production Success, Production Error, Test Success, Test Error).
5. Enable the workflow and test it in Production Mode (not Test Mode, as the issue does not appear there).

### Expected behavior

The Webhook should return the image from the HTTP Request, even when `N8N_DEFAULT_BINARY_DATA_MODE=filesystem` is set and all execution saving options are disabled.

### Operating System

Official n8n Docker Image

### n8n Version

1.83.2

### Node.js Version

-

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @centigrade-kdk,

We have created an internal ticket to look into this which we will be tracking as "GHC-1302"

**Comment by centigrade-kdk** [comment]
Hey @Joffcom,

thanks for the quick reply. I created a new workflow using your minimal example and I'm still encountering the issue I originally mentioned.

<img width="515" alt="Image" src="https://github.com/user-attachments/assets/a7f9e206-f2c0-42ad-9caa-eb5eee2e8939" />

<img width="1088" alt="Image" src="https://github.com/user-attachments/assets/79f1ab25-0452-4266-9947-7239c4c2eede" />

I've checked the docker environment variables and didn't see anything unusual that could be related to this. One difference from my deployment might be that I'm still using a SQLite database.


Here a minimal docker compose with which I can reproduce the error
```
services:

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.83.1
    restart: unless-stopped
    environment:
      - N8N_HOST=DOMAIN
      - N8N_EDITOR_BASE_URL=https://DOMAIN
      - WEBHOOK_URL=https://DOMAIN/
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_PATH=/
      - N8N_PROXY_HOPS=1
      - N8N_TEMPLATES_ENABLED=false
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    networks:
      - default
    volumes:
      - ./container-data/n8n:/home/node/.n8n
      - ./container-data/storage-data:/opt/data
```

NOTE: I run the container behind a revers proxy

**Comment by Joffcom** [comment]
Hey @centigrade-kdk 

Can you remove n8n_path, n8n_editor, n8n_port, n8n_protocol they are default values and don't need to be set and n8n_editor will default to webhook_url.

**Comment by centigrade-kdk** [comment]
@Joffcom 

I've removed the suggested variables, including the `N8N_TEMPLATES_ENABLED` environment variable, but I'm still encountering the same issue.


Here the updated docker-compose:
```
services:

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.84.1
    restart: unless-stopped
    environment:
      - N8N_HOST=DOMAIN
      - WEBHOOK_URL=https://DOMAIN
      - N8N_PROXY_HOPS=1
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem

    networks:
      - default
    volumes:
      - ./container-data/n8n:/home/node/.n8n
      - ./container-data/storage-data:/opt/data
```
