### ISSUE TITLE
2FA activation leads to a 404 error when submitting login/password

### ISSUE THREAD

**Issue by Tryum** [n8n-io/n8n#14275]
### Bug Description

My setup :
- n8n running under docker
- nginx proxy manager as a reverse proxy

When enabling 2FA, I can't log anymore, getting a 404 error from a POST request to /rest/login with my credentials, I'm never getting the 2FA prompt

Out of the box, I get this error in the logs
```
n8n         | ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
n8n         |     at Object.xForwardedForHeader (/usr/local/lib/node_modules/n8n/node_modules/express-rate-limit/dist/index.cjs:166:13)
n8n         |     at Object.wrappedValidations.<computed> [as xForwardedForHeader] (/usr/local/lib/node_modules/n8n/node_modules/express-rate-limit/dist/index.cjs:338:22)
n8n         |     at Object.keyGenerator (/usr/local/lib/node_modules/n8n/node_modules/express-rate-limit/dist/index.cjs:593:20)
n8n         |     at /usr/local/lib/node_modules/n8n/node_modules/express-rate-limit/dist/index.cjs:644:32
n8n         |     at /usr/local/lib/node_modules/n8n/node_modules/express-rate-limit/dist/index.cjs:625:5 {
n8n         |   code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
n8n         |   help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
n8n         | }
```

I tried setting `N8N_PROXY_HOPS=1` without success (I saw this in the forums).

### To Reproduce

1. Enable 2FA for user
2. Logout
3. Login

### Expected behavior

I should be asked for my auth code and be able to login

### Operating System

Debian 12 (docker compose)

### n8n Version

1.84.3

### Node.js Version

v20.18.3

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Tryum 

Once you set the proxy hops did you remember to stop and start (not restart) n8n?

Can you also make sure you have the websockets option set in proxy manager.

When you try to login and you get the 404 page what does it look like and what is the url?

**Comment by Tryum** [comment]
Hi @Joffcom !

Changing env variable in a docker compose recreates the containers so I should have been covered. To be safe I down/up the deployment, but I'm still getting the issue.

Websockets are enabled in reverse proxy.

When going to the top level, location bar change to `/signin?redirect=%252F` and I'm greeted whit the classic login page.

![Image](https://github.com/user-attachments/assets/5ef3073f-6ef9-489f-bf41-1dead1b60482)

If I inspect network requests, I can see 2 XHR GET that fails : `/rest/events/session-started` and `/rest/login`. (404).
After entering credentials and clicking "Sign in", an XHR POST to `/rest/login` gets a 404 too.

I set N8N logs to debug, nothing outputs regarding the issue.

I inspected with `tshark` on the host, and the requests to `/rest/*` are reaching the host, not a proxy issue.

**Comment by Joffcom** [comment]
Hey @Tryum,

I have tried to reproduce this on `1.85.3` and after enabling 2FA when I attempt to login I get the screen to enter the code then it logs me in. This would suggest it is either fixed in a newer release or there is potentially something in your config / environment causing an issue.

Can you share your full n8n config and I will see if I can reproduce with that.

**Comment by Tryum** [comment]
Sure,
Here's the relevant part of my docker-compose :
```
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    pull_policy: always
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${N8N_SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_PROXY_HOPS=1
      - N8N_LOG_LEVEL=debug
    volumes:
      - ./n8n/data:/home/node/.n8n
      - ./n8n/local-files:/files
```

I tried 2FA login without reverse proxy (using `N8N_SECURE_COOKIE=false`) and it worked... I'll do some capture analysis later to checjk what's happening. (witouht reverse proxy, `/rest/*` endpoints returns error 401 instead of 404).
