### ISSUE TITLE
Startup Error in n8n v1.88.0: Missing Parameter Name in path-to-regexp Package

### ISSUE THREAD

**Issue by loudotdigital** [n8n-io/n8n#14645]
### Bug Description

After updating my n8n instance to version 1.88.0, I started experiencing an error during startup that keeps the cointainer rebooting. Below is the log snippet showing the issue:

```
Last session crashed
Initializing n8n process
n8n ready on 0.0.0.0, port 5678
n8n Task Broker ready on 127.0.0.1, port 5679
TypeError: Missing parameter name at 7: https://git.new/pathToRegexpError
    at name (/usr/local/lib/node_modules/n8n/node_modules/path-to-regexp/dist/index.js:73:19)
    at lexer (/usr/local/lib/node_modules/n8n/node_modules/path-to-regexp/dist/index.js:87:27)
    at lexer.next (<anonymous>)
    at Iter.peek (/usr/local/lib/node_modules/n8n/node_modules/path-to-regexp/dist/index.js:106:38)
    at Iter.tryConsume (/usr/local/lib/node_modules/n8n/node_modules/path-to-regexp/dist/index.js:112:28)
    at Iter.text (/usr/local/lib/node_modules/n8n/node_modules/path-to-regexp/dist/index.js:128:30)
    at consume (/usr/local/lib/node_modules/n8n/node_modules/path-to-regexp/dist/index.js:152:29)
    at parse (/usr/local/lib/node_modules/n8n/node_modules/path-to-regexp/dist/index.js:183:20)
    at /usr/local/lib/node_modules/n8n/node_modules/path-to-regexp/dist/index.js:294:74
    at Array.map (<anonymous>)
Exiting due to an error.
Missing parameter name at 7: https://git.new/pathToRegexpError
Registered runner "JS Task Runner" (h_suSQXcToVe_kegllQGa) 
User settings loaded from: /home/node/.n8n/config
```

Environment:
Running n8n inside a Docker container (managed using Coolify) on a home server.
Server specs:
CPU: Intel i5
RAM: 32GB
Disk: 1TB

Let me know if you need any more information or logs to troubleshoot further

### To Reproduce

.

### Expected behavior

.

### Operating System

Docker container (managed using Coolify) 

### n8n Version

1.88.0

### Node.js Version

v20.18.3

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @loudotdigital,

We have created an internal ticket to look into this which we will be tracking as "GHC-1593"

**Comment by loudotdigital** [comment]
no, Im using docker.n8n.io/n8nio/n8n as image

and yes, the volumes are mounted inside the container. Find below the docker-compose file.
note that ${DATA-FOLDER} isn't working as it should, and it ended up creating the volume inside the container

```
services:
  n8n:
    image: 'docker.n8n.io/n8nio/n8n:1.86.1'
    environment:
      - 'N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}'
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      - N8N_RUNNERS_MAX_CONCURRENCY=5
      - N8N_RUNNERS_TASK_TIMEOUT=60
      - N8N_RUNNERS_HEARTBEAT_INTERVAL=30
      - 'WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/'
      - 'N8N_ENDPOINT_WEBHOOK_TEST=https://${SUBDOMAIN}.${DOMAIN_NAME}/'
      - SERVICE_FQDN_N8N_5678
      - 'N8N_EDITOR_BASE_URL=${SERVICE_FQDN_N8N}'
      - 'N8N_HOST=${SERVICE_URL_N8N}'
      - 'GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Lisbon}'
      - DB_TYPE=postgresdb
      - 'DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}'
      - DB_POSTGRESDB_HOST=postgresql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=$SERVICE_USER_POSTGRES
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_PASSWORD=$SERVICE_PASSWORD_POSTGRES
    volumes:
      - '${DATA-FOLDER}/n8n-data:/home/node/.n8n'
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10
  postgresql:
    image: 'postgres:16-alpine'
    volumes:
      - '${DATA-FOLDER}/postgresql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - 'POSTGRES_DB=${POSTGRES_DB:-n8n}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10

```
