### ISSUE TITLE
Webhook Node URL Path Not Updating from /null After Saving (v1.88.0, Local Docker Desktop + Nginx Proxy)

### ISSUE THREAD

**Issue by Gtapia69** [n8n-io/n8n#14856]
### Bug Description

When a new Webhook node is added to a workflow, the Test and Production URLs correctly display the base public URL but end in /null (e.g., https://n8n.example.app/webhook-test/null), as expected before the first save.
However, after saving the workflow, the URLs displayed within the Webhook node's configuration panel fail to update. They consistently remain ending in /null, regardless of whether the "Path" input field was left empty (expecting an auto-generated path) or filled with a custom path.
Importantly, other workflow changes ARE saved correctly (e.g., adding/removing other nodes persists after saving and reloading). The issue seems specific to the logic that registers and/or displays the webhook's path in the UI.

### To Reproduce

1.Access the n8n editor via the local HTTPS URL (https://n8n.example.app).
2.Create a new, empty workflow.
3.Add a Webhook node to the canvas.
4.Observe the initial URLs ending in /null.
5.Scenario 1 (Auto-path): Leave the "Path" field empty. Click "Save" workflow. Reload page or close/re-open node panel.
6.Scenario 2 (Custom-path): Enter a simple, valid custom path (e.g., mytestwebhook) in the "Path" field. Click "Save" workflow. Reload page or 7.close/re-open node panel.
8.Observe Result: In both scenarios, the displayed Test/Production URLs still end in /null. In Scenario 2, the custom path text is correctly saved and 9.visible in the "Path" input field itself, but it's not reflected in the generated URLs below it.

Troubleshooting Steps Taken:
Confirmed N8N_PUBLIC_URL, WEBHOOK_URL, and N8N_TRUST_PROXY=true environment variables are set correctly for the local URL and are visible inside the container.
Resolved earlier trust proxy errors; no relevant errors appear in n8n logs when saving the webhook node now.
Verified that other node changes are saved successfully.
Tested in browser incognito mode to rule out client-side caching.

### Expected behavior

After saving the workflow, the Test and Production URLs displayed in the Webhook node panel should update to reflect either the auto-generated path (if the "Path" field was saved empty) or the custom path entered by the user.

### Operating System

win 10

### n8n Version

1.88.0

### Node.js Version

v20.19.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Gtapia69,

Thanks for reporting this issue! We’ve attempted to reproduce the problem, but unfortunately, we weren’t able to replicate it. It’s possible there was some environmental or other variable that prevented us from seeing the same behavior.

If you’re still encountering this issue, please provide any additional details or steps to reproduce it, and we’d be happy to investigate further. Thanks for your understanding!

**Comment by alanoteles** [comment]
I'm facing the same issue.
This is the content of my .env file. Is there anything here that could be causing this issue? Some icons are also not being displayed.

```
WEBHOOK_URL=https://my-domain.com/
VUE_APP_URL_BASE_API=https://my-domain.com/
N8N_HOST=my-domain.com
N8N_PORT=5678

N8N_BASIC_AUTH_ACTIVE=true
N8N_BASIC_AUTH_USER=my-user
N8N_BASIC_AUTH_PASSWORD=my-password

N8N_DIAGNOSTICS_ENABLED=false
N8N_VERSION_NOTIFICATIONS_ENABLED=false
N8N_TEMPLATES_ENABLED=false

N8N_RUNNERS_ENABLED=true
N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
N8N_METRICS=true

N8N_EMAIL_MODE=smtp
N8N_SMTP_HOST=smtp.my-server.com
N8N_SMTP_PORT=587
N8N_SMTP_USER=automations@my-domain.com
N8N_SMTP_PASS=user-password
N8N_SMTP_SENDER="My Company <noreply@my-domain.com>"
N8N_SMTP_SSL=false

N8N_DIAGNOSTICS_ENABLED=false
N8N_DEFAULT_NAME=MyCompany
N8N_TRUST_PROXY=true
N8N_CONFIG_FILES=/home/node/.n8n/config.json

N8N_PUBLIC_API_DISABLED=true

N8N_EDITOR_BASE_URL=https://my-domain.com

POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=n8n

POSTGRES_NON_ROOT_USER=user
POSTGRES_NON_ROOT_PASSWORD=user
```

And this is the content of my docker-compose.yml:

```
version: '3'

networks:
  n8n:

volumes:
  db_storage:
  n8n_storage:

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: n8n
    volumes:
      - db_storage:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - n8n
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8nUser -d n8n"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:1.90.2
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=user
      - DB_POSTGRESDB_PASSWORD=password
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD='${N8N_BASIC_AUTH_PASSWORD}'
      - N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED}
      - N8N_VERSION_NOTIFICATIONS_ENABLED=${N8N_VERSION_NOTIFICATIONS_ENABLED}
      - N8N_TEMPLATES_ENABLED=${N8N_TEMPLATES_ENABLED}
      - N8N_RUNNERS_ENABLED=${N8N_RUNNERS_ENABLED}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}
      - N8N_METRICS=${N8N_METRICS}
      - N8N_EMAIL_MODE=${N8N_EMAIL_MODE}
      - N8N_SMTP_HOST=${N8N_SMTP_HOST}
      - N8N_SMTP_PORT=${N8N_SMTP_PORT}
      - N8N_SMTP_USER=${N8N_SMTP_USER}
      - N8N_SMTP_PASS='${N8N_SMTP_PASS}'
      - N8N_SMTP_SENDER=${N8N_SMTP_SENDER}
      - N8N_SMTP_SSL=${N8N_SMTP_SSL}
      - N8N_HOST=${N8N_HOST}
      - N8N_DEFAULT_NAME=${N8N_DEFAULT_NAME}
      - N8N_TRUST_PROXY=${N8N_TRUST_PROXY}
      - N8N_CONFIG_FILES=${N8N_CONFIG_FILES}
      - N8N_PUBLIC_API_DISABLED=${N8N_PUBLIC_API_DISABLED}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
    ports:
      - 5678:5678
    networks:
      - n8n
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./config.json:/home/node/.n8n/config.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - postgres
```

Any ideas?
TIA!

**Comment by Joffcom** [comment]
Hey @alanoteles,

I would check the nginx proxy settings as well but to start with I would remove the bad settings that AI gave you...

```
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD='${N8N_BASIC_AUTH_PASSWORD}'
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
```

I would then add 
```
- WEBHOOK_URL=https://your-domain.com
```

Your .env file could do with some cleaning as well but this is a start for you, As this is not a bug I am going to close this but for more support on this I would recommend checking the docs and checking out the [community support forum](https://community.n8n.io).

**Comment by orosadmin** [comment]
I am still having this issue, and have tried all the solutions above, but can't quite get it right. I am using NGINX as the reverse proxy in front of n8n, with the following docker-compose file

```
n8n:
      image: docker.n8n.io/n8nio/n8n:1.81
      container_name: n8n
      restart: always
      expose:
        - 5678
      environment:
        - NODE_ENV=production
        - N8N_PUBLIC_URL=https://n8n.orosdata.com
        - WEBHOOK_URL=https://n8n.orosdata.com
        - GENERIC_TIMEZONE=America/Sao_Paulo
        - N8N_METRICS=true
        - N8N_LOG_LEVEL=debug
        - N8N_PROXY_HOPS=1
        - EXECUTIONS_DATA_PRUNE=true
        - N8N_RUNNERS_ENABLED=true
        - N8N_EDITOR_BASE_URL=https://n8n.orosdata.com
        - EXECUTIONS_DATA_PRUNE_MAX_COUNT=50000
        - EXECUTIONS_DATA_MAX_AGE=168
      volumes:
        - n8n_data:/home/node/.n8n
        - ./n8n-files:/files
      deploy:
        resources:
          limits:
            cpus: '1.0'
            memory: 2G
          reservations:
            cpus: '0.5'
            memory: 1G
      healthcheck:
        test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/healthz"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

```
    


The Nginx configurations is as follows
server {
    listen 443 ssl http2;
    server_name n8n.orosdata.com;

    # SSL configuration
    ssl_certificate [CERTIFICATE PATH];
    ssl_certificate_key [KEY PATH];
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_ciphers [REDACTED CYPHER];
    
    # SSL session cache
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;
    
    # Increase client max body size for file uploads
    client_max_body_size 50M;
    
    # N8N proxy settings with WebSocket support
    location / {
        proxy_pass http://n8n:5678;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        
        # CRITICAL: WebSocket support for N8N
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_cache_bypass $http_upgrade;
        proxy_ssl_server_name on;
        
        # Optimizations for N8N
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
        proxy_request_buffering off;
        
        # Increase timeouts for long-running workflows
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
        
        # Rate limiting for general access
        limit_req zone=tag_manager burst=20 nodelay;
    }
    
    # Health check endpoint
    location /healthz {
        proxy_pass http://n8n:5678/healthz;
        access_log off;
    }
    
    # Specific webhook endpoint optimization
    location ~ ^/(webhook|webhook-test) {
        proxy_pass http://n8n:5678;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        
        # WebSocket support for webhooks
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        
        # Optimized for webhook performance
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
        proxy_request_buffering off;
        
        # Webhook timeouts
        proxy_connect_timeout 10;
        proxy_send_timeout 30;
        proxy_read_timeout 30;
        
        # Rate limiting for webhooks
        limit_req zone=tag_manager burst=100 nodelay;
    }
}
