### ISSUE TITLE
Task execution timed out after 300 seconds in Queue Mode with TaskRunners enabled

### ISSUE THREAD

**Issue by othiel1984** [n8n-io/n8n#14865]
### Bug Description

If a Code Node takes longer than 5 minutes the Task execution times out after 300 seconds.
Queue Mode and TaskRunners are enabled 

### To Reproduce

1. Set up Docker compose 
```
version: '3.8'

volumes:
  db_storage:
  n8n_storage:

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - traefik
    command: ["redis-server","--appendonly","yes"]
  postgresn8n:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    networks:
      - traefik  

    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-post:
    image: docker.n8n.io/n8nio/n8n:1.89.2
    restart: always
    environment:
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - WEBHOOK_URL=n8nhosturl
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_HOST=n8nhosturl
      - N8N_LOG_LEVEL=debug
      - N8N_RUNNERS_ENABLED=true
      - N8N_CONCURRENCY=50
      - N8N_RUNNERS_TASK_TIMEOUT=60000
      - EXECUTIONS_TIMEOUT=10800000
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgresn8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - EXECUTIONS_MODE=queue
    networks:
      - traefik 
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n-post-router.entrypoints=web,web-secure
      - traefik.http.routers.n8n-post-router.rule=Host(`n8nhosturl`)
      - traefik.http.routers.n8n-post-router.service=n8n-post-service
      - traefik.http.routers.n8n-post-router.middlewares=n8n-post-redirect
      - traefik.http.services.n8n-post-service.loadbalancer.server.port=5678
      - traefik.http.routers.n8n-post-router-https.rule=Host(`n8nhosturl`)
      - traefik.http.routers.n8n-post-router-https.service=n8n-post-service
      - traefik.http.routers.n8n-post-router-https.tls=true
      - traefik.http.middlewares.n8n-post-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.n8n-post-redirect.redirectscheme.permanent=true
    volumes:
      - n8n_storage:/home/node/.n8n
      - /local-files:/files 
    depends_on:
      postgresn8n:
        condition: service_healthy
      



  n8n-post-worker:
    image: docker.n8n.io/n8nio/n8n:1.89.2
    command: worker 
    restart: always
    environment:
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_LOG_LEVEL=debug
      - N8N_ENCRYPTION_KEY=xxxxxxxxxxxxx
      - N8N_RUNNERS_ENABLED=true
      - N8N_CONCURRENCY=50
      - N8N_RUNNERS_TASK_TIMEOUT=60000 
      - EXECUTIONS_TIMEOUT=10800000
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgresn8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    depends_on:
      - n8n-post
      - redis
    networks:
      - traefik


networks:
   traefik:
      name: traefik
      external: true

```
2. Start up Environment 
`docker compose up --scale n8n-post-worker=3 -d`

3 Steps to Reproduce 
Create WF with only one Code Node and following content
```
await new Promise(resolve => setTimeout(resolve, 60000000)); 
return $input.all();
 ```
4. Wait 5 Minutes

![Image](https://github.com/user-attachments/assets/ebbdc7d1-03ae-488a-8da8-fbec06c3c4e2)

5. Timeout Occurs with manuel and scheduled Trigger
6. Turn of queue Mode and Taskrunners --> everything is fine  

### Expected behavior

For long running tasks the code node should time out after  the given Timeout. 

The Timeouts in the docker compose seem to be not effective 

### Operating System

Debian with Docker version 25.0.4, build 1a576c5

### n8n Version

1.89.2

### Node.js Version

20.19.0

### Database

PostgreSQL

### Execution mode

queue
