### ISSUE TITLE
SMTP Email outlook / microsoft365 connection issue

### ISSUE THREAD

**Issue by zazin** [n8n-io/n8n#15296]
### Bug Description

I have problem with SMTP connection with error log message like this.
I am sure my SMTP credentials is valid, and work with another app.

```
Invalid login: 535 Incorrect authentication data
Failed to send email
Please contact your administrator: Invalid login: 535 Incorrect authentication data
ResponseError: Please contact your administrator: Invalid login: 535 Incorrect authentication data
    at PasswordResetController.forgotPassword (/usr/local/lib/node_modules/n8n/dist/controllers/password-reset.controller.js:89:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26
```

i am using docker. this is my docker-compose yaml:

```
volumes:
  n8n_storage:

x-shared: &shared
  restart: always
  image: n8nio/n8n:1.90.3
  network_mode: bridge
  environment:
    - N8N_HOST=my.domain.id
    - N8N_PROTOCOL=https
    - NODE_ENV=production
    - WEBHOOK_URL=https://my.domain.id/
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=172.17.0.1
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=n8n_db
    - DB_POSTGRESDB_USER=n8n_user
    - DB_POSTGRESDB_PASSWORD="***********"
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=172.17.0.1
    - N8N_ENCRYPTION_KEY=********
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    - ENABLE_ALPINE_PRIVATE_NETWORKING=true
    - GENERIC_TIMEZONE=Asia/Jakarta
    - N8N_EMAIL_MODE=smtp
    - N8N_SMTP_HOST=mail.domain.id
    - N8N_SMTP_PORT=465
    - N8N_SMTP_USER=nua@domain.id
    - N8N_SMTP_PASS="***************"
    - N8N_SMTP_SENDER="MyAccount <nua@domain.id>"
    - N8N_SMTP_SSL=true
  volumes:
    - n8n_storage:/home/node/.n8n

services:
  n8n:
    <<: *shared
    ports:
      - 127.0.0.1:5678:5678

  n8n-worker:
    <<: *shared
    command: worker
    depends_on:
      - n8n
```

### To Reproduce

1. go forgot password page
2. input any email
3. click submit

### Expected behavior

success send email

### Operating System

Ubuntu linux 22.04

### n8n Version

1.90.3

### Node.js Version

20.19.0

### Database

PostgreSQL

### Execution mode

queue
