### ISSUE TITLE
Schedule Trigger Duplicated Workflow Executions

### ISSUE THREAD

**Issue by RoseSecurity** [n8n-io/n8n#16332]
## Deployment Details

- Utilizing `n8n-helm-charts` to deploy `n8n` on EKS with version `1.97.1`
- Enterprise license, two replicas, regular mode, and internal task runners
- Pertinent settings:

```yaml
# the main (n8n) application related configuration + Kubernetes specific settings
# The config: {} dictionary is converted to environmental variables in the ConfigMap.
main:
  secret:
    n8n:
      encryption_key: XXXXXXX
    db:
      postgresdb:
        password: XXXXX
  config:
    # Disable telemetry collection (disables Ask AI in the Code node)
    n8n:
      diagnostics:
        enabled: false
      # Required for reverse proxy usage
      proxy:
        hops: 1
      # Enforce correct permissions for the n8n configuration
      enforce:
        settings:
          file:
            permissions: true
      log:
        level: info
      license:
        activation:
          key: XXXXXXX
      metrics: true
      public:
        api:
          disabled: true
          swaggerui:
            disabled: true
      hiring:
        banner:
          enabled: false
      version:
        notifications:
          enabled: true
      runners:
        enabled: true
        mode: internal
        auth:
          token: XXXXXXX
        max:
          concurrency: 5
        task:
          timeout: 300
        broker:
          listen:
            address: "0.0.0.0"
    db:
      type: postgresdb
      postgresdb:
        database: n8n
        host: XXXXXXXXX
        port: "5432"
        user: n8n-user
    webhook:
      url: https://XXXXXXX
    node:
      function:
        allow:
          external: "*"
```

## Workflow Details

- After upgrading to `1.97.1`, we began seeing duplicate workflow executions for our schedule trigger nodes executing sub-workflows:

![Image](https://github.com/user-attachments/assets/1b10c290-51a5-4cb1-ba88-d1dc6e94cb3c)

- We observe duplicate executions where each workflow executes twice. When we set the trigger to one minute rather than five, duplicates only occur on the five minute mark

![Image](https://github.com/user-attachments/assets/edb5fc41-4ee3-41e1-8b38-436e46a0d7ec)

### To Reproduce

1. Schedule trigger to execute sub-workflow every five minutes
2. Review executions
3. Observe duplicated entries

### Expected behavior

When using `1.95.3`, the schedule trigger workflows executed every five minutes with no duplicated executions.

### Operating System

Alpine Linux v3.21 on Kubernetes

### n8n Version

1.97.1

### Node.js Version

20.19.2

### Database

PostgreSQL

### Execution mode

main (default)
