### ISSUE TITLE
"Connection lost" in workflow

### ISSUE THREAD

**Issue by chozeur** [n8n-io/n8n#16368]
### Bug Description

I installed n8n on a VPS, using docker compose, without Traefik since I already have Nginx set up on the VPS. 

Since then, I haven't been able to run any workflow, because of a "Connection lost" alert.

![Image](https://github.com/user-attachments/assets/75ab8423-d15b-4c53-8a89-a2331f097542)

![Image](https://github.com/user-attachments/assets/3fafb298-2e59-4b9d-a01c-cdbaf8be4dfe)

I tried to switch to previous versions, but the error is still the same.

NB: I have multiple apps running on the VPS, some of them using web sockets with no problem.

Here are my `docker-compose.yml` and `/etc/nginx/sites-available/n8n.mydomain.com`

```
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.mydomain.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.mydomain.com
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - VUE_APP_URL_BASE_API=https://n8n.mydomain.com
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

volumes:
  n8n_data:
```

```
server {
    server_name n8n.mydomain.com;

    location / {
        proxy_pass http://127.0.0.1:5678;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1; 
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection “connection_upgrade”; 
        chunked_transfer_encoding off;
        proxy_cache_bypass $http_upgrade;
        proxy_ssl_server_name on;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/n8n.mydomain.com-0001/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/n8n.mydomain.com-0001/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = n8n.mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name n8n.mydomain.com;
    return 404; # managed by Certbot


}
```

### To Reproduce

1. Run Docker compose without Traefik
2. Login to n8n.yourdomain.com
3. Go to workflow

### Expected behavior

No connection failure.

### Operating System

Debian 12

### n8n Version

1.97.1

### Node.js Version

20.19.2

### Database

SQLite (default)

### Execution mode

main (default)
