### ISSUE TITLE
Docker version for armv8

### ISSUE THREAD

**Issue by subzero355** [n8n-io/n8n#1638]
I have Pi 4B and installed Ubuntu, unable to run the docker version using ``` sudo docker run -d --restart always --name n8n -p 8012:5678 -v /home/ubuntu/n8n:/root/.n8n n8nio/n8n:latest-rpi```
![image](https://user-images.githubusercontent.com/7847452/114163155-7e8f9980-9947-11eb-9afc-7aa48b8aea1e.png)

**Comment by janober** [comment]
Thanks a lot for reporting this issue. 

Fixing that will maybe be easy once the following PR has been merged: https://github.com/n8n-io/n8n/pull/1625

Sadly did not have time to review yet. But you should be able to use the code to temporary build your own.

**Comment by orangethakkali** [comment]
Thanks @janober , I have limited knowledge on how to use that code to run the workflow. If you can guide me how to start,  I can certainly dig deeper and build the image. Will running the below workflow code generate the image for armv8? If yes, how and where do I run this ?
```
name: Docker Image CI

on:
  push:
    tags:
      - n8n@*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:14})
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./docker/images/n8n
          build-args: |
            N8N_VERSION=${{steps.vars.outputs.tag}}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/n8n:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/n8n:latest
      -
        name: Build (debian)
        uses: docker/build-push-action@v2
        with:
          context: ./docker/images/n8n-debian
          build-args: |
            N8N_VERSION=${{ steps.vars.outputs.tag }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/n8n:${{ steps.vars.outputs.tag }}-debian
            ${{ secrets.DOCKER_USERNAME }}/n8n:latest-debian
```
