### ISSUE TITLE
🚨 JavaScript Code Node Timeout in v1.98.1 — Works Fine in v1.97.1

### ISSUE THREAD

**Issue by vineetdpnd** [n8n-io/n8n#16541]
### Bug Description

After upgrading to n8n@1.98.1, all executions using the Code Node (JavaScript language) stop responding and eventually time out — even with basic or minimal logic inside. This issue is not present in version 1.97.1, where the same workflows run perfectly.

Notably, Python language execution in the Code Node continues to work normally, indicating this is specific to the JavaScript node execution in 1.98.1.

System memory is not a constraint — we have 30GB+ of free memory on the host, and no other performance issues are observed.

### To Reproduce

1. Upgrade from v1.97.1 to v1.98.1
2. Create a new workflow with a Code Node using:

`return [
  {
    json: {
      test: $now
    }
  }
];
`

3. Execute the node

4. Observe that the node hangs indefinitely or times out with no result

5. Roll back to v1.97.1 → same node executes correctly.

### Expected behavior

The JavaScript Code Node should:

Execute even basic JavaScript code without issue

Return a valid output object (as it did in previous versions)

### Operating System

Ubuntu 24.04.2 LTS

### n8n Version

1.98.1

### Node.js Version

v22.14.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @vineetdpnd,

Thank you for reaching out! We’ve received your issue and are looking into it. To help us track this internally, we’ve created a Linear ticket with the reference: "GHC-2664".

We’ll keep you updated as we make progress, but if you have any additional details or context to share, feel free to add them here - it’s always helpful!

Thanks for your patience and for bringing this to our attention.

**Comment by Joffcom** [comment]
Thanks for reporting this issue! We’ve attempted to reproduce the problem, but unfortunately, we weren’t able to replicate it. It’s possible there was some environmental or other variable that prevented us from seeing the same behavior.

This is what I am seeing when following your instructions, Although I am on `1.98.2` so it could be that it was fixed but I am not aware of anything that would have impacted this.

![Image](https://github.com/user-attachments/assets/4ff5ecb1-0b7e-4309-8628-38b352a5b3b0)

**Comment by vineetdpnd** [comment]
@Joffcom  We deploy n8n using Docker. Please let us know if it would be helpful to share our docker-compose.yaml setup — happy to provide it for debugging.

We will also try upgrading to 1.98.2 and report back if the issue persists in that version or if it's resolved.

Thanks for your support

**Comment by rlegall-eness** [comment]
Hi, it seems that we've the same issue as @vineetdpnd.

We have two n8n instances on the same server. One in regular mode and the other one in queue mode. The code node in the regular one in 1.98.2 works perfectly but, in the queue one in 1.98.2, the same code node, with just a simple return, seems to hang indefinitely.

Thanks.

**Comment by Joffcom** [comment]
Most unusual, I am also running in queue mode with no issues. Are you both using task runners? It would be handy if you could both share the env options you have set (removing any sensitive values).

**Comment by mliga666** [comment]
Same problem, reverting to 1.97.1 solved

**Comment by Joffcom** [comment]
@mliga666 same question... what env options do you have set? We will need to work out the pattern for this one. I have tried on self hosted in queue mode and on cloud with no issues

**Comment by vineetdpnd** [comment]
@Joffcom 

Below is our docker compose yaml if it helps.

```
services:

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.98.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file:
      - .env
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=<HOST>
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      - N8N_PROXY_HOPS=1
      - N8N_DIAGNOSTICS_ENABLED=false
      - EXECUTIONS_TIMEOUT_MAX=7200
      - NODE_OPTIONS=--max-old-space-size=12288
      - N8N_RUNNERS_MAX_CONCURRENCY=10
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - NODE_ENV=production
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,node-forge,node-fetch
      - WEBHOOK_URL=https://<HOST>/
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=<USER>
      - N8N_BASIC_AUTH_PASSWORD=<PASSWORD>
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=<HOST>
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=<USER>
      - DB_POSTGRESDB_SCHEMA=<SCHEMA>
      - DB_POSTGRESDB_PASSWORD=<PASSWORD>
      - DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false
      - OPENAI_KEY=<OPENAI_KEY>
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

volumes:
  n8n_data:

```

**Comment by rlegall-eness** [comment]
@Joffcom 

Hello,

Here is our .yml

```
services:
  n8n-queue:
    image: n8nio/n8n:${N8N_TAG:-latest}
    container_name: n8n-queue
    restart: unless-stopped
    ports:
      - "${N8N_QUEUE_PORT}:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB_QUEUE}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_HOST=${N8N_QUEUE_HOST}
      - WEBHOOK_URL=https://${N8N_QUEUE_HOST}
      - TZ=${GENERIC_TIMEZONE}
      - N8N_EXECUTIONS_MODE=queue
      - N8N_RUNNERS_ENABLED=true
      - N8N_QUEUE_MODE=redis
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - N8N_REDIS_HOST=redis
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}
      - N8N_REDIS_PASSWORD=${REDIS_PASSWORD}
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
    depends_on:
      - postgres
      - redis
    volumes:
      - n8n-queue-data:/home/node/.n8n
    networks:
      - n8n-net

  n8n-worker:
    image: n8nio/n8n:${N8N_TAG:-latest}
    container_name: n8n-worker
    restart: unless-stopped
    command: worker
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB_QUEUE}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${GENERIC_TIMEZONE}
      - N8N_EXECUTIONS_MODE=queue
      - N8N_QUEUE_MODE=redis
      - N8N_REDIS_HOST=redis
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_REDIS_PASSWORD=${REDIS_PASSWORD}
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - N8N_LOG_LEVEL=debug
      - N8N_LOG_OUTPUT=console
    depends_on:
      - postgres
      - redis
    networks:
      - n8n-net

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "<ports>"
    networks:
      - n8n-net

volumes:
  postgres-data:
  n8n-main-data:
  n8n-queue-data:

networks:
  n8n-net:
```
