### ISSUE TITLE
Error: Failed to load module "external-secrets"

### ISSUE THREAD

**Issue by fouadbakkour** [n8n-io/n8n#16587]
### Bug Description

Error: Failed to load module "external-secrets": Cannot find module '/usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+backend-common@file+packages+@n8n+backend-common/node_modules/cli/dist/modules/external-secrets.ee/external-secrets.module'
Require stack:
- /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+backend-common@file+packages+@n8n+backend-common/node_modules/@n8n/backend-common/dist/modules/module-registry.js
- /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+backend-common@file+packages+@n8n+backend-common/node_modules/@n8n/backend-common/dist/index.js
- /usr/local/lib/node_modules/n8n/dist/config/index.js
- /usr/local/lib/node_modules/n8n/bin/n8n. Please review the module's entrypoint file name and the module's directory name.
    at ModuleRegistry.loadModules (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+backend-common@file+packages+@n8n+backend-common/node_modules/@n8n/backend-common/src/modules/module-registry.ts:61:12)
    at BaseCommand.loadModules (/usr/local/lib/node_modules/n8n/src/commands/base-command.ts:80:3)
    at /usr/local/lib/node_modules/n8n/bin/n8n:68:2

### To Reproduce

1. Clone n8n repo
2. Create docker compose file to deploy n8n + postgress
```yml
version: '3.8'

networks:
  n8n_net:
    driver: bridge

services:
  # >>> Database
  postgres:
    container_name: n8n_postgres
    build:
      context: ./postgres_deployment
      dockerfile: Dockerfile
    image: n8n/n8n_postgres:latest
    environment:
      POSTGRES_USER: admin_workflows_automation
      POSTGRES_PASSWORD: '*******'
      POSTGRES_DB: postgresdb
    ports:
      - '5531:5432'
    volumes:
      - ./postgres_deployment/pgdata:/var/lib/postgresql/data
    networks:
      - n8n_net
    restart: unless-stopped
  # >>> Web app
  n8n:
    container_name: n8n_engine
    build:
      context: .
      dockerfile: docker/images/n8n/Dockerfile
    image: n8n/n8n_engine:latest
    ports:
      - '5678:5678'
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: admin_workflows_automation
      DB_POSTGRESDB_PASSWORD: '*******'
      DB_POSTGRESDB_SCHEMA: n8n_schema
      WEBHOOK_URL: https://agents.mydomain.net
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: 'true'
      N8N_SECURE_COOKIE: 'false'
      N8N_LOG_OUTPUT: 'console,file'
      N8N_RUNNERS_ENABLED: 'true'
      N8N_DIAGNOSTICS_ENABLED: 'false'
      N8N_VERSION_NOTIFICATIONS_ENABLED: 'false'
      N8N_TEMPLATES_ENABLED: 'false'
      N8N_PERSONALIZATION_ENABLED: 'false'
      N8N_DISABLED_MODULES: 'insights'
    volumes:
      - n8n_data:/home/node/.n8n # n8n data and encryption key
      - ./n8n_files/config:/home/node/.n8n/config # n8n data and encryption key
    networks:
      - n8n_net
    restart: unless-stopped
  # >>> Micro-service for converting any file to PDF
  anyfile_to_pdf:
    container_name: file_converter_ms
    build:
      context: ./python/anyfile_to_pdf
      dockerfile: Dockerfile
    image: n8n/n8n_file_converter_ms:latest
    ports:
      - '8233:8233'
    networks:
      - n8n_net
    restart: unless-stopped
  # >>> Micro-service for converting audio OGA to OGG
  convert_oga_to_ogg:
    container_name: audio_file_converter_ms
    build:
      context: ./python/audio_file_converter
      dockerfile: Dockerfile
    image: n8n/n8n_audio_file_converter:latest
    ports:
      - '8231:8231'
    networks:
      - n8n_net
    restart: unless-stopped
volumes:
  n8n_data:

```
4. Run commands to deploy the stack
```bash
docker-compose -p n8n -f docker-compose.yml build
docker-compose -p n8n -f docker-compose.yml up -d
```

### Expected behavior

To deploy successfully!

### Operating System

Ubuntu 24.04.2 LTS 

### n8n Version

1.98.2

### Node.js Version

24.2.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @fouadbakkour,

Thank you for reaching out! We’ve received your issue and are looking into it. To help us track this internally, we’ve created a Linear ticket with the reference: "GHC-2693".

We’ll keep you updated as we make progress, but if you have any additional details or context to share, feel free to add them here - it’s always helpful!

Thanks for your patience and for bringing this to our attention.

**Comment by Joffcom** [comment]
Hey @fouadbakkour 

Can you share the docker file you are using? This doesn't happen with the official one so at the moment it seems tuounhsh

**Comment by fouadbakkour** [comment]
Hi @Joffcom , it's the current docker file in the repo, I did not touch or change anything in it.
That's it: https://github.com/n8n-io/n8n/blob/master/docker/images/n8n/Dockerfile

**Comment by yotomations** [comment]
+1 for the issue

**Comment by ManuLasker** [comment]
+2 I've just tried to follow contributing guidelines and the `pnpm start` command failed with that error.

**Comment by shortstacked** [comment]
Hi @fouadbakkour ,

I'm following up on this issue regarding the Docker Compose setup.

Using the provided minimal `docker-compose.yml` file:

```yaml
version: '3.8'

services:
  n8n:
    container_name: n8n_engine
    image: n8nio/n8n:local 
    ports:
      - '5678:5678'
    environment:
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: 'true'
      N8N_SECURE_COOKIE: 'false'
      N8N_LOG_OUTPUT: 'console,file'
      N8N_RUNNERS_ENABLED: 'true'
      N8N_DIAGNOSTICS_ENABLED: 'false'
      N8N_VERSION_NOTIFICATIONS_ENABLED: 'false'
      N8N_TEMPLATES_ENABLED: 'false'
      N8N_PERSONALIZATION_ENABLED: 'false'
      N8N_DISABLED_MODULES: 'insights'
    restart: unless-stopped
```

And executing the commands:

```bash
docker-compose -p n8n -f docker-compose.yml build
docker-compose -p n8n -f docker-compose.yml up -d
```

I can confirm that **this setup is currently working without any errors on the `latest` branch.**

As of v1.101.0, there were some changes related to the Docker building process. For local development and building images, users should now be able to run:

```bash
pnpm build:docker
```

This command should locally build the necessary Docker image.

Please let me know if you have any further questions or if this resolves your issue.

Thanks\!
