### ISSUE TITLE
Credentials are lost every time Docker Compose is restarted

### ISSUE THREAD

**Issue by robinspt** [n8n-io/n8n#16637]
### Bug Description

Every time a modification is made to Docker Compose and it requires a restart, all connection information within the credentials is lost. Additionally, the community nodes will encounter an error: There is a problem with this package, try uninstalling it then reinstalling to resolve this issue.

![Image](https://github.com/user-attachments/assets/eea6ff52-b765-4970-8f93-c01d746fe1ad)

![Image](https://github.com/user-attachments/assets/a257eb6e-2455-4745-884d-eec43cb005b2)

### To Reproduce

Deploy using Docker Compose
```
services:
    n8n_db:
        image: postgres:15
        container_name: n8n_pg
        restart: always
        networks:
            - mcp-server
        volumes:
            - /mnt/user/appdata/n8n/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=USER
            - POSTGRES_PASSWORD=PASSWORD
            - POSTGRES_DB=n8n
            - TZ=Asia/Shanghai
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U robinspt -d n8n"]
            interval: 5s
            timeout: 5s
            retries: 10

    docker-cli-installer:
        image: alpine:latest
        container_name: n8n_docker_init
        networks:
            - mcp-server
        command: >
          sh -c '
            apk update && 
            apk add --no-cache docker-cli &&
            cp /usr/bin/docker /shared/docker &&
            chmod +x /shared/docker &&
            echo "Docker CLI installed successfully"
          '
        volumes:
            - docker-cli-shared:/shared

    app:
        image: n8nio/n8n:latest
        container_name: n8n_app
        restart: always
        networks:
            - mcp-server
        depends_on:
            docker-cli-installer:
                condition: service_completed_successfully
            n8n_db:
                condition: service_healthy
            n8n_redis:
                condition: service_healthy
        environment:
            - DB_TYPE=postgresdb
            - DB_POSTGRESDB_HOST=n8n_db
            - DB_POSTGRESDB_PORT=5432
            - DB_POSTGRESDB_DATABASE=n8n
            - DB_POSTGRESDB_USER=USER
            - DB_POSTGRESDB_PASSWORD=PASSWORD
            - GENERIC_TIMEZONE=Asia/Shanghai
            - TZ=Asia/Shanghai
            - N8N_SECURE_COOKIE=false
            - N8N_RUNNERS_ENABLED=true
            - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
            - N8N_COMMUNITY_PACKAGES_ENABLED=true
            - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
            - NODE_FUNCTION_ALLOW_EXTERNAL=cheerio,axios,form-data
            - NODE_OPTIONS=--max_old_space_size=4096
            - N8N_EXECUTION_TIMEOUT=1800 
            - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/shared
        ports:
            - '5678:5678'
        volumes:
            - /mnt/user/appdata/n8n/app:/home/node/.n8n
            - /mnt/disk1/embymedia/workflow:/files
            - /var/run/docker.sock:/var/run/docker.sock
            - docker-cli-shared:/shared
        user: "0:0"

    n8n_redis:
        image: redis:7
        container_name: n8n_redis
        restart: always
        networks:
            - mcp-server
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    docker-cli-shared:

networks:
    n8n-network:
        driver: bridge
    mcp-server:
        external: true
```

### Expected behavior

Credentials will not be lost after docker compose restart, and community nodes do not need to be reinstalled.

### Operating System

UNRAID 7.1.2

### n8n Version

1.98.2

### Node.js Version

22.14.0

### Database

PostgreSQL

### Execution mode

main (default)
