### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by Venipa** [n8n-io/n8n#1700]
**Describe the bug**
upons loading the website this appears in the console, white page, nothing loads
![image](https://user-images.githubusercontent.com/17952364/115938590-86991e80-a49b-11eb-9aba-24d5b0b98be4.png)

**To Reproduce**
1. docker instance of n8n
2. nginx reverse proxy to localhost:5678
3. login etc
4. error on load:
5. 

**Expected behavior**

**Environment (please complete the following information):**
 - OS: 
```
Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch
```
 - n8n Version: 0.116.1
 - Node.js Version: v10.12

**Additional context**
```yaml
version: "2"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_TUNNEL_URL
      - VUE_APP_URL_BASE_API
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_FOLDER}/.n8n:/home/node/.n8n
```
