### ISSUE TITLE
docker-compose environment

### ISSUE THREAD

**Issue by jwillmer** [n8n-io/n8n#216]
I have a strange issue. I encountered that I wrote the `environment` twice in my `docker-compose`. Fixing it throws an error so now I'm asking why this works:

```
n8n:
    container_name: n8n
    image: n8nio/n8n:0.46.0
    restart: always
    networks:
        default:
        traefik_proxy:
    environment:
        DB_TYPE: mongodb
        DB_MONGODB_CONNECTION_URL: mongodb://${MONGOROOTUSER}:${MONGOROOTPW}@db:27017/n8n            
    ports:
        - 5678:5678
    environment:
        N8N_BASIC_AUTH_ACTIVE: 'true'
        N8N_BASIC_AUTH_USER: ${N8NUSER}
        N8N_BASIC_AUTH_PASSWORD: ${N8NPASSWORD}
        N8N_HOST: n8n.${DOMAINNAME}
    volumes:
    ...
```

But this throws an exception that the database was not found/wrong password:

```
n8n:
    container_name: n8n
    image: n8nio/n8n:0.46.0
    restart: always
    networks:
        default:
        traefik_proxy:
    ports:
        - 5678:5678
    environment:
        DB_TYPE: mongodb
        DB_MONGODB_CONNECTION_URL: mongodb://${MONGOROOTUSER}:${MONGOROOTPW}@db:27017/n8n   
        N8N_BASIC_AUTH_ACTIVE: 'true'
        N8N_BASIC_AUTH_USER: ${N8NUSER}
        N8N_BASIC_AUTH_PASSWORD: ${N8NPASSWORD}
        N8N_HOST: n8n.${DOMAINNAME}
    volumes:
    ...
```

**Comment by janober** [comment]
Sorry, do not totally understand what you mean. The first one works but the second one not? If that is correct, can you please tell me the exact differences that I do not have to spend a lot of time comparing each line and each letter and so also maybe overlook something. And if my assumption is correct, can you please also tell me if the first example really works as intended, so if it really uses all the defined environment variables.
Because without comparing everything now letter by letter I would say in the first example it probably uses "sqlite" as you have two "environment" blocks defined and so the second overwrites the first.

**Comment by jwillmer** [comment]
The only change is that I have defined the `environment` twice. Both, db access and basic auth works in the first docker-compose file. In the second n8n throws an internal exception that it can't find (or access) the database.

**Comment by janober** [comment]
To echo again what I wrote before. Are you sure that it actually uses MongoDB with the first Dockerfile and not SQLite? So if you save a workflow does it have the id "1" or something like "507f1f77bcf86cd799439011"?

**Comment by janober** [comment]
So to make it even clearer. I think that this environment block:
```
    environment:
        DB_TYPE: mongodb
        DB_MONGODB_CONNECTION_URL: mongodb://${MONGOROOTUSER}:${MONGOROOTPW}@db:27017/n8n            
```
does get totally overwritten by this one:
```
    environment:
        N8N_BASIC_AUTH_ACTIVE: 'true'
        N8N_BASIC_AUTH_USER: ${N8NUSER}
        N8N_BASIC_AUTH_PASSWORD: ${N8NPASSWORD}
        N8N_HOST: n8n.${DOMAINNAME}
```
Meaning it uses instead of Mongo actually SQLite. And for that reason does the first example work. Because even though there is apparently an issue with your Mongo-Setup it does not throw an error as it does not get used.
