### ISSUE TITLE
Local docker webhook 404 not found

### ISSUE THREAD

**Issue by maximegel** [n8n-io/n8n#2443]
**Describe the bug**

While using n8n from my local Docker environment running on a Windows 10, I'm unable to receive a response other than 404 (Not found) from the Webhook trigger node.

I'm invoking the Webhook from Postman and I already checked that the HTTP verb match, the workflow is active and tested with both the test and production URL.

**To Reproduce**
  1. Run `docker-compose up` with the following config:

```yml
version: '3.9'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - 5678:5678
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  n8n-data:
```

2. Add a Webhook node
3. Execute node
4. Send HTTP request with Postman, curl, or another HTTP client
5. See 404 error response

**Expected behavior**
The node should respond with success.

**Environment (please complete the following information):**
 - OS: Docker on Windows 10
 - n8n Version: 0.148.0
 - Node.js Version: N/A (same as Docker image)
 - Database system: SQLite
 - Operation mode: Own
