### ISSUE TITLE
Problems with special characters in Unicode

### ISSUE THREAD

**Issue by ericfischerbav** [n8n-io/n8n#2748]
**Describe the bug**
I'm trying to use data from the website finanzen.net in my workflows. There, special characters are marked with the HTML unicode format. In N8N, only questions marks are shown for these characters. The page uses an UTF-8 HTML-file formatting.

This happens in the RSS Feed node as well as though the HTTP Request and HTML Extract nodes.

**To Reproduce**
Use this workflow to see the result:
```
{
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        280,
        0
      ]
    },
    {
      "parameters": {
        "url": "https://www.finanzen.net/rss/news"
      },
      "name": "RSS Feed Read1",
      "type": "n8n-nodes-base.rssFeedRead",
      "typeVersion": 1,
      "position": [
        520,
        0
      ]
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "RSS Feed Read1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

**Expected behavior**
HTML-Unicode characters are replaces with the UTF-8 characters.

**Environment (please complete the following information):**
From my docker compose file:
```
  automation:
    image: n8nio/n8n:0.158.0
    restart: always
    volumes:
      - ./data/automation/system:/home/node/.n8n
    env_file:
      - config/automation.env
    environment:
      - DB_TYPE=mariadb
      - DB_MYSQLDB_HOST=automation-db
      - DB_MYSQLDB_PORT=3306
      - GENERIC_TIMEZONE=Europe/Berlin
    depends_on:
      automation-db:
        condition: service_healthy
    networks:
      - automation
      - database

  automation-db:
    image: mariadb:10.6.4-focal
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./data/automation/db:/var/lib/mysql
    env_file:
      - config/automation.env
    networks:
      - automation
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
```

* Edited due to wrong code formatting
