### ISSUE TITLE
Webhooks not displaying data or not stopping executing.

### ISSUE THREAD

**Issue by ebecaf** [n8n-io/n8n#2830]
**Describe the bug**
There are two issues:
1) Executions will not stop when manually executed.
2) The more major issue is that even though the execution is 'executed' (data goes through) none of it is seen when using test webhooks and because the workflow doesn't end, I never see any data come in and the workflow doesn't visibly execute.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run n8n in Docker, on Postgres 14, with at least v0.161.1
2. Create webhook
2. Manually execute
3. Send data to test webhook
4. See error (or nothing...)

**Expected behaviour**
Before this (when I installed with v0.159.1), workflows would execute and show data when manually executed, or at least stop when the 'stop' icon was clicked. Now, only a page refresh will stop a manual execution and no data is displayed so I can't get values from previous nodes to build a workflow (using data via expressions).

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 21.10
 - n8n Version: 0.163.1
 - Node.js Version: Docker (unknown)
 - Database system: Postgres 14
 - Operation mode: own

**Additional context**
~~EXECUTIONS_PROCESS is set to `main` since reporting this issue.~~ Changed back to `own` almost immediately. 

I should note that this has happened before and I had to completely re-install n8n. I did not expect this to be happening again a few versions later. Could this be Postgres? Or perhaps the fact it's running in Docker?

Side note; what version of Postgres _should_ I be using?

**Comment by ebecaf** [comment]
To update this, I created a new/ second install of n8n with the only change to Postgres 13.6, and with 0.163.1, still webhooks are not registering and data is just passing through with the workflow stuck spinning even after clicking the 'stop' button.

**Comment by Joffcom** [comment]
Hey @ebecaf,

I have not seen any mentions of this yet on the community support forum which is odd, Do you happen to have an example compose file that reproduces the issue? I am not seeing it on the 3 instances I run but none of them are using Postgres so it could be something odd when using Postgtres.

If you go back to 159.1 does it start working again?

**Comment by ebecaf** [comment]
Hi,
> If you go back to 159.1 does it start working again?
Yes.

**Comment by rishi003** [comment]
> Hey @ebecaf,
> 
> I have not seen any mentions of this yet on the community support forum which is odd, Do you happen to have an example compose file that reproduces the issue? I am not seeing it on the 3 instances I run but none of them are using Postgres so it could be something odd when using Postgtres.
> 
> If you go back to 159.1 does it start working again?

I tried to reproduce the issue with the below compose file but it was working fine. @ebecaf please check out the below file and let me know if I am heading in the right direction.

```yml
version: '3.1'

services:

  pgsql:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - ./n8n-pgdata:/var/lib/postgresql/data
  
  n8n:
    image: n8nio/n8n:0.161.1
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=pgsql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
    ports:
      - 5678:5678
    links:
      - pgsql
    volumes:
      - ~/.n8n:/home/node/.n8n
    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 5; n8n start"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8123:8080

volumes:
  n8n-pgdata:
```
