### ISSUE TITLE
Command sleep not found

### ISSUE THREAD

**Issue by YarmoM** [n8n-io/n8n#309]
**Describe the bug**
When starting the n8n docker container, it immediately stops with the following message:
```
n8n_1                        | The command "-c" is not known!
n8n_1                        | 
n8n_1                        |  ›   Error: command sleep not found
```

**To Reproduce**
1. Copy the docker-compose.yaml from this repo
2. Execute `docker-compose up -d`
3. See error via logs `docker-compose logs n8n`

**Expected behavior**
It should just start, like it did about a week ago.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - n8n Version: 0.53.0
 - Node.js Version: 10.4.1 (of system, unsure about what version inside container)

**Additional context**
It worked about a week ago, I have searched the github issues for a couple of days now but can't find anyone else having this issue.

I use n8n together with mongo. docker-compose.yaml:

```
  n8n_db:
    image: mongo:4.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_USERNAME
      - MONGO_NON_ROOT_PASSWORD
    volumes:
      - ./n8n_init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
      - ${PATH_DATA_APPS}/n8n/db:/data/db

  n8n:
    image: n8nio/n8n
    environment:
      - GENERIC_TIMEZONE="Europe/Amsterdam"
      - DB_TYPE=mongodb
      - DB_MONGODB_CONNECTION_URL=mongodb://${MONGO_NON_ROOT_USERNAME}:${MONGO_NON_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=n8n.domain.com
      - N8N_PROTOCOL=https
      - WEBHOOK_TUNNEL_URL=https://n8n.domain.com/
      - VUE_APP_URL_BASE_API=https://n8n.domain.com/
    links:
      - n8n_db:mongo
    volumes:
      - ${PATH_DATA_APPS}/n8n/config:/root/.n8n
    command: /bin/sh -c "sleep 5; n8n start"
    labels:
      - "traefik.frontend.rule=Host:n8n.domain.com"
      - "traefik.port=5678"
```
