### ISSUE TITLE
Using a $ or ^in a mysql password fails a mysql connection via docker-compose

### ISSUE THREAD

**Issue by rowanfuchs** [n8n-io/n8n#3116]
I was bumping into the following error when I used a mysql connection within a docker compose:

```
Stopping n8n...,
Initializing n8n process,
There was an error initializing DB: "Access denied for user 'dsp_n8n'@'XX-XXX-XXX-XX.fixed.kpn.net' (using password: YES)",
```

Use the following configuration to reproduce:
```
version: "3.1"

services:
  n8n:
    container_name: n8n
    image: n8nio/n8n
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${BASIC_USERNAME}
      - N8N_BASIC_AUTH_PASSWORD=${BASIC_PASSWORD}
      - DB_TYPE=mariadb
      - DB_MYSQLDB_DATABASE=${DB_MYSQLDB_DATABASE}
      - DB_MYSQLDB_HOST=${DB_MYSQLDB_HOST}
      - DB_MYSQLDB_PORT=${DB_MYSQLDB_PORT}
      - DB_MYSQLDB_USER=${DB_MYSQLDB_USER}
      - DB_MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}
    ports:
      - "5678:5678"
    volumes:
      - /config/n8n/.n8n:/home/node/.n8n
      - /config/n8n/files:/files
```
Make sure the password contains special characters like a & and ^
Which should result in the above mentioned error.

forum post
https://community.n8n.io/t/mysql-connection-issue-with-remote-sql/13022
