### ISSUE TITLE
Docker-compose: MariaDB/MySQL communication issues

### ISSUE THREAD

**Issue by pablorq** [n8n-io/n8n#3138]
**Describe the bug**
In a docker-compose stack with 2 containers (n8n & db), the database (db) container receives incorrect packets from n8n app.

The error shown in the log is:
```
[Note] Aborted connection xx to db: 'n8n' user: 'root' host: 'x.x.x.x' (Got an error reading communication packets)
```

From the n8n app container log:
```
There was an error initializing DB: "connect ECONNREFUSED x.x.x.x:3306"
```

As a result, the n8n service doesn't work.

Tested with MariaDB and MySQL databases.

**To Reproduce**
1. Create a docker-compose file or use Portainer Editor (my case):
```
version: '3.1'

services:
  db:
    image: mariadb:10.7
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=mysecretpassword
      - MARIADB_DATABASE=n8n

  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=mariadb
      - DB_MYSQLDB_HOST=db
      - DB_MYSQLDB_DATABASE=n8n
      - DB_MYSQLDB_USER=root
      - DB_MYSQLDB_PASSWORD=mysecretpassword

    depends_on:
      - db
```
2. Run the stack
3. Check logs

**Expected behavior**
It is to get the first run web page.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 21.10
 - n8n Version: 0.172.0
 - Database system: MariaDB, MySQL
