### ISSUE TITLE
'Started at' timezone gets mixed in the executions view

### ISSUE THREAD

**Issue by rafalkrupinski** [n8n-io/n8n#3855]
**Describe the bug**
When one flow calls another, the task execution view shows that the triggered task was called 2 hours before or after the triggering task

**To Reproduce**
1. Running n8n server with both     TZ and  GENERIC_TIMEZONE=Europe/Vienna
2. prepare a simple flow
3. prepare another flow, triggering the flow from the step 2.

**Expected behavior**
The execution time of flows should be seconds apart

**Environment (please complete the following information):**
 - n8n Version 168.1

**Additional context**
![image](https://user-images.githubusercontent.com/3732079/183388798-058467c7-29ee-4d2d-b465-19ac63051a1e.png)

Also in some cases a task trigger by cron node will show execution time 2hrs earlier then the actual execution

**Comment by Joffcom** [comment]
Hey @rafalkrupinski,

What is your workflow doing and have you tried on a newer release? I have just given it a quick go here and I am seeing what I would expect, does it actually run the workflow when it is meant to?

![image](https://user-images.githubusercontent.com/4688521/184099685-47353a2d-f140-4a15-abe5-feec36bba4d5.png)

**Comment by rafalkrupinski** [comment]
> What is your workflow doing 

I just run a very simple workflow even without a call to another one and the time is wrong.
It's querying Airtable for a single value and making two HTTP requests querying for some simple data - API version and current account.

> and have you tried on a newer release?

Yes, since I made the report I've updated to 0.189.1

> I have just given it a quick go here and I am seeing what I would expect, does it actually run the workflow when it is meant to?

I just run it manually and the time is 2hrs back.

Sorry, I forgot to mention I'm running it in Docker from a custom image based on the official one:

```Dockerfile
FROM n8nio/n8n:0.189.1

RUN npm_config_user=root npm install -g date-fns date-fns-tz nanoid
```
docker compose
```yaml
  n8n-dev:
    build: ...
    environment:
    - DB_POSTGRESDB_DATABASE=...
    - DB_POSTGRESDB_HOST=...
    - DB_POSTGRESDB_PASSWORD=...
    - DB_POSTGRESDB_USER=...
    - DB_TYPE=postgresdb
    - GENERIC_TIMEZONE=Europe/Vienna
    - N8N_BASIC_AUTH_ACTIVE=true
    - N8N_BASIC_AUTH_USER=...
    - N8N_BASIC_AUTH_PASSWORD=...
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_ENCRYPTION_KEY=...
    - N8N_HOST=...
    - N8N_METRICS=true
    - N8N_VERSION_NOTIFICATIONS_ENABLED=false
    - NODE_FUNCTION_ALLOW_EXTERNAL=date-fns,date-fns-tz,nanoid
    - NODE_FUNCTION_ALLOW_BUILTIN=crypto
    - TZ=Europe/Vienna
    - WEBHOOK_URL=...
    - NODE_ENV=production

    - N8N_LOG_LEVEL=debug
```
