### ISSUE TITLE
N8N interface keeps staying on Executing node... and loosing connection sometimes on Digital Ocean's app platform

### ISSUE THREAD

**Issue by matthijs166** [n8n-io/n8n#4162]
**Describe the bug**
I can't execute the workflow to test in the frontend interface.
It keeps loading.
Every workflow I create has this problem, no matter the configuration.

![2022-09-21 18_13_47-n8n - 🔄 My workflow 2](https://user-images.githubusercontent.com/31346561/191556677-f46b26c3-d693-4509-8803-0c8525ace51b.png)

**To Reproduce**

1. Create an app in Digital Ocean
2. Create a resource from a docker image (n8nio/n8n)
3. Setup the env and add domain
4. Wait for a build
5. Open n8n and register
6. Create the first workflow and click on execute workflow
7. Workflow stays loading

**Expected behavior**
- To let the workflow run on digital ocean
- Give a clear error if it doesn't work
- A timeout with an error instead of waiting forever

**Environment (please complete the following information):**
- Digital Ocean
- Docker version latest
- Database system [SQLite]
- In the env file I have set N8N_HOST WEBHOOK_URL WEBHOOK_TUNNEL_URL VUE_APP_URL_BASE_API N8N_EDITOR_BASE_URL

**Additional context**
When I run the docker image local everything works

**Comment by Joffcom** [comment]
Hi @matthijs166, 

Thanks for reporting this one, I suspect this is not a bug as such and is more than likely going to be a configuration issue. Are you just using the  docker image or are you also using a reverse proxy and something like Cloudflare?

**Comment by matthijs166** [comment]
Hi @Joffcom,

It's indeed just the docker container. And I also suspect it to be a configuration issue.
Have used it with and without Cloudflare and it works on a VPS with Cloudflare.

I also find this issue #959

Think it has something to do with EventSource...
But if it does there should be a clear error.

Also, the future is cloud and it is annoying that n8n cant is deployed on Digital Oceans app platform.
You cant configure the reverse proxy (what I imagen also the case on other cloud app providers)

The thing is it should work right out of the box right?

**Comment by Joffcom** [comment]
Hey @matthijs166,

It should work fine on Digital Ocean I have an instance there myself and have used it previously with nginx, Caddy and Traefik with no issues, Are you using a reverse proxy and what environment options do you have set (and what are the values)?

If you check the browser console do you see any error messages?

**Comment by matthijs166** [comment]
Hey @Joffcom,

I also have it running on a droplet with an NGINX proxy in front.
And got it working locally without proxy.
But I need to run it on the app platform. (it's going to be part of a serverless infrastructure)

![2022-09-21 18_44_19-king-prawn-app - DigitalOcean App Platform](https://user-images.githubusercontent.com/31346561/191563568-626fb9db-700a-414c-8c1c-d6ee1ec37e9a.png)

**Comment by Joffcom** [comment]
Hey @matthijs166,

Perfect, the last few of these it was down to the nginx config. Can you share the config block for the proxy section.

**Comment by matthijs166** [comment]
Hey @Joffcom

Sorry for the wait but here is my digital ocean spec file.
All the settings of the app. You can also use this for reproducing the issue.

```
name: starfish-app
region: ams
services:
- envs:
  - key: N8N_HOST
    scope: RUN_AND_BUILD_TIME
    value: xxxxxxx.ondigitalocean.app
  - key: WEBHOOK_URL
    scope: RUN_AND_BUILD_TIME
    value: https://xxxxxxx.ondigitalocean.app
  - key: WEBHOOK_TUNNEL_URL
    scope: RUN_AND_BUILD_TIME
    value: https://xxxxxxx.ondigitalocean.app
  - key: VUE_APP_URL_BASE_API
    scope: RUN_AND_BUILD_TIME
    value: https://xxxxxxx.ondigitalocean.app
  - key: N8N_EDITOR_BASE_URL
    scope: RUN_AND_BUILD_TIME
    value: https://xxxxxxx.ondigitalocean.app
  http_port: 5678
  image:
    registry: n8nio
    registry_type: DOCKER_HUB
    repository: n8n
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  name: n-8-nio-n-8-n
  routes:
  - path: /
```
