### ISSUE TITLE
Workflow can not be enabled using command line

### ISSUE THREAD

**Issue by smalot** [n8n-io/n8n#4753]
**Describe the bug**

The command line fail to enable workflow using 'update:workflow'.

**To Reproduce**

1. Create a workflow with a webhook trigger
2. Enable this workflow with UI
3. Disable workflow with command line : `docker-compose exec n8n n8n update:workflow --all --active=false` (response is : Deactivating all workflows)
4. Check status in UI : workflow is disabled
5. Enable workflow with command line : `docker-compose exec n8n n8n update:workflow --all --active=true` (response is : Deactivating all workflows)
6. Check status in UI : workflow is still disabled

The result is the same when using `--id=1` instead of `--all`.

**Expected behavior**

Workflow should be activated with `update:workflow --all --active=true` as done with UI.

**Environment (please complete the following information):**

- OS: docker
- n8n Version : 0.203.1
- Node.js Version : v16.17.0]
- Database system : SQLite
- Operation mode : own

**Additional context**

**Comment by Joffcom** [comment]
Hey @smalot,

I have just given this a go and while the command does come back and say `deactiving workflow with ID: xx` it looks like it has enabled the workflow.

In your testing did it fail with all workflows or just ones with certain triggers?

**Comment by smalot** [comment]
Hi @Joffcom 

However I don't care about command line feedback, the workflow is not enabled.
Only the disable is applied.

BR

**Comment by Joffcom** [comment]
Hey @smalot,

Did it fail with all workflows or just ones with certain triggers? The feedback message didn't matter but I was unable to reproduce.

**Comment by smalot** [comment]
Hi @Joffcom 

Indeed, it works with the `--id=[id]` specified, but not with the `--all` flag.

Here a sample code to reproduce

```
version: "3.3"
services:
  n8n:
    image: n8nio/n8n:0.204.0
    environment:
      - N8N_ENCRYPTION_KEY=qa
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_HOST=mysql
      - DB_MYSQLDB_USER=root
      - DB_MYSQLDB_PASSWORD=root
      - DB_MYSQLDB_DATABASE=n8n
    ports:
      - "5678:5678"
    links:
      - mysql:mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=n8n
      - MYSQL_PASSWORD=n8n
      - MYSQL_DATABASE=n8n
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5-apache
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql:mysql
    ports:
      - "9000:80"
```

Step 1 : launch docker

```
docker-compose up -d mysql
sleep 30
docker-compose up -d
```

Step 2

create a workflow with the `webhook trigger` node

Step 3

```
docker-compose exec n8n n8n update:workflow --all --active=true
```

However, if you active the workflow manually using the UI, the following command line works to disable it:

```
docker-compose exec n8n n8n update:workflow --all --active=false
```

BR
