### ISSUE TITLE
MongoDB cannot connect on latest version of n8n (but works with older version)

### ISSUE THREAD

**Issue by kimus** [n8n-io/n8n#4886]
**Describe the bug**
After upgrading my docker container to ‘latest’ version (0.206.1) of n8n the MongoDB connections stopped to work.
And with an older version (0.173.1) works fine.

![image](https://user-images.githubusercontent.com/188404/206936392-69a86449-2b94-4ff2-a888-4245292fb347.png)
It seams that it's ignoring my setting and trying to connect to the local `docker-compose` network?? Even the port is the 'default' and not what I've provided in the connection url.

**To Reproduce**
Not sure why it’s getting the error, when the connections string is not the provided.
I’m using something like: `mongodb://user:pass@db02.s.example.com:27018/db-prd?authSource=admin&readPreference=secondary`

**Expected behavior**
Should connect has normal. Like older versions does.

**Environment (please complete the following information):**

- OS: Docker
- n8n Version: 0.206.1
- Database system: MongoDB
- Operation mode: own

**Comment by luizeof** [comment]
@Joffcom same here ... doesn't work with connection string or values

**Comment by netroy** [comment]
Are you able to add and test new credentials?

**Comment by kimus** [comment]
@netroy  Adding or editing an existing one will give me the same error:
```
Couldn’t connect with these settings 
connect ECONNREFUSED 192.168.149.173:27017
```

**Comment by kimus** [comment]
So, I've found out that `192.168.149.173:27017` is the primary member of the replica set.

It's an internal server, so, it should not be reached directly and should not connect.

Strangely, if I do a `docker-compose exec n8n /bin/sh`and do:
```bash
> cd /usr/local/lib/node_modules/n8n
> MONGO_URI='... same connection string ... ' node

const { MongoClient } = require('mongodb');
const uri = process.env.MONGO_URI;
const client = new MongoClient(uri);
await client.connect();
await client.db().admin().listDatabases();
await client.db().collection('User').find({ username: /^teste/}).limit(1).toArray()
```

it works fine :-(

**Comment by Joffcom** [comment]
Hey @kimus & @luizeof,

How do you both have MongoDB running and what version are you using? I have did a quick test yesterday and it is working for me on `0.206.1` with MDB `5.0.6` running in Docker. The string I have used is the one that Compass built out for me.

![image](https://user-images.githubusercontent.com/4688521/207274447-0edcb0d3-14fc-40c9-b09b-49b10dde2ce3.png)

Based on what is in here already it could be something in the connection string that needs to be updated but if we can reproduce it we will be able to work out the fix for it.

**Comment by kimus** [comment]
Hi @Joffcom ,

The problem is related with this being a replicaSet. and not a normal MongoDB instance.
And so, I could describe my setup:
- a replica set with several MongoDB members (primary and secondary) v4.0
- this replica set is behind a firewall in a private network (so you can't directly access members by the private ips)
- a connection string that has the [read preference](https://www.mongodb.com/docs/manual/core/read-preference/) set to `secondary` - so it should only connect to the secondary member

The connection string is something like:
`mongodb://user:pass@secondary.public.io:27018/?authSource=admin&readPreference=secondary`
The replica set is configured with the following members (all in a private network):
```javascript
[
    "db01.private.io:27017",	// primary
    "db02.private.io:27018",	// secondary
    "db03.private.io:27018"	// arbiter
]
```

So, the secondary member (`secondary.public.io`) has an public ip and the port `27018` is opened. And it works fine with the `mongodb` driver v3 but not with v4.

**Comment by netroy** [comment]
> So, in `/usr/local/lib/node_modules/n8n` there is a different `mongodb` package version:
> 
> ```shell
> > grep '"version":' node_modules/mongodb/package.json
>   "version": "3.7.3",
> ```
> 
> Then in `/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base`:
> 
> ```shell
> > grep '"version":' node_modules/mongodb/package.json
>   "version": "4.12.1",
> ```

The 3.x version of the mongodb is being pulled in by `typeorm`, but it's not being used in the MongoDB node. 

> So it's an connection error related with the latest version of mongodb package.

Yeah, my suspicion is that somehow the older format of your connection string isn't compatible with the 4.x mongodb driver, just as you said.

**Comment by Joffcom** [comment]
Hey @kimus,

Could you try the below (add `+srv`) and let me know if it works? I set up an Atlas instance and if I don't include that one part it won't connect.

```mongodb+srv://user:pass@secondary.public.io:27018/?authSource=admin&readPreference=secondary```

**Comment by kimus** [comment]
@Joffcom, can you test this?

```yaml
version: "3"

services:
  mongo-primary:
    image: bitnami/mongodb:4.0
    restart: always
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongo-primary
      - MONGODB_REPLICA_SET_KEY=repls0
      - MONGODB_ROOT_PASSWORD=s3cr3tp4ss

  mongo-secondary:
    image: bitnami/mongodb:4.0
    depends_on:
          - mongo-primary
    ports:
      - "27018:27017"
    restart: always
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_ADVERTISED_HOSTNAME=mongo-secondary
      - MONGODB_REPLICA_SET_KEY=repls0
      - MONGODB_INITIAL_PRIMARY_HOST=mongo-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=s3cr3tp4ss

  mongo-arbiter:
    image: bitnami/mongodb:4.0
    depends_on:
      - mongo-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_ADVERTISED_HOSTNAME=mongo-arbiter
      - MONGODB_REPLICA_SET_KEY=repls0
      - MONGODB_INITIAL_PRIMARY_HOST=mongo-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=s3cr3tp4ss

volumes:
  mongodb_master_data:
    driver: local
```
