### ISSUE TITLE
N8n queue mode fails to execure some workflows

### ISSUE THREAD

**Issue by MartinsVi** [n8n-io/n8n#5086]
**Describe the bug**
Running n8n in queue mode with `N8N_USER_MANAGEMENT_DISABLED=true` causes workflows, that call/execute other workflows to fail with following error `Error: cannot find configuration param 'userManagement.isInstanceOwnerSetUp'`

**To Reproduce**
1. docker-compose.yaml
```
version: '3.8'

services:

  n8n:
    image: n8nio/n8n:0.209.0
    restart: always
    environment:
      - DB_LOGGING_MAX_EXECUTION_TIME=0
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=dbrootpassword
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=dbroot
      - DB_TYPE=postgresdb
      - EXECUTIONS_MODE=queue
      - EXECUTIONS_PROCESS=main
      - N8N_ENCRYPTION_KEY=n8nencryptionkey
      - N8N_LOG_LEVEL=info
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - QUEUE_BULL_REDIS_DB=0
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
    ports:
      - 5678:5678
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - postgres
      - redis
    volumes:
      - ./appdata-main:/home/node/.n8n
    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 5; n8n start"

  n8n-worker:
    image: n8nio/n8n:0.209.0
    restart: always
    environment:
      - DB_LOGGING_MAX_EXECUTION_TIME=0
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=dbrootpassword
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=dbroot
      - DB_TYPE=postgresdb
      - EXECUTIONS_MODE=queue
      - EXECUTIONS_PROCESS=main
      - N8N_ENCRYPTION_KEY=n8nencryptionkey
      - N8N_LOG_LEVEL=error
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - QUEUE_BULL_REDIS_DB=0
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_HEALTH_CHECK_ACTIVE=true
    ports:
      - 5679:5678
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./appdata-worker:/home/node/.n8n
    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 5; n8n worker"

  redis:
    ports:
      - 6379:6379
    image: redis:alpine

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=dbroot
      - POSTGRES_PASSWORD=dbrootpassword
      - POSTGRES_DB=n8n
      - POSTGRES_NON_ROOT_USER=dbuser
      - POSTGRES_NON_ROOT_PASSWORD=dbpassword
    ports:
      - 5432:5432
```

2. Create "Very quickstart quickstart" workflow and add "Execute Workflow Trigger" node
![image](https://user-images.githubusercontent.com/47249890/210600766-612a27a6-9ab5-44fd-b3af-756d995c87fa.png)
3. Create "My workflow" workflow that calls Quickstart workflow (created on step 1.) on some schedule
![image](https://user-images.githubusercontent.com/47249890/210600966-5991a551-92bd-46e0-b940-9e565edea8a8.png)
4. Wait for workflows to start executing and open any "My workflow"
![image](https://user-images.githubusercontent.com/47249890/210602118-3a77df77-f5ae-4f10-ac66-4fc8bea394df.png)
5. Open "My workflow" -> "Execute Workflow" node to see the error message
![image](https://user-images.githubusercontent.com/47249890/210605032-a9385fb0-c4fc-47ad-b0f4-ecd768f6e098.png)
```
Error: cannot find configuration param 'userManagement.isInstanceOwnerSetUp'
    at walk (/usr/local/lib/node_modules/n8n/node_modules/convict/src/main.js:453:15)
    at Object.get (/usr/local/lib/node_modules/n8n/node_modules/convict/src/main.js:528:17)
    at isUserManagementEnabled (/usr/local/lib/node_modules/n8n/dist/UserManagement/UserManagementHelper.js:58:26)
    at isSharingEnabled (/usr/local/lib/node_modules/n8n/dist/UserManagement/UserManagementHelper.js:63:13)
    at Function.checkSubworkflowExecutePolicy (/usr/local/lib/node_modules/n8n/dist/UserManagement/PermissionChecker.js:78:58)
    at Object.executeWorkflow (/usr/local/lib/node_modules/n8n/dist/WorkflowExecuteAdditionalData.js:595:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/ExecuteWorkflow/ExecuteWorkflow.node.js:159:34)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:658:28)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:585:53
```
**Expected behavior**
Workflow executes without error

**Environment (please complete the following information):**

- OS: macOS 12.4
- n8n Version: 0.209.0
- Node.js Version: v16.18.1
- Database system: PostgreSQL13
- Operation mode: queue

**Additional context**
Similar issue was reported [here](https://community.n8n.io/t/i-am-unable-to-run-queue-mode/18260), but it does not mention how to fix it.
If we remove N8N_USER_MANAGEMENT_DISABLED variable or disable queue mode all workflows execute without issues.
However, we would like to keep user management feature disabled and queue mode enabled in our environment.
