### ISSUE TITLE
Docker image doesn't support _FILE suffix format for secrets environment variables

### ISSUE THREAD

**Issue by jpwarren** [n8n-io/n8n#5184]
**Describe the bug**
The n8n image doesn't appear to support the `_FILE` suffix format of environment variables to, for example, read in secrets from a file.

Appears to have been previously reported as #1656.

**To Reproduce**

1. Define a docker-compose.yml file with secrets, similar to the following:

```
secrets:
  n8n_postgresdb_password:
    file: /path/to/secrets/file

services:
  n8n:
    image: n8nio/n8n

  secrets:
    - "n8n_postgresdb_password"

  environment:
    - DB_POSTGRES_PASSWORD_FILE=/run/secrets/n8n_postgresdb_password
```

2. Start the containers with `docker-compose -f <composefile.yml> up`
3. See error in output: `FATAL:  password authentication failed for user "n8n"`

**Expected behavior**
The environment variable `DB_POSTGRES_PASSWORD` in the container should be set to the contents of `/path/to/secrets/file`.

It should function the same as defining `DB_POSTGRES_PASSWORD` in a `.env` file or in the `docker-compose.yml` definition.

The PostgreSQL docker images support this mechanism, so there could be inspiration there for how to implement this functionality.

**Environment **

- OS: Ubuntu Linux 22.04 LTS
- n8n Version: Container image `n8nio/n8n`
- Database system: PostgreSQL
- Operation mode: own (although I haven't gotten that far yet, just trying to get the containers started)

**Additional context**
It's challenging to diagnose, as the n8n application just crashes without providing much diagnostic information to the console or logfile, even with `N8N_LOG_LEVEL=debug` set.
