### ISSUE TITLE
localhost appearing in webhook production URL with Stripe node

### ISSUE THREAD

**Issue by despens** [n8n-io/n8n#5204]
A URL containing `localhost:5678` is generated for production webhook; test URL contains correctly set up domain name.

**To Reproduce**

1. Create new workflow
2. Add new Stripe trigger node
3. Inside the node, under "Webhook URL" switch in between "Test URL" and "Production URL"
4. Test URL will contain domain name as set up via `WEBHOOK_URL` environment variable; Production URL uses localhost

**Expected behavior**
The domain name set up via `WEBHOOK_URL` should be used in all instances of webhook URLs being created.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04, running n8n via docker behind nginx reverse proxy
- n8n Version n8nio/n8n:0.212.0
- Database system: Postgresql 14
- Operation mode `own`

**Comment by Joffcom** [comment]
Hey @despens 

Have you tried setting `WEBHOOK_URL`? The editor url in some cases can be different to the webhook url.

**Comment by despens** [comment]
Hello @Joffcom, yes `WEBHOOK_URL` is set. I will update the original issue accordingly.
Further experimentation now revealed that the Stripe node seems to generate the Production URL from `N8N_PROTOCOL`, `N8N_HOST`, and `N8N_PORT` environment variables. Unfortunately it is not possible to set these in a way that would make n8n work behind a reverse proxy, as `N8N_PORT` is also used to define the port the UI is served from. So if I set that variable to `443`, n8n would listen to connections on `0.0.0.0:443` which won't work, as the outside nginx refuses to proxy plain http requests to that port.

**Comment by Joffcom** [comment]
Hey @despens,

That sounds odd, I have `WEBHOOK_URL` set on my home instance and I have both Production and Test URLs using that domain. Can you share your full config so I can take a look?

**Comment by despens** [comment]
Thank you so much for checking @Joffcom, here is the anonymized conf:

<details><summary>docker-compose.yaml</summary>

```yaml
version: '3.1'
services:
  n8n:
    image: n8nio/n8n:0.212.0
    restart: always
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=https
      - N8N_PORT=443
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - VUE_APP_URL_BASE_API=${N8N_EDITOR_BASE_URL}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_PAYLOAD_SIZE_MAX=128
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
    ports:
      - 5678:5678
    extra_hosts:
      postgres: x
    volumes:
      - ./n8n_data:/home/node/.n8n
    command: /bin/sh -c "n8n start"
```

</details>

<details><summary>.env</summary>

```bash
N8N_HOST=n8n.mydomain.info
N8N_EDITOR_BASE_URL=https://n8n.mydomain.info/
WEBHOOK_URL=https://n8n.mydomain.info/


POSTGRES_USER=x
POSTGRES_PASSWORD=x
POSTGRES_DB=x

POSTGRES_NON_ROOT_USER=x
POSTGRES_NON_ROOT_PASSWORD=x

N8N_BASIC_AUTH_USER=x
N8N_BASIC_AUTH_PASSWORD=x
```
</details>
