### ISSUE TITLE
error when set N8N_CONFIG_FILES env

### ISSUE THREAD

**Issue by Yoshino-s** [n8n-io/n8n#5318]
**Describe the bug**
When set N8N_CONFIG_FILES and run n8n instance, an error will reported

```
n8n  | module: @oclif/config@1.18.5
n8n  | task: toCached
n8n  | plugin: n8n
n8n  | root: /usr/local/lib/node_modules/n8n/packages/cli
n8n  | See more details with DEBUG=*
n8n  | (node:8) Error Plugin: n8n: LoggerProxy not initialized
n8n  | module: @oclif/config@1.18.5
n8n  | task: toCached
n8n  | plugin: n8n
n8n  | root: /usr/local/lib/node_modules/n8n/packages/cli
n8n  | See more details with DEBUG=*
n8n  | Error Plugin: n8n: LoggerProxy not initialized
n8n  |     at getInstance (/usr/local/lib/node_modules/n8n/packages/workflow/dist/LoggerProxy.js:11:15)
n8n  |     at Object.debug (/usr/local/lib/node_modules/n8n/packages/workflow/dist/LoggerProxy.js:21:5)
n8n  |     at Object.<anonymous> (/usr/local/lib/node_modules/n8n/packages/cli/dist/config/index.js:40:36)
n8n  |     at Module._compile (node:internal/modules/cjs/loader:1165:14)
n8n  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
n8n  |     at Module.load (node:internal/modules/cjs/loader:1043:32)
n8n  |     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
n8n  |     at Module.require (node:internal/modules/cjs/loader:1067:19)
n8n  |     at require (node:internal/modules/cjs/helpers:103:18)
n8n  |     at Object.<anonymous> (/usr/local/lib/node_modules/n8n/packages/cli/dist/Db.js:8:34)
```

**To Reproduce**
using follow docker-compose.yml

```yml
version: "3"
services:
  n8n:
    image: n8nio/n8n:nightly
    container_name: n8n
    restart: always
    environment:
      - DEBUG=*
      - N8N_CONFIG_FILES=/etc/n8n/config.json
```

See error

- OS: Debian 10.2.1-6
- n8n Version: nightly
- Node.js Version 16.19.0
- Database system SQLite
- Operation mode own
