### ISSUE TITLE
n8nio/n8n:latest-debian still doesn't work on ARM

### ISSUE THREAD

**Issue by SurPaul** [n8n-io/n8n#5462]
`n8nio/n8n:latest-debian` still doesn't work on ARM.

_Originally posted by @SurPaul in https://github.com/n8n-io/n8n/issues/5164#issuecomment-1427061649_

**Comment by SurPaul** [comment]
I keep using `n8nio/n8n:0.204.0-debian`.

**Comment by Joffcom** [comment]
Hey @SurPaul 

Can you complete the template we provide?

Would be handy to know what error you are seeing and what ARM cpu you are using.

**Comment by SurPaul** [comment]
@Joffcom, almost everything is the same as the author #5164. Raspberry Pi 4 (arm64), but I don't use Portainer. Right now I'm running n8n using Docker Compose:

```yml
n8n:
    container_name: n8n
    environment:
        # ...
    image: n8nio/n8n:0.204.0-debian
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./n8n:/home/node/.n8n
```

If I upgrade from `n8nio/n8n:0.204.0-debian` to `n8nio/n8n:latest-debian` an error occurs:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /docker-entrypoint.sh: exec format error
```
