### ISSUE TITLE
Edit Image node fails with "ERROR: Stream yields empty buffer"

### ISSUE THREAD

**Issue by Nurgak** [n8n-io/n8n#5569]
**Describe the bug**
When executing the `Edit Image` node, no matter what operation (blur, crop, draw...) it gives the error `ERROR: Stream yields empty buffer`.

```
Stack

Error: Stream yields empty buffer
    at Socket.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/gm/lib/command.js:56:21)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**To Reproduce**
1. Input an image (I read something form the filesystem).
2. Pass the image data to the Edit Image node.
3. See error.

**Expected behavior**
I expect the correct image editing operation to be performed, without error.

**Environment (please complete the following information):**
- OS: [e.g. Ubuntu Linux 22.04]: Mac OS 12.6.1, in Docker
- n8n Version [e.g. 0.200.1]: 0.217.0
- Node.js Version [e.g. 16.17.0]: 16.19.1
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]: SQLite
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]: queue

**Additional context**
Only tested in manually executed workflow.

**Comment by Joffcom** [comment]
Hey @Nurgak,

I have just tried to reproduce this but I have not been able to, Can you try running the workflow below and let me know if it works? I also noticed in the template you have mentioned that you are using queue mode with a sqlite database which won't work, Are you sure you are using queue mode?

<details><summary>Workflow</summary>
<p>
```
{
  "meta": {
    "instanceId": "8c8c5237b8e37b006a7adce87f4369350c58e41f3ca9de16196d3197f69eabcd"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "32080cf1-13c3-4cd1-81a5-30ec7bb7462b",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        920,
        480
      ]
    },
    {
      "parameters": {
        "url": "https://imgs.search.brave.com/JPYk8wnXXZmoUZPRrUFwtSaOK3t36KUmArZrhDD_TCs/rs:fit:1024:1024:1/g:ce/aHR0cHM6Ly9zMy5h/bWF6b25hd3MuY29t/L2NyZWFyZS13ZWJz/aXRlcy13cG1zLWxl/Z2FjeS93cC1jb250/ZW50L3VwbG9hZHMv/c2l0ZXMvMzIvMjAx/Ni8wMy8wMTIwMDk1/OS9jYW5zdG9ja3Bo/b3RvMjI0MDI1MjMt/YXJjb3MtY3JlYXRv/ci5jb21fLTEwMjR4/MTAyNC5qcGc",
        "options": {}
      },
      "id": "d7c5a008-ca2e-46eb-9a86-859e4edad80a",
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        1120,
        480
      ]
    },
    {
      "parameters": {
        "operation": "blur",
        "options": {}
      },
      "id": "41c729ba-a6c4-41de-9ca7-c793788092e5",
      "name": "Edit Image",
      "type": "n8n-nodes-base.editImage",
      "typeVersion": 1,
      "position": [
        1300,
        480
      ]
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "HTTP Request": {
      "main": [
        [
          {
            "node": "Edit Image",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```
</p>
</details>

**Comment by Nurgak** [comment]
Hi @Joffcom 

Thank you for checking. I tried your workflow and it gives me the same error message. I pulled the latest n8n image (0.217.2) and still have the same issue.

Regarding the queue mode with sqlite setup: I was trying out the scaling features of n8n and got stuck in getting a database container to spin up (some configuration error), it's an unrelated problem. However, as I'm only executing workflows manually right now I have not had any issues, as everything is executed in the main n8n instance, instead of the worker instances... I guess. Thank you for noticing.

**Comment by Joffcom** [comment]
Hey @Nurgak 

You got it running manually will run it all on the same instance, can you share the config options you have set on the main instance removing any sensitive?

The node seems to be working fine in my testing so this looks to be something environmental. Which docker image are you using as well?

**Comment by Nurgak** [comment]
Hi @Joffcom 

I am building the image using the [starter node](https://github.com/n8n-io/n8n-nodes-starter).

Here's my `docker-compose.yml` file contents:
```YML
version: "3"
services:
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    networks:
      - n8n-net
  n8n-worker:
    build: .
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./configuration:/root/.n8n
    command: n8n worker --concurrency=5
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_DIAGNOSTICS_CONFIG_FRONTEND=
      - N8N_DIAGNOSTICS_CONFIG_BACKEND=
      - N8N_LOG_LEVEL=debug
      - QUEUE_BULL_REDIS_HOST=redis
    networks:
      - n8n-net
  n8n-main:
    container_name: "n8n-main"
    depends_on:
      - redis
      - n8n-worker
    build: .
    restart: unless-stopped
    ports:
      - "5678:5678/tcp"
    volumes:
      - ./configuration:/root/.n8n
      - ./samples:/samples
    environment:
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_HIDE_USAGE_PAGE=true
      - N8N_LICENSE_AUTO_RENEW_ENABLED=false
      - N8N_LICENSE_SERVER_URL=
      - N8N_DEFAULT_LOCALE=en
      - N8N_METRICS=true
      - N8N_LOG_LEVEL=debug
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_DIAGNOSTICS_CONFIG_FRONTEND=
      - N8N_DIAGNOSTICS_CONFIG_BACKEND=
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_HIRING_BANNER_ENABLED=false
      - NODE_FUNCTION_ALLOW_EXTERNAL=true
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
    networks:
      - n8n-net
networks:
  n8n-net:
```

Of course, since the workers do not have access to the database this setup will not work in production.
