### ISSUE TITLE
When verbosely referring to a previous node w/ modified output using "$node.NodeName...", non-empty value returns 'empty'

### ISSUE THREAD

**Issue by jwowk-hpne** [n8n-io/n8n#6375]
**Describe the bug**
After manually editing the output of a webhook call from FreeScout, specifically a custom field w/ my ClickUp task ID, successive nodes report the value as empty when using `{{ $node.Webhook.json.body.customFields[3].value }}`, however the value is reported properly when using `{{ $json.body.customFields[3].value }}` but this limits the user to only using the previous node.

![dZhfifCYKv](https://github.com/n8n-io/n8n/assets/107562237/445abb63-724f-4d53-af70-0931ccaf33f1)
![aS9krycH1G](https://github.com/n8n-io/n8n/assets/107562237/a8295103-c40c-477d-86ba-da9fb9594e4a)
![0vMUuluXjZ](https://github.com/n8n-io/n8n/assets/107562237/56fac9d8-2bec-4f80-9c1a-2d75541ed26b)

**To Reproduce**
1. Manually edit webhook output
2. Create an HTML to Markdown node, converting the FreeScout ticket body to md.
3. Create a "Create ClickUp Comment" node, in the "ID" field, enter expression `{{ $node.Webhook.json.body.customFields[3].value }}'
4. Value is reported as empty

**Expected behavior**
Value should be displayed properly, same as when using `{{ $json.body.customFields[3].value }}`
**Environment (please complete the following information):**

###
# Docker on an Ubuntu 22.04.2 LTS Hetzner VPS
[SMALL-2C-2G (2 VCPU s - 2 GB RAM - 40 GB storage)]
```
version: '3'
services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      N8N_BASIC_AUTH_ACTIVE: 'true'
      N8N_BASIC_AUTH_USER: xxxx
      N8N_BASIC_AUTH_PASSWORD: xxxx
      N8N_HOST: xxxx
      N8N_EMAIL_MODE: 'smtp'
      N8N_SMTP_HOST: '172.17.0.1'
      N8N_SMTP_PORT: '25'
      N8N_SMTP_USER: ' '
      N8N_SMTP_PASS: ' '
      N8N_SMTP_SENDER: 'xxxx'
      N8N_SMTP_SSL: 'false'
      WEBHOOK_URL: xxxx
    ports:
      - 172.17.0.1:5678:5678
    dns:
      - 8.8.8.8

    volumes:
      - ./.n8n:/home/node/.n8n'
```

**Additional context**
