### ISSUE TITLE
1.0.1: Invalid or unexpected token

### ISSUE THREAD

**Issue by ykorzikowski** [n8n-io/n8n#6641]
**Describe the bug**
I ttried setting up n8n with dockercompose, but I get a not well described error message: 

```
/bin/busybox:1
ELF
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1124:15)
    at Module._compile (node:internal/modules/cjs/loader:1160:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

**To Reproduce**

1. Setup n8n as described

https://github.com/n8n-io/n8n/blob/master/docker/compose/withPostgresAndWorker/docker-compose.yml

2. It will print this error message

```
root@lxc-n8n:ansible # cat /opt/docker/.n8n-secrets-env
DB_POSTGRESDB_USER=n8n
DB_POSTGRESDB_PASSWORD=****
N8N_BASIC_AUTH_USER=n8n-swokiz
N8N_BASIC_AUTH_PASSWORD=****
```

```yaml
    x-shared: &shared
      restart: always
      environment:
        DB_TYPE: postgresdb
        DB_POSTGRESDB_HOST: 10.10.10.103
        DB_POSTGRESDB_PORT: 5432
        DB_POSTGRESDB_DATABASE: n8ndb
        EXECUTIONS_MODE: queue
        QUEUE_BULL_REDIS_HOST: redis
        QUEUE_HEALTH_CHECK_ACTIVE: "true"
      links:
        - redis
      volumes:
        - /mnt/data/n8n:/home/node/.n8n
      env_file: 
        - /opt/docker/.n8n-secrets-env
      depends_on:
        redis:
          condition: service_healthy

    services:
      redis:
        image: redis:6-alpine
        restart: always
        volumes:
          - /mnt/data/redis:/data
        healthcheck:
          test: ['CMD', 'redis-cli', 'ping']
          interval: 5s
          timeout: 5s
          retries: 10

      n8n:
        <<: *shared
        image: harbor.swokiz.dev/hub-proxy/n8nio/n8n:{{ software_version.n8n }}
        command: /bin/sh -c "n8n start --tunnel"
        ports:
          - 5678:5678

      n8n-worker:
        <<: *shared
        image: harbor.swokiz.dev/hub-proxy/n8nio/n8n:{{ software_version.n8n }}
        command: /bin/sh -c "sleep 5; n8n worker"
        depends_on:
          - n8n
```

```
CONTAINER ID   IMAGE                                         COMMAND                  CREATED         STATUS                         PORTS      NAMES
d059d3ae9cf5   harbor.swokiz.dev/hub-proxy/n8nio/n8n:1.0.1   "tini -- /docker-ent…"   3 minutes ago   Restarting (1) 5 seconds ago              by-ansible_n8n-worker_1
34504f0895d7   harbor.swokiz.dev/hub-proxy/n8nio/n8n:1.0.1   "tini -- /docker-ent…"   3 minutes ago   Restarting (1) 6 seconds ago              by-ansible_n8n_1
60b88b0a512c   redis:6-alpine                                "docker-entrypoint.s…"   4 minutes ago   Up 4 minutes (healthy)         6379/tcp   by-ansible_redis_1
```

**Expected behavior**

**Environment (please complete the following information):**

- OS: Debian
- n8n Version 1.0.1
- Node.js Version n8nio/n8n:1.0.1
- Database system Postgres
- Operation mode queue

**Additional context**
