### ISSUE TITLE
withPostgresAndWorker docker-compose example "worker service" not working

### ISSUE THREAD

**Issue by zadokdaniel** [n8n-io/n8n#6678]
When running the docker-compose file withPostgresAndWorker the worker service fails with 
`su-exec: worker: No such file or directory message

**To Reproduce**
run `docker-compose up -d` in the "compose/withPostgres/withPostgresAndWorker" example directory
and review worker service logs in docker

**Expected behavior**
expected worker to run and receive jobs

**Environment**
- OS: Ubuntu Linux 22.04 on WSL2
- n8n Version: 0.236.2
- Node.js Version: v16.20.1
- Database system: Postgress, Redis
- Operation mode: queue

**Additional context**
the problem occurs in the example directory for the docker-compose of running n8n with worker, postgres and redis
figured out based on the "/docker-entrypoint.sh"
```sh
if [ "$#" -gt 0 ]; then
  # Got started with arguments
  **exec su-exec node "$@"**
else
  # Got started without arguments
  exec su-exec node n8n
fi
``` 

while in the docker-compose file, it is set to only the "worker" command
```yaml
  n8n-worker:
    <<: *shared
    command: **worker**
    depends_on:
      - n8n
```
to fix need to add 
```yaml
  n8n-worker:
    <<: *shared
    command: **n8n** worker
    depends_on:
      - n8n
 ```

What is the preferred way to fix this? Change the docker-compose example file or the entry point file?
