### ISSUE TITLE
environment  variable [WEBHOOK_URL] take no effect on webhook Test URL 

### ISSUE THREAD

**Issue by dangehub** [n8n-io/n8n#6722]
**Describe the bug**
In docker ,the environment  variable  `WEBHOOK_URL=mydomain` does not  configure the `webhook Test URL` , It only works for `webhook_Production URL`

**To Reproduce**

1. install n8n in docker just like:
```
version: '3.3'
services:
  n8nio:
    container_name: n8n
    ports:
      - '5678:5678'
    volumes:
      - ./data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=xxx
      - TZ=xxx
      - N8N_HOST=mydomain
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=https://mydomain/
      - N8N_EDITOR_BASE_URL=https://mydomain:5678/
    image: docker.n8n.io/n8nio/n8n
```
2. use ngnix for reverse proxy(I use ngnix proxy manager in docker)
![image](https://github.com/n8n-io/n8n/assets/61233621/5dd0164d-926e-44ce-b48e-734e2a02e550)

**Expected behavior**
I find this:
![image](https://github.com/n8n-io/n8n/assets/61233621/3e6a140a-4cf9-4d78-895c-f9c6a77f8b5c)

**Environment (please complete the following information):**

- OS: Linux version 5.10.0-23-cloud-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.179-1 (2023-05-12)
- n8n Version 0.236.3
- Database system SQLite
- Operation mode main

**Additional context**
none
