### ISSUE TITLE
Custom Docker builds failing ? 

### ISSUE THREAD

**Issue by accforgithubtest** [n8n-io/n8n#6840]
**Describe the bug**
Docker builds failing using the latest alpine image, used to be working until last week. Issue started [at least] since 30 Jul.
Fails at the step - "RUN apk update"

**To Reproduce**

1. Create a sample github project
2. Create below dockerfile - [yourgithubproject]/Dockerfile
```
FROM n8nio/n8n:latest

RUN apk update 
RUN apk add busybox-extras
```
4. Create below file for github actions - [yourgithubproject]/.github/workflows/build.yml
```
name: Build and Publish Docker Image
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yourdockerhubusername/n8n:alpine
```
5. See error
```
build-and-push-image
buildx failed with: ERROR: failed to solve: executor failed running [/bin/sh -c apk update]: exit code: 99
```

**Expected behavior**
Docker image is built and published to dockerhub. Used to be working until last week. Issue started [at least] since 30 Jul.

**Environment (please complete the following information):**
Use github actions. No other customization, other than the 2 files mentioned above.
Remember to set your own DOCKER_USERNAME (Dockerhub account id) and DOCKER_PASSWORD (Dockerhub token) and set them in github under the projects settings > secrets > actions.
