### ISSUE TITLE
init-data.sh not autorun in docker compose, postgres user not auto create

### ISSUE THREAD

**Issue by Innei** [n8n-io/n8n#6906]
**Describe the bug**

The docker compose with postgres is not working, got this n8n log.

```
n8n-postgres-1  |
n8n-postgres-1  | 2023-08-10 11:20:55.025 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
n8n-postgres-1  | 2023-08-10 11:20:55.025 UTC [1] LOG:  listening on IPv6 address "::", port 5432
n8n-postgres-1  | 2023-08-10 11:20:55.027 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
n8n-postgres-1  | 2023-08-10 11:20:55.037 UTC [27] LOG:  database system was shut down at 2023-08-10 11:20:53 UTC
n8n-postgres-1  | 2023-08-10 11:20:55.041 UTC [1] LOG:  database system is ready to accept connections
n8n-n8n-1       | License manager not initialized
n8n-n8n-1       | Last session crashed
n8n-postgres-1  | 2023-08-10 11:21:13.063 UTC [65] FATAL:  password authentication failed for user "changeUser"
n8n-postgres-1  | 2023-08-10 11:21:13.063 UTC [65] DETAIL:  Role "changeUser" does not exist.
n8n-postgres-1  | 	Connection matched pg_hba.conf line 95: "host all all all md5"
n8n-n8n-1 exited with code 0
n8n-n8n-1       | License manager not initialized
n8n-n8n-1       | Last session crashed
n8n-postgres-1  | 2023-08-10 11:21:27.837 UTC [90] FATAL:  password authentication failed for user "changeUser"
n8n-postgres-1  | 2023-08-10 11:21:27.837 UTC [90] DETAIL:  Role "changeUser" does not exist.
```

I didn't change `.env` content, also password and username. But I try to change it, also can not startup n8n.

My `.env` as below

```sh
POSTGRES_USER=root
POSTGRES_PASSWORD=abcdazzzzzzz,,...
POSTGRES_DB=n8n

POSTGRES_NON_ROOT_USER=changeUser
POSTGRES_NON_ROOT_PASSWORD=changePassword
```

Maybe postgress initialize failed. The `init-data.sh` is not autorun when the postgres container is created.

I added this code in init-data.sh

```
#!/bin/bash
set -e;

echo "Pure data" # echo this
if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi
```

But echo info not print.

**To Reproduce**

Clone this folder `https://github.com/n8n-io/n8n/tree/master/docker/compose/withPostgres`.

Then run `docker compose up`.

**Expected behavior**

**Environment (please complete the following information):**

Docker version 24.0.5, build ced0996600

```
                   -`                    innei@arch
                  .o+`                   ----------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-7.2)
               `+oooooo:                 Kernel: 6.1.39-3-lts
               -+oooooo+:                Uptime: 3 days, 6 hours, 55 mins
             `/:-:++oooo+:               Packages: 231 (pacman)
            `/++++/+++++++:              Shell: fish 3.6.1
           `/++++++++++++++:             Resolution: 1280x800
          `/+++ooooooooooooo/`           Terminal: /dev/pts/0
         ./ooosssso++osssssso+`          CPU: Intel Pentium Gold 7505 (3) @ 1.996GHz
        .oossssso-````/ossssss+`         GPU: 00:02.0 Vendor 1234 Device 1111
       -osssssso.      :ssssssso.        Memory: 988MiB / 2970MiB
      :osssssss/        osssso+++.
     /ossssssss/        +ssssooo/-
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
```

**Comment by Joffcom** [comment]
Hey @Innei,

I have just ran the example without making any changes and for me it is working as expected. Can you try deleting both images then running it again without making any changes?

**Comment by Innei** [comment]
I try `sudo docker volume prune` to cleanup the volume, and use `sudo docker compose up --force-recreate` to recreate, also not work
 
```
innei@arch ~/d/n8n> sudo docker compose up --force-recreate
[+] Running 2/0
 ✔ Container n8n-postgres-1  Recreated                                                                                                        0.0s
 ✔ Container n8n-n8n-1       Recreated                                                                                                        0.0s
Attaching to n8n-n8n-1, n8n-postgres-1
n8n-postgres-1  |
n8n-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
n8n-postgres-1  |
n8n-postgres-1  |
n8n-postgres-1  | 2023-08-10 12:02:00.203 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
n8n-postgres-1  | 2023-08-10 12:02:00.203 UTC [1] LOG:  listening on IPv6 address "::", port 5432
n8n-postgres-1  | 2023-08-10 12:02:00.206 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
n8n-postgres-1  | 2023-08-10 12:02:00.215 UTC [26] LOG:  database system was shut down at 2023-08-10 12:01:37 UTC
n8n-postgres-1  | 2023-08-10 12:02:00.220 UTC [1] LOG:  database system is ready to accept connections
n8n-n8n-1       | Last session crashed
n8n-postgres-1  | 2023-08-10 12:02:17.889 UTC [58] FATAL:  password authentication failed for user "changeUser"
n8n-postgres-1  | 2023-08-10 12:02:17.889 UTC [58] DETAIL:  Role "changeUser" does not exist.
n8n-postgres-1  | 	Connection matched pg_hba.conf line 95: "host all all all md5"
n8n-n8n-1 exited with code 0
n8n-n8n-1       | Last session crashed
```

**Comment by Innei** [comment]
And I pulled lasted images. This is my docker-compose file, I just change the postgres volume mapped path.

```yml
version: '3.8'

volumes:
  db_storage:
  n8n_storage:

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - ../docker/db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

```
