### ISSUE TITLE
Got issue my data and workflow missing when update latest version 1.1.1

### ISSUE THREAD

**Issue by mzayn** [n8n-io/n8n#6979]
**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04] - Ubuntu 22.04.2 LTS aarch64(Py3.7.8)
- n8n Version [e.g. 1.0.1] - 1.1.1
- Node.js Version [e.g. 18.16.0] - 18.16
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed] - Default
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`] - Docker / Portainer - own 

**Additional context**

How to get back my data and workflow and credential was saved in previous version 0.236.2

and i was loses my data there with my credential login was been reset.

**Comment by Joffcom** [comment]
Hey @mzayn,

In v1 we changed the user that is used, can you check that the user in portainer is node and not root and that the working path is /home/node and not /data.

It could also be worth running the command from the migration guide that updates the permissions.

**Comment by mzayn** [comment]
> Hey @mzayn,
> 
> In v1 we changed the user that is used, can you check that the user in portainer is node and not root and that the working path is /home/node and not /data.
> 
> It could also be worth running the command from the migration guide that updates the permissions.

hi @Joffcom,

i see my volume in /home/node 

can your check my config here correct in env. 

```
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "127.0.0.1:4433:5678"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(${SUBDOMAIN}.${DOMAIN_NAME})
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000

    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - VUE_APP_URL_BASE_API=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      #   - WEBHOOK_TUNNEL_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=${SMTP_HOST}
      - N8N_SMTP_PORT=465
      - N8N_SMTP_USER=${SMTP_USER}
      - N8N_SMTP_PASS=${SMTP_PASSWORD}
      - N8N_SMTP_SENDER=${SMTP_SENDER}
      - N8N_SMTP_SSL=true
      - EXECUTIONS_DATA_PRUNE=${DATA_PRUNE}
      - EXECUTIONS_DATA_MAX_AGE=${DATA_MAX_AGE}
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=${DATA_PRUNE_MAX_COUNT}
      - N8N_PUSH_BACKEND=sse

    volumes:
      - ${DATA_FOLDER}/.n8n:/home/node/.n8n
      - /home/my-n8n/n8n-local-files:/files
      ```
      
      that better use sse or webhook for push backend ?
