### ISSUE TITLE
No ARM build for ai-beta or wrong entrypoint script path

### ISSUE THREAD

**Issue by ms1design** [n8n-io/n8n#7389]
**Describe the bug**
Docker Base image tagged `:ai-beta` fails to start on **NVIDIA Jetson AGX Orin 64GB**
```
exec /sbin/tini: exec format error
```
The `:latest` tag without `LangChain` work fine.

**To Reproduce**

1. Lanuch a `docker-compose` with base image `docker.n8n.io/n8nio/n8n:ai-beta`
2. See error

`docker-compose.yaml`:
```
n8n:
    image: docker.n8n.io/n8nio/n8n:ai-beta
    restart: unless-stopped
    runtime: nvidia
    container_name: n8n
    hostname: n8n
    ports:
      - "${ENV_N8N_PORT}:5678"
    environment:
      N8N_HOST: localhost
      N8N_PORT: "${ENV_N8N_PORT}"
      N8N_PROTOCOL: http
      NODE_ENV: production
      TZ: ${ENV_TZ}
      GENERIC_TIMEZONE: ${ENV_TZ}
    volumes:
      - n8n_data:/home/node/.n8n
```

**Expected behavior**
Docker should not fail.

**Environment (please complete the following information):**

- OS: `Ubuntu Linux 20.04`
- n8n Version: `beta`
- Node.js Version: `18.17.1`
- Database system: `SQLite`
- Operation mode: `main`
