### ISSUE TITLE
Crash loop upgrading from 1.8.2 to 1.9.3

### ISSUE THREAD

**Issue by vmstan** [n8n-io/n8n#7413]
**Describe the bug**
I'm currently running n8n in a Kubernetes environment, with a dedicated external database. I have been running 1.8.2 for a while, and got a notice that 1.9.3 was available.

After changing my yaml manifest to use `image: ghcr.io/n8n-io/n8n:1.9.3` and the newly launched pod goes into a crash loop with the following error:

```
Initializing n8n process
Error: There was an error initializing DB
DatabaseError: no pg_hba.conf entry for host "10.118.0.2", user "n8n", database "n8n", no encryption
```

Reverting the manifest back allows a 1.8.2 to start.

**To Reproduce**
Attempt to upgrade from 1.8.2 to anything after 1.9.x

**Expected behavior**
n8n connects to the database

**Environment (please complete the following information):**

- OS Containerized
- n8n Version 1.8.2 --> 1.9.3
- Node.js Version Containerized
- Postgres 15.4 (Digital Ocean managed)

**Additional context**
I reviewed the release notes for all versions between them, and didn't see anything about changes to Postgres configuration.

Here is a redacted copy of the deployment manifest.

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n
spec:
  selector:
    matchLabels:
      app: n8n
  serviceName: "n8n-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: n8n
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: s-4vcpu-16gb-amd
      containers:
      - name: n8n
        image: ghcr.io/n8n-io/n8n:1.8.2
        resources:
          requests:
            memory: "512Mi"
            cpu: "125m"
          limits:
            cpu: "500m"
            memory: "2G"
        ports:
        - containerPort: 5678
        volumeMounts:
        - mountPath: /home/node/.n8n
          name: data
        env:
        - name: GENERIC_TIMEZONE
          value: America/Chicago
        - name: TZ
          value: America/Chicago
        - name: N8N_ENCRYPTION_KEY
          value: xxx
        - name: WEBHOOK_URL
          value: https://n8n.vmst.io/
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: http
        - name: N8N_EMAIL_MODE
          value: smtp
        - name: N8N_SMTP_HOST
          value: xxx
        - name: N8N_SMTP_SSL
          value: "true"
        - name: N8N_SMTP_PORT
          value: "465"
        - name: N8N_SMTP_USER
          value: xxx
        - name: N8N_SMTP_PASS
          value: xxx
        - name: N8N_SMTP_SENDER
          value: n8n@ses.vmst.io
        - name: DB_POSTGRESDB_DATABASE
          value: n8n
        - name: DB_POSTGRESDB_HOST
          value: xxx
        - name: DB_POSTGRESDB_PORT
          value: "25060"
        - name: DB_POSTGRESDB_USER
          value: n8n
        - name: DB_POSTGRESDB_PASSWORD
          value: xxx
        - name: DB_TYPE
          value: postgresdb
        - name: PGSSLMODE
          value: no-verify
        livenessProbe:
          tcpSocket:
            port: 5678
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5678
          timeoutSeconds: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /healthz
            port: 5678
          failureThreshold: 30
          periodSeconds: 5
          initialDelaySeconds: 30
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
```

The same behaviors were observed with other pre-release versions after 1.8.2.
