### ISSUE TITLE
Cant Connect to PostgresSql sqlmode=require

### ISSUE THREAD

**Issue by danztensai** [n8n-io/n8n#75]
I've created 
```
version: '3.1'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=myhost
      - DB_POSTGRESDB_PORT=myport
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=userpostgres
      - DB_POSTGRESDB_PASSWORD=mypass
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
    ports:
      - 5678:5678
    volumes:
      - ~/.n8n:/root/.n8n
    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 5; n8n start"

```
Everything went smoothly until I tried to use Postgresdb that using ssl which is sslmode=require 
did n8n will support sslmode=require on postgresdb or am I missing something like missing some ENV that need to assign so it can work with ssl mode?
because i got an error like this

```
Attaching to n8n_n8n_1
n8n_1  | (node:1) UnhandledPromiseRejectionWarning: Error: There was an error: no pg_hba.conf entry for host "36.79.255.231", user "doadmin", database "n8n", SSL off
n8n_1  |     at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:22:17)
n8n_1  |     at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:57:23)
n8n_1  |     at /usr/local/lib/node_modules/n8n/dist/commands/start.js:105:22
n8n_1  |     at processTicksAndRejections (internal/process/task_queues.js:85:5)
n8n_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
n8n_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
