### ISSUE TITLE
Executions running forever - Can't cancel

### ISSUE THREAD

**Issue by pablorq** [n8n-io/n8n#7754]
**Describe the bug**
Some workflow executions are running forever and can't be canceled nor stopped. The behavior seems to be random, because affects to any workflow.

Most of the executions goes well, but some keep running forever. All workflows had a timeout on its settings.

It is happening along different n8n versions up until 1.15.2 (last time happened).

Attached screenshots are below.

**To Reproduce**

- Unknown. No steps found to reproduce it.

**Expected behavior**
1. Do not keep running.
2. Respect the timeout settings.
3. Raise an error.

**Environment (please complete the following information):**
- OS: Ubuntu Linux 23.10
- n8n Version: 1.15.2
- Node.js Version: ?
- Database system: postgresql
- Operation mode: ? [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**
Screenshot: Running forever
![Screenshot 2023-11-17 at 15-33-43 n8n - Executions 02](https://github.com/n8n-io/n8n/assets/774839/a9a83214-a4a2-41f1-96fb-ce16149d971a)

Screenshot: Can't cancel
![Screenshot 2023-11-17 at 15-34-40 n8n - Executions 02](https://github.com/n8n-io/n8n/assets/774839/4852fe54-85eb-4f4a-b50b-790b15128f06)

**Comment by pablorq** [comment]
Already checked #5561 and #7442, but doesn't seem the same issue.

**Comment by pablorq** [comment]
The only way that I've found to stop them is to restarting the docker stack (using portainer).

**Comment by Joffcom** [comment]
Hey @pablorq,

That error looks like it may already have been stopped in the background, Can you share more about your setup? Are you using a reverse proxy, do you have cloudflare or similar involved?

Next time you see this issue if you connect using the direct IP of your n8n container it would be interesting to see if you see the same thing. Are you also running in queue mode or do you just have the one n8n instance running?

**Comment by pablorq** [comment]
Hi @Joffcom,

I'm running n8n in a simple way, just an local stack with one instance.

When you said "stopped in the background", do you mean that the task was already stopped but not reported to the UI? Is there any check or debug that I can run inside the container?


This is my docker-compose like file (I'm using Portainer):

```yaml
# n8n with persistent volume Postgres
# https://raw.githubusercontent.com/n8n-io/n8n/master/docker/compose/withPostgres/docker-compose.yml

version: '3.8'

volumes:
  db_data:
  main_data:

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ${N8N_LOCAL_FILES}/n8n-config/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  main:
    image: docker.n8n.io/n8nio/n8n:${N8N_VERSION}
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - main_data:/home/node/.n8n
      - ${N8N_LOCAL_FILES}:/files
    depends_on:
      postgres:
        condition: service_healthy
    user: root
    entrypoint: sh -c
    command:
      - |
        npm install -g @mozilla/readability jsdom
        su node -c "tini -s -- /docker-entrypoint.sh &"
        sleep infinity

    extra_hosts:
    # Access host localhost
      - "local.host:host-gateway"


# environment
# N8N_VERSION=1.3.1
```

As you can see, I've to modify the entrypoint to install some Code.js modules, but it shouldn't break anything.
