### ISSUE TITLE
n8n is taking a lot of RAM memory

### ISSUE THREAD

**Issue by pablorq** [n8n-io/n8n#7939]
**Describe the bug**
The n8n process is taking a lot of RAM memory, in this case 1.1 GB, and 41.7 GB of virtual memory.

**To Reproduce**

1. Install n8n using Docker/Portainer
2. Use it with some workflows managing some data (5000 rows in a Google Sheets, for instance)
3. Check the System Monitor.
4. See RAM memory  consumption

**Expected behavior**
A little memory consumption when idle. If taking a lot of memory during a workflow run, release it when it ends.

**Environment (please complete the following information):**
- OS: Ubuntu Linux 23.10
- n8n Version: 1.16.0
- Node.js Version: ?
- Database system: postgresql
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**
Here are some screenshots.
All process list sort by memory:
![Screenshot from 2023-12-05 20-44-08](https://github.com/n8n-io/n8n/assets/774839/d9fbfcd2-9d01-4666-98af-7125b2c2c1e5)

n8n process details:
![Screenshot from 2023-12-05 20-46-59](https://github.com/n8n-io/n8n/assets/774839/11f80d64-b8ae-46e4-a6a4-b39d5d5b965a)

I did a new fresh install of the same Docker stack, without any workflow, and the memory consumption seems to be low. This makes me thing about this could be a (or some) workflow that is taking a lot memory, or that successive running keep increasing the memory  without release it.

In any case the memory should be freed when no workflow is running.

**Comment by Joffcom** [comment]
Hey @pablorq,

n8n loads things into memory while working so I would expect it to grow and to also be higher the more items you are using but the memory itself will drop down.

Can you check the Portainer memory stats while your workflow is running to check if that is showing the memory being released? I would expect that you would see that grow then decrease a few seconds after the workflow has finished.

Or can you check the container stats using the docker command to see what that shows, it could be that the 1GB is reserved but only 300mb is being used.

**Comment by pablorq** [comment]
Hi @Joffcom !

Maybe I didn't express myself correctly: this data is taken when no workflow was running.

I just was speculating about what could be happen when I've talked about the workflow using Google Sheet to move a lot of data, because is the only one that I can relate with a high memory use. But maybe it's another thing.

To give you more detail, I have 7 workflows that activate by time (RSS trigger or schedule trigger), most of them every 3 hours and 2 of them every hour. Most of the time is a sequence like "run, check everything is ok, end". That is something that takes a minute or so.

When no workflow is running is when I have this memory consumption. In fact, now is 1.5GB.

This is the container stats:
![Screenshot 2023-12-07 at 10-37-40 Portainer local](https://github.com/n8n-io/n8n/assets/774839/1dc394bc-ecaf-4afa-8f9d-acdbe87c5a0f)

This is more info from inside de container:
```
/home/node # top
Mem: 21443940K used, 2516304K free, 1060796K shrd, 307824K buff, 5260444K cached
CPU:   7% usr  13% sys   0% nic  79% idle   0% io   0% irq   0% sirq
Load average: 2.14 2.43 2.29 2/2239 65
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   23    21 node     S    42.1g 169%   5   0% node /usr/local/bin/n8n
   52     0 root     S     1672   0%   0   0% sh
    1     0 root     S     1604   0%   2   0% sh -c whoami pwd npm install -g @mozilla/readability jsdom echo "done install" su node -c "tini -s -- /docker-entrypoint.sh &" sl
   65    52 root     R     1600   0%   0   0% top
   22     1 root     S     1588   0%   2   0% sleep infinity
   21     1 node     S      816   0%   6   0% tini -s -- /docker-entrypoint.sh
/home/node # free -h
              total        used        free      shared  buff/cache   available
Mem:          22.8G       13.5G        2.4G        1.0G        7.0G        7.7G
Swap:         32.0G        7.5G       24.5G
```

## Important info
Now I've noticed that I have 3 "forever running" executions (issue #7754).

I don't know if that is related, I didn't check it when first I've opened this issue.

I'm still in v1.16.0. I'm going to upgrade and see how everything works.

**Comment by Joffcom** [comment]
Hey @pablorq,

I was just looking at my own instance that has about 40 active workflows on it and I have a very different graph, This is after running 2948 workflows since the last restart which I think was yesterday.

![image](https://github.com/n8n-io/n8n/assets/4688521/a6885123-c649-467f-9edf-cc503a8e8a08)

This is n8n running in Portainer using a Postgres database as well, Out of interest if you start up a new instance that doesn't add the extra node package and just runs like normal do you also see the same usage?

Can you also share the environment variables and portainer settings you have configured, As an example in portainer have you set any of the Runtime & Resources options or Capabilities?

**Comment by pablorq** [comment]
Hi @Joffcom !

I've upgraded today to v1.18.2 and by now (a couple of hours) it seems pretty good.

Look at this:
![Screenshot 2023-12-07 at 14-52-59 Portainer local](https://github.com/n8n-io/n8n/assets/774839/1deef6e5-481d-47c6-9987-8b42aa35ac0e)

This is my portainer stack editor (docker-compose style). This is also n8n+postgres (I would prefer mariadb, by the way):
```yaml
# n8n with persistent volume Postgres
# https://raw.githubusercontent.com/n8n-io/n8n/master/docker/compose/withPostgres/docker-compose.yml

version: '3.8'

volumes:
  db_data:
  main_data:

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ${N8N_LOCAL_FILES}/n8n-config/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  main:
    image: docker.n8n.io/n8nio/n8n:${N8N_VERSION}
#    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - main_data:/home/node/.n8n
      - ${N8N_LOCAL_FILES}:/files
    depends_on:
      postgres:
        condition: service_healthy
    user: root
    entrypoint: sh -c
    command:
      - |
        whoami
        pwd
        npm install -g @mozilla/readability jsdom
        echo "done install"
        su node -c "tini -s -- /docker-entrypoint.sh &"
        sleep infinity

    extra_hosts:
    # Access host localhost
      - "local.host:host-gateway"
```

One question: what do you mean about Runtime & Resources options or Capabilities? I think the only thing configured is the timezone.
