### ISSUE TITLE
Migration failure in fresh install with external Mysql DB

### ISSUE THREAD

**Issue by Hobbit44** [n8n-io/n8n#7999]
**Describe the bug**
The migration "MigrateIntegerKeysToString1690000000001" fails with the error:

```
Starting migration MigrateIntegerKeysToString1690000000001
Error: There was an error running database migrations
QueryFailedError: Unknown collation: 'utf8mb4_0900_ai_ci'
```

**To Reproduce**
Start a docker stack with the following configuration:

<details><summary>docker-compose.yml</summary>

```
version: "3.9"
services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_DATABASE=n8n
      - MARIADB_USER=auser
      - MARIADB_PASSWORD=apassword
      - MYSQL_ROOT_PASSWORD=arootpassword
    volumes:
      - /mnt/dockerdata/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=aurl
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=anotherurl
      - GENERIC_TIMEZONE=Europe/London
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_DATABASE=n8n
      - DB_MYSQLDB_HOST=mariadb
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_USER=auser
      - DB_MYSQLDB_PASSWORD=apassword
    volumes:
      - /mnt/dockerdata/n8n:/home/node/.n8n
```
You may need to create a database if the image doesnt do it automatically. I used `CREATE DATABASE n8n CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;`

</details> 

**Expected behavior**
I would expect it to start. Or give me an error if im using a version that no longer supports MySQL.

**Environment (please complete the following information):**

- OS: Ubuntu Server 22.04
- n8n Version: 1.18.2 (Docker Latest)
- Database system: MySQL
- Operation mode: main

**Additional context**
I have now noticed the massive box saying MySQL is deprecated, but that isnt obvious if you miss it and try to install. Feel free to close this as a non issue but i would reccomend removing mysql from the docs if its no longer functional
