### ISSUE TITLE
Permission error when trying to mount directories

### ISSUE THREAD

**Issue by creyD** [n8n-io/n8n#8272]
**Describe the bug**
I get permission errors with a docker-compose file for a selfhosted n8n instance. I believe the problem is that in the Dockerfile of n8n the service is handed to the node user, but on my host system I don't have such a user. I tried giving the folder that I am mapping into the container 777 permissions and being owned by the user that runs the docker process, but it seems to be ineffective.

**To Reproduce**

1. Create docker-compose file with the following config:

```
n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - N8N_HOST=n8n:8081
      - N8N_PORT=8081
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - DB_TYPE=postgresdb
      - DB_TABLE_PREFIX=n8n_
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
    volumes:
      - ./DOCKER/n8n/data:/home/node/.n8n
      - ./DOCKER/n8n/files:/files
    depends_on:
      db:
        condition: service_healthy
```
2. Start the docker compose in a GitHub action runner, which is running as the runner user
3. Create the DOCKER/n8n directory before and give it 777 permissions and let the runner own it (optional, tried with and without this step)
4. The service logs as `Error: EACCES: permission denied, open '/home/node/.n8n/config'`

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version: latest
- Database system: Postgres, but should work independent of this
- Operation mode: main

**Additional context**
This is part of our testing pipeline, so we are getting up the whole service as docker compose and run tests against the n8n API.
