### ISSUE TITLE
REDIS Cluster Mode Fails To Connect With TLS

### ISSUE THREAD

**Issue by ersinors** [n8n-io/n8n#8543]
**Describe the bug**
I have an AWS ElasticCache Serverless Instance. I can connect with 'redis-cli' but n8n can not connect and gives the following error :

```
Error with Redis: 
n8n_1  | Redis unavailable - trying to reconnect...
n8n_1  | [ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
n8n_1  |     at tryNode (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/cluster/index.js:308:31)
n8n_1  |     at /usr/local/lib/node_modules/n8n/node_modules/ioredis/built/cluster/index.js:325:21
n8n_1  |     at /usr/local/lib/node_modules/n8n/node_modules/ioredis/built/cluster/index.js:662:24
n8n_1  |     at run (/usr/local/lib/node_modules/n8n/node_modules/ioredis/built/utils/index.js:117:22)
n8n_1  |     at tryCatcher (/usr/local/lib/node_modules/n8n/node_modules/standard-as-callback/built/utils.js:12:23)
n8n_1  |     at /usr/local/lib/node_modules/n8n/node_modules/standard-as-callback/built/index.js:33:51
n8n_1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
``` 

**To Reproduce**

1. Create AWS ElasticCache Serverless.
2. Create EC2 Instance.
3. Update security inbound and outbound rules.
4. Install docker-compose and docker related stuff.
5. Use this docker-compose file :
```yaml
version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "80:5678"
    env_file:
      - ./.env
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
      - /root/n8n:/files

volumes:
  n8n_data:
```
With following .env file in the same directory :
```
QUEUE_BULL_REDIS_TLS=true
QUEUE_BULL_REDIS_CLUSTER_NODES=redacted:6379
```

**Expected behavior**
N8N should work.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version latest.
- Database system postgresql.
- Operation mode queue.
