### ISSUE TITLE
Waiting Executions do not work correctly when changing time zone

### ISSUE THREAD

**Issue by directpromo** [n8n-io/n8n#8548]
**Describe the bug**
With the default time zone GMT 0, everything works correctly.

For time zones from GMT - 1 to GMT - 11 workflow freezes. In waiting status.

For time zones from GMT +1 to GMT +14 workflow goes to status successful within about 1 minute. Even if you need to wait for an hour or 5 minutes.

**To Reproduce**
1. create a workflow for waiting 
2. set the time zone in the workflow settings
3. run
4. see the result in the executions
5. repeat several times with different time zones

**Environment:**

- OS:  Ubuntu Linux 22.04
- n8n Version 1.27.2
- Database  POSTGRES
- EXECUTIONS_MODE=regular

**Additional context**
The bug also occurs if you set the timezone in .env via: 
GENERIC_TIMEZONE=your time zone
TZ=your time zone

**Comment by directpromo** [comment]
Hi  @Joffcom,

I don't quite understand the question. 

I made a screencast. It shows this bug.

https://github.com/n8n-io/n8n/assets/42971248/1354afac-5b75-424f-9997-7f317dbc1f8d

https://drive.google.com/file/d/1hLqwqb3rP-dP7Jl2juvYz-kzX1E2srGi/view?usp=sharing

**Comment by Joffcom** [comment]
Hey @directpromo,

I have done a bit of testing and I managed to reproduce it as my database was still using the UTC timezone, I have not done a lot of testing around starting a new database with the correct timezone configuration but I do wonder if that is linked.

For now I have created an internal ticket which we will be tracking as `PAY-1341`.

**Comment by stwonary** [comment]
I am experiencing a similar issue with my workflows in n8n, particularly around the handling of different time zones. It seems there is a discrepancy in how workflows proceed or freeze based on the time zone settings, which mirrors the problem described.

To reproduce this issue, I've been using the following Docker Compose file:

```yaml
version: '3.1'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
      - WEBHOOK_TUNNEL_URL=http://localhost:5678/
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=password
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
```

<img width="728" alt="image" src="https://github.com/n8n-io/n8n/assets/59780143/279b47fa-24ea-42b4-a4e6-469304471e92">



And in my workflows, I've observed that a 3-minute Wait node is incorrectly storing timestamps in the database 5 hours in the future, potentially due to the default `GENERIC_TIMEZONE` setting, which is `America/New_York` (GMT-5).

I am running this with n8n version 1.29.1, utilizing a PostgreSQL database. The issue persists regardless of setting the time zone in the workflow settings or via the `.env` file using `GENERIC_TIMEZONE` and `TZ` variables.

Current time:
<img width="631" alt="image" src="https://github.com/n8n-io/n8n/assets/59780143/11bbff6f-ae1e-40ca-a056-6f36be719b87">

Workflow `waitTill` in database:

<img width="385" alt="image" src="https://github.com/n8n-io/n8n/assets/59780143/f9d947fd-9f01-4cd8-b8f8-951cc247cb93">
