### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: There was an error: Port should be >= 0 and < 65536. Kubernetes.

### ISSUE THREAD

**Issue by aneurinprice** [n8n-io/n8n#88]
**Describe the bug**
n8n does not start on my kubernetes cluster with the following message:

```
UserSettings got generated and saved to: /root/.n8n/config
(node:1) UnhandledPromiseRejectionWarning: Error: There was an error: Port should be >= 0 and < 65536. Received NaN.
    at Object.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/errors/lib/index.js:22:17)
    at Start.error (/usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js:57:23)
    at /usr/local/lib/node_modules/n8n/dist/commands/start.js:112:22
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Apply the deployment
2. See error

**Expected behaviour**
n8n should start

**Environment (please complete the following information):**
 - OS: Debian 10
 - n8n Version Docker:latest
 - Node.js Version Docker:latest

**Additional context**

Kubernetes deployment used:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: n8n
  namespace: n8n
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - n8n.nyeprice.space
      secretName: n8n.nyeprice.space
  rules:
    - host: n8n.nyeprice.space
      http:
        paths:
          - path: /
            backend:
              serviceName: n8n
              servicePort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  selector:
    app: n8n
  ports:
    - port: 5678
      targetPort: 5678
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pv
  namespace: n8n
  labels:
    app: n8n
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20G
---
apiVersion: apps/v1  # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  selector:
    matchLabels:
      app: n8n
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: n8n
        tier: frontend
    spec:
      containers:
        - image: n8nio/n8n
          imagePullPolicy: Always
          name: n8n
          ports:
            - containerPort: 5678
              name: n8n
          env:
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              value: "aneurinprice"
            - name: N8N_BASIC_AUTH_PASSWORD
              value: "test"
          volumeMounts:
          - name: n8n-data
            mountPath: /root/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pv
```

**Comment by janober** [comment]
Hm, very strange. Never saw that error before. No idea why the port should end up to not be a number... Did you try to set the env variable `N8N_PORT`?

**Comment by aneurinprice** [comment]
I have now set the N8N_PORT var and it seems to be perfectly happy with that now (Thank you for that). Any idea why the default didn't work? I have tested in just docker rather than Docker + Kubernetes and it seems to be fine. This doesn't seem to be limited to just my cluster either.

**Comment by janober** [comment]
Great to hear!

Honestly not the slightest idea. Something must somehow send in a "strange" port. I am using `convict` for that. Not sure if there is something that gets set by Kubernetes that it picks up.

**Comment by Fusion** [comment]
I am seeing the same issue.
I tried to perform a rolling update to 0.41.0 and ended up with the same error.
Even more bizarre: I performed a rollback and the error was still there!

**Comment by janober** [comment]
@Fusion and you have `N8N_PORT` set?

**Comment by Fusion** [comment]
That's the confusing part: I do.

```
kubectl exec -it n8n-8dbc94878-959r2 sh
/data # env | grep N8N
N8N_SERVICE_HOST=10.110.101.178
N8N_BASIC_AUTH_ACTIVE=true
N8N_PORT=tcp://10.110.101.178:80
N8N_SERVICE_PORT=80
N8N_PORT_80_TCP_ADDR=10.110.101.178
N8N_PORT_80_TCP_PORT=80
N8N_PORT_80_TCP_PROTO=tcp
N8N_PORT_80_TCP=tcp://10.110.101.178:80
N8N_BASIC_AUTH_PASSWORD={redacted}
N8N_BASIC_AUTH_USER={redacted}
/data #
```

**Comment by janober** [comment]
Sorry, I do not understand. The answer is "yes" but to an invalid value but you can not set it to a valid one for some reason as `N8N_PORT` should just be a number?

**Comment by janober** [comment]
Btw. if nothing is overwriting it and you simply did not have it set. Here is an example for docker which will probably help to get the correct values for k8s:
https://docs.n8n.io/#/server-setup

**Comment by Fusion** [comment]
Actually, I was hoping you would tell me how you felt about that value ;)

I did not set these values myself so I guess they were somehow inferred by the container.
The only variables I set in my deployment file are: N8N_BASIC_AUTH_ACTIVE, N8N_BASIC_AUTH_USER and N8N_BASIC_AUTH_PASSWORD.

Ah, I see that you posted a link to a more comprehensive page which shows all these values. I based my K8S deployment on that page instead: https://github.com/n8n-io/n8n/blob/master/docker/images/n8n/README.md#start-n8n-in-docker

**Comment by janober** [comment]
Ah sorry, then I misunderstood you ;-)

Then it is really a good idea to check which environment variables are set in the docker-compose example and set the same ones to appropriate values. Then it should work fine.

**Comment by Fusion** [comment]
Yes, just did this and it seems to work nicely now.  Thanks!

@aneurinprice here is my deployment.yaml file:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - image: n8nio/n8n
        imagePullPolicy: Always
        name: n8n
        env:
        - name: N8N_BASIC_AUTH_ACTIVE
          value: "true"
        - name: N8N_BASIC_AUTH_USER
          value: "{redacted}"
        - name: N8N_BASIC_AUTH_PASSWORD
          value: "{redacted}"
        - name: N8N_PROTOCOL
          value: "http"
        - name: N8N_PORT
          value: "5678"
        - name: N8N_HOST
          value: "{redacted}"
        - name: WEBHOOK_TUNNEL_URL
          value: "{redacted}"
        - name: VUE_APP_URL_BASE_API
          value: "{redacted}"
        ports:
        - containerPort: 5678
        volumeMounts:
        - mountPath: /root/.n8n
          name: n8n
      volumes:
        - name: n8n
          persistentVolumeClaim:
            claimName: n8n-pvc
```
