### ISSUE TITLE
Wordpress create post - errors out on Author name or ID

### ISSUE THREAD

**Issue by datdamnzotz** [n8n-io/n8n#8851]
### Bug Description

![image](https://github.com/n8n-io/n8n/assets/3913859/bb349dbb-5084-414d-b429-3eee044d3a59)

### To Reproduce

Create wordpress docker container:

docker-compose.yaml 

```
version: '3.8'

services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:latest
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - /home/wordpress/db/:/var/lib/mysql/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    #expose:
    #  - 3306
    #  - 33060
    networks:
      - wordpress

  wordpress:
    image: wordpress:latest
    ports:
      - 88:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=1
      - WORDPRESS_CONFIG_EXTRA=define( 'WP_ENVIRONMENT_TYPE', 'local' );
    networks:
     - wordpress

networks:
  wordpress:
```

1. run docker-compose up on the wordpress docker-compose.yaml above so you can see the webserver logs produced by wordpress.
2. Open http://ip:88 and run setup steps for Wordpress and create admin user.
3. Create Wordpress Application [password](https://docs.n8n.io/integrations/builtin/credentials/wordpress/)
![image](https://github.com/n8n-io/n8n/assets/3913859/ecde4210-1cc9-45d5-a9e5-04958c739f8e)
4. Create n8n wordpress creds
![image](https://github.com/n8n-io/n8n/assets/3913859/02ddd078-6d94-43ef-b340-d2884e720204)
5. Login to n8n and add wordpress create post node.

![image](https://github.com/n8n-io/n8n/assets/3913859/82d6efb8-484b-4f30-8343-be4405b4d15f)

Observe failed login with 401 from the wordpress docker container.
```
wordpress-wordpress-1  | 172.27.0.1 - wordpressapi [08/Mar/2024:18:31:28 +0000] "GET /wp-json/wp/v2/users?who=authors&per_page=10&page=1 HTTP/1.1" **401** 643 "-" "n8n"
```

It is a interesting note that categories works, but users does not.
![image](https://github.com/n8n-io/n8n/assets/3913859/b805dbf7-1bef-4c45-9650-7c552a805cf1)

```
wordpress-wordpress-1  | 172.27.0.1 - wordpressapi [08/Mar/2024:18:32:02 +0000] "GET /wp-json/wp/v2/categories?per_page=10&page=1 HTTP/1.1" 200 1164 "-" "n8n"
```

### Expected behavior

Author Name or ID should popluate.

### Operating System

Ubuntu 22.04

### n8n Version

1.31.2

### Node.js Version

docker version

### Database

SQLite (default)

### Execution mode

main (default)
