### ISSUE TITLE
Docker image crash on n8nio/n8n:0.84.2

### ISSUE THREAD

**Issue by dokime7** [n8n-io/n8n#983]
**Describe the bug**
The container based on image n8nio/n8n:0.84.2 crash at starting

**To Reproduce**
1. docker pull n8nio/n8n:0.84.2
2. docker run...

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS
 - n8n Version 0.84.2

**Additional context**
Here containers logs:
```
n8n_1  |     Error: Cannot find module 'https-proxy-agent'
n8n_1  |     Require stack:
n8n_1  |     - /usr/local/lib/node_modules/n8n/node_modules/jwks-rsa/lib/wrappers/reque
n8n_1  |     st.js
n8n_1  |     - /usr/local/lib/node_modules/n8n/node_modules/jwks-rsa/lib/JwksClient.js
n8n_1  |     - /usr/local/lib/node_modules/n8n/node_modules/jwks-rsa/lib/index.js
n8n_1  |     - /usr/local/lib/node_modules/n8n/dist/src/Server.js
n8n_1  |     - /usr/local/lib/node_modules/n8n/dist/src/index.js
n8n_1  |     - /usr/local/lib/node_modules/n8n/dist/commands/start.js
n8n_1  |     - /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/plugin.js
n8n_1  |     - /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/config.js
n8n_1  |     - /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/index.js
n8n_1  |     - 
n8n_1  |     /usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js
n8n_1  |     - /usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/index.js
n8n_1  |     - /usr/local/lib/node_modules/n8n/bin/n8n
n8n_1  |     Code: MODULE_NOT_FOUND
n8n_1  | ln: /home/node/.n8n: File exists
```

docker-compose.yml
```
version: "3"

services:

  n8n:
    image: n8nio/n8n:0.84.2
    environment:
      GENERIC_TIMEZONE: Europe/Paris
      TZ: Europe/Paris
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: xxxx
      N8N_BASIC_AUTH_PASSWORD: xxxx
      N8N_HOST: mydomain.com
      N8N_PROTOCOL: https
      NODE_ENV: production
      WEBHOOK_TUNNEL_URL: https://mydomain.com/
      VUE_APP_URL_BASE_API: https://mydomain.com/
    volumes:
      - ./config:/root/.n8n
    restart: unless-stopped
```
